CREATE TABLE departments (
    department_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    department_name VARCHAR2(100) NOT NULL,
    floor_no NUMBER,
    status VARCHAR2(20) DEFAULT 'Active' NOT NULL,

    CONSTRAINT pk_departments
        PRIMARY KEY (department_id),

    CONSTRAINT uq_department_name
        UNIQUE (department_name),

    CONSTRAINT chk_department_status
        CHECK (status IN ('Active', 'Inactive'))
);


CREATE TABLE doctor_specialties (
    specialty_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    specialty_name VARCHAR2(100) NOT NULL,
    status VARCHAR2(20) DEFAULT 'Active' NOT NULL,

    CONSTRAINT pk_doctor_specialties
        PRIMARY KEY (specialty_id),

    CONSTRAINT uq_specialty_name
        UNIQUE (specialty_name),

    CONSTRAINT chk_specialty_status
        CHECK (status IN ('Active', 'Inactive'))
);


CREATE TABLE medicine_categories (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    category_name VARCHAR2(100) NOT NULL,
    status VARCHAR2(20) DEFAULT 'Active' NOT NULL,

    CONSTRAINT pk_medicine_categories
        PRIMARY KEY (category_id),

    CONSTRAINT uq_medicine_category_name
        UNIQUE (category_name),

    CONSTRAINT chk_medicine_category_status
        CHECK (status IN ('Active', 'Inactive'))
);


CREATE TABLE appointment_statuses (
    status_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    status_name VARCHAR2(50) NOT NULL,

    CONSTRAINT pk_appointment_statuses
        PRIMARY KEY (status_id),

    CONSTRAINT uq_appointment_status_name
        UNIQUE (status_name)
);