--create the table:
create table traffic_signals(
                                signal_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                signal_name     VARCHAR2(100) NOT NULL,
                                state           VARCHAR2(10) DEFAULT 'RED' NOT NULL
                  CONSTRAINT ck_signal_state CHECK (state IN ('RED','YELLOW','GREEN')),
                                last_changed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
--show table:
SELECT * FROM traffic_signals;
--test table by inserted row:
insert into traffic_signals (signal_name) VALUES ('Al Khuwair Signal');
COMMIT;

--create procedure that's check and update the signal status:
CREATE OR REPLACE PROCEDURE check_and_update_signal_status
(
    p_signal_id IN NUMBER
)
AS
    v_state              VARCHAR2(10);
    v_last_changed_at    TIMESTAMP;
    v_next_state         VARCHAR2(10);
    v_required_seconds   NUMBER;
BEGIN

SELECT state, last_changed_at
INTO v_state, v_last_changed_at
FROM traffic_signals
WHERE signal_id = p_signal_id;

IF v_state = 'RED' THEN
        v_next_state := 'YELLOW';
        v_required_seconds := 10;

    ELSIF v_state = 'YELLOW' THEN
        v_next_state := 'GREEN';
        v_required_seconds := 5;

ELSE
        v_next_state := 'RED';
        v_required_seconds := 10;
END IF;

    IF SYSTIMESTAMP >=
       v_last_changed_at +
       NUMTODSINTERVAL(v_required_seconds, 'SECOND')
    THEN

UPDATE traffic_signals
SET state = v_next_state,
    last_changed_at = SYSTIMESTAMP
WHERE signal_id = p_signal_id;

COMMIT;

END IF;

END check_and_update_signal_status;
/

--create PROCEDURE that's create Scheduler job
CREATE OR REPLACE PROCEDURE start_signal_watch
(
    p_signal_id IN NUMBER
)
AS
   PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN

    DBMS_SCHEDULER.CREATE_JOB(
        job_name        => 'SIG_WATCH_' || p_signal_id,
        job_type        => 'PLSQL_BLOCK',
        job_action      => 'BEGIN check_and_update_signal_status('
                           || p_signal_id || '); END;',
        repeat_interval => 'FREQ=SECONDLY;INTERVAL=5',
        start_date      => SYSTIMESTAMP,
        enabled         => TRUE
    );
COMMIT;
END start_signal_watch;
/

--create the trigger
CREATE OR REPLACE TRIGGER handle_traffic_signal_insert_event
AFTER INSERT ON traffic_signals
FOR EACH ROW
BEGIN
    start_signal_watch(:NEW.signal_id);
END handle_traffic_signal_insert_event;
/

--insert to see after add trigger
insert into traffic_signals (signal_name) VALUES ('Suhar Signal');
COMMIT;

insert into traffic_signals (signal_name) VALUES ('AL-Suwaiq Signal');
COMMIT;

--privilege
SELECT USER FROM dual;

GRANT CREATE JOB TO SYSTEM;



