SET DEFINE OFF;

-- ============================================================
-- Table: departments
-- ============================================================
MERGE INTO departments t
USING (SELECT 1 AS DEPARTMENT_ID, 'Cardiology' AS DEPARTMENT_NAME, 2 AS FLOOR_NO, 'Active' AS STATUS FROM dual) s
ON (t.DEPARTMENT_ID = s.DEPARTMENT_ID)
WHEN NOT MATCHED THEN INSERT (DEPARTMENT_ID, DEPARTMENT_NAME, FLOOR_NO, STATUS)
  VALUES (s.DEPARTMENT_ID, s.DEPARTMENT_NAME, s.FLOOR_NO, s.STATUS);
MERGE INTO departments t
USING (SELECT 2 AS DEPARTMENT_ID, 'Pediatrics' AS DEPARTMENT_NAME, 1 AS FLOOR_NO, 'Active' AS STATUS FROM dual) s
ON (t.DEPARTMENT_ID = s.DEPARTMENT_ID)
WHEN NOT MATCHED THEN INSERT (DEPARTMENT_ID, DEPARTMENT_NAME, FLOOR_NO, STATUS)
  VALUES (s.DEPARTMENT_ID, s.DEPARTMENT_NAME, s.FLOOR_NO, s.STATUS);
MERGE INTO departments t
USING (SELECT 3 AS DEPARTMENT_ID, 'Orthopedics' AS DEPARTMENT_NAME, 3 AS FLOOR_NO, 'Active' AS STATUS FROM dual) s
ON (t.DEPARTMENT_ID = s.DEPARTMENT_ID)
WHEN NOT MATCHED THEN INSERT (DEPARTMENT_ID, DEPARTMENT_NAME, FLOOR_NO, STATUS)
  VALUES (s.DEPARTMENT_ID, s.DEPARTMENT_NAME, s.FLOOR_NO, s.STATUS);
MERGE INTO departments t
USING (SELECT 4 AS DEPARTMENT_ID, 'General Medicine' AS DEPARTMENT_NAME, 1 AS FLOOR_NO, 'Active' AS STATUS FROM dual) s
ON (t.DEPARTMENT_ID = s.DEPARTMENT_ID)
WHEN NOT MATCHED THEN INSERT (DEPARTMENT_ID, DEPARTMENT_NAME, FLOOR_NO, STATUS)
  VALUES (s.DEPARTMENT_ID, s.DEPARTMENT_NAME, s.FLOOR_NO, s.STATUS);
MERGE INTO departments t
USING (SELECT 5 AS DEPARTMENT_ID, 'Emergency' AS DEPARTMENT_NAME, 'Ground' AS FLOOR_NO, 'Active' AS STATUS FROM dual) s
ON (t.DEPARTMENT_ID = s.DEPARTMENT_ID)
WHEN NOT MATCHED THEN INSERT (DEPARTMENT_ID, DEPARTMENT_NAME, FLOOR_NO, STATUS)
  VALUES (s.DEPARTMENT_ID, s.DEPARTMENT_NAME, s.FLOOR_NO, s.STATUS);

-- ============================================================
-- Table: doctor_specialties
-- ============================================================
MERGE INTO doctor_specialties t
USING (SELECT 1 AS SPECIALTY_ID, 'Cardiologist' AS SPECIALTY_NAME, 'Active' AS STATUS FROM dual) s
ON (t.SPECIALTY_ID = s.SPECIALTY_ID)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_ID, SPECIALTY_NAME, STATUS)
  VALUES (s.SPECIALTY_ID, s.SPECIALTY_NAME, s.STATUS);
MERGE INTO doctor_specialties t
USING (SELECT 2 AS SPECIALTY_ID, 'Pediatrician' AS SPECIALTY_NAME, 'Active' AS STATUS FROM dual) s
ON (t.SPECIALTY_ID = s.SPECIALTY_ID)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_ID, SPECIALTY_NAME, STATUS)
  VALUES (s.SPECIALTY_ID, s.SPECIALTY_NAME, s.STATUS);
MERGE INTO doctor_specialties t
USING (SELECT 3 AS SPECIALTY_ID, 'Orthopedic Surgeon' AS SPECIALTY_NAME, 'Active' AS STATUS FROM dual) s
ON (t.SPECIALTY_ID = s.SPECIALTY_ID)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_ID, SPECIALTY_NAME, STATUS)
  VALUES (s.SPECIALTY_ID, s.SPECIALTY_NAME, s.STATUS);
MERGE INTO doctor_specialties t
USING (SELECT 4 AS SPECIALTY_ID, 'General Practitioner' AS SPECIALTY_NAME, 'Active' AS STATUS FROM dual) s
ON (t.SPECIALTY_ID = s.SPECIALTY_ID)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_ID, SPECIALTY_NAME, STATUS)
  VALUES (s.SPECIALTY_ID, s.SPECIALTY_NAME, s.STATUS);
MERGE INTO doctor_specialties t
USING (SELECT 5 AS SPECIALTY_ID, 'Emergency Physician' AS SPECIALTY_NAME, 'Active' AS STATUS FROM dual) s
ON (t.SPECIALTY_ID = s.SPECIALTY_ID)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_ID, SPECIALTY_NAME, STATUS)
  VALUES (s.SPECIALTY_ID, s.SPECIALTY_NAME, s.STATUS);

-- ============================================================
-- Table: medicine_categories
-- ============================================================
MERGE INTO medicine_categories t
USING (SELECT 1 AS CATEGORY_ID, 'Antibiotic' AS CATEGORY_NAME, 'Active' AS STATUS FROM dual) s
ON (t.CATEGORY_ID = s.CATEGORY_ID)
WHEN NOT MATCHED THEN INSERT (CATEGORY_ID, CATEGORY_NAME, STATUS)
  VALUES (s.CATEGORY_ID, s.CATEGORY_NAME, s.STATUS);
MERGE INTO medicine_categories t
USING (SELECT 2 AS CATEGORY_ID, 'Painkiller' AS CATEGORY_NAME, 'Active' AS STATUS FROM dual) s
ON (t.CATEGORY_ID = s.CATEGORY_ID)
WHEN NOT MATCHED THEN INSERT (CATEGORY_ID, CATEGORY_NAME, STATUS)
  VALUES (s.CATEGORY_ID, s.CATEGORY_NAME, s.STATUS);
MERGE INTO medicine_categories t
USING (SELECT 3 AS CATEGORY_ID, 'Diabetes' AS CATEGORY_NAME, 'Active' AS STATUS FROM dual) s
ON (t.CATEGORY_ID = s.CATEGORY_ID)
WHEN NOT MATCHED THEN INSERT (CATEGORY_ID, CATEGORY_NAME, STATUS)
  VALUES (s.CATEGORY_ID, s.CATEGORY_NAME, s.STATUS);
MERGE INTO medicine_categories t
USING (SELECT 4 AS CATEGORY_ID, 'Antihistamine' AS CATEGORY_NAME, 'Active' AS STATUS FROM dual) s
ON (t.CATEGORY_ID = s.CATEGORY_ID)
WHEN NOT MATCHED THEN INSERT (CATEGORY_ID, CATEGORY_NAME, STATUS)
  VALUES (s.CATEGORY_ID, s.CATEGORY_NAME, s.STATUS);
MERGE INTO medicine_categories t
USING (SELECT 5 AS CATEGORY_ID, 'Vitamin' AS CATEGORY_NAME, 'Active' AS STATUS FROM dual) s
ON (t.CATEGORY_ID = s.CATEGORY_ID)
WHEN NOT MATCHED THEN INSERT (CATEGORY_ID, CATEGORY_NAME, STATUS)
  VALUES (s.CATEGORY_ID, s.CATEGORY_NAME, s.STATUS);

-- ============================================================
-- Table: appointment_statuses
-- ============================================================
MERGE INTO appointment_statuses t
USING (SELECT 1 AS STATUS_ID, 'Scheduled' AS STATUS_NAME FROM dual) s
ON (t.STATUS_ID = s.STATUS_ID)
WHEN NOT MATCHED THEN INSERT (STATUS_ID, STATUS_NAME)
  VALUES (s.STATUS_ID, s.STATUS_NAME);
MERGE INTO appointment_statuses t
USING (SELECT 2 AS STATUS_ID, 'Completed' AS STATUS_NAME FROM dual) s
ON (t.STATUS_ID = s.STATUS_ID)
WHEN NOT MATCHED THEN INSERT (STATUS_ID, STATUS_NAME)
  VALUES (s.STATUS_ID, s.STATUS_NAME);
MERGE INTO appointment_statuses t
USING (SELECT 3 AS STATUS_ID, 'Cancelled' AS STATUS_NAME FROM dual) s
ON (t.STATUS_ID = s.STATUS_ID)
WHEN NOT MATCHED THEN INSERT (STATUS_ID, STATUS_NAME)
  VALUES (s.STATUS_ID, s.STATUS_NAME);
MERGE INTO appointment_statuses t
USING (SELECT 4 AS STATUS_ID, 'No Show' AS STATUS_NAME FROM dual) s
ON (t.STATUS_ID = s.STATUS_ID)
WHEN NOT MATCHED THEN INSERT (STATUS_ID, STATUS_NAME)
  VALUES (s.STATUS_ID, s.STATUS_NAME);

-- ============================================================
-- Table: doctors
-- ============================================================
MERGE INTO doctors t
USING (SELECT 1 AS DOCTOR_ID, 'Dr. Ahmed Al-Balushi' AS FULL_NAME, 1 AS DEPARTMENT_ID, 1 AS SPECIALTY_ID, '93530829' AS MOBILE_NO, 'ahmedalbalushi@alnoor.om' AS EMAIL, 15 AS CONSULTATION_FEE, 'Active' AS STATUS FROM dual) s
ON (t.DOCTOR_ID = s.DOCTOR_ID)
WHEN NOT MATCHED THEN INSERT (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS)
  VALUES (s.DOCTOR_ID, s.FULL_NAME, s.DEPARTMENT_ID, s.SPECIALTY_ID, s.MOBILE_NO, s.EMAIL, s.CONSULTATION_FEE, s.STATUS);
MERGE INTO doctors t
USING (SELECT 2 AS DOCTOR_ID, 'Dr. Mariam Al-Farsi' AS FULL_NAME, 2 AS DEPARTMENT_ID, 2 AS SPECIALTY_ID, '91810111' AS MOBILE_NO, 'mariamalfarsi@alnoor.om' AS EMAIL, 18 AS CONSULTATION_FEE, 'Active' AS STATUS FROM dual) s
ON (t.DOCTOR_ID = s.DOCTOR_ID)
WHEN NOT MATCHED THEN INSERT (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS)
  VALUES (s.DOCTOR_ID, s.FULL_NAME, s.DEPARTMENT_ID, s.SPECIALTY_ID, s.MOBILE_NO, s.EMAIL, s.CONSULTATION_FEE, s.STATUS);
MERGE INTO doctors t
USING (SELECT 3 AS DOCTOR_ID, 'Dr. Salim Al-Kindi' AS FULL_NAME, 3 AS DEPARTMENT_ID, 3 AS SPECIALTY_ID, '99990608' AS MOBILE_NO, 'salimalkindi@alnoor.om' AS EMAIL, 10 AS CONSULTATION_FEE, 'Active' AS STATUS FROM dual) s
ON (t.DOCTOR_ID = s.DOCTOR_ID)
WHEN NOT MATCHED THEN INSERT (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS)
  VALUES (s.DOCTOR_ID, s.FULL_NAME, s.DEPARTMENT_ID, s.SPECIALTY_ID, s.MOBILE_NO, s.EMAIL, s.CONSULTATION_FEE, s.STATUS);
MERGE INTO doctors t
USING (SELECT 4 AS DOCTOR_ID, 'Dr. Layla Al-Hinai' AS FULL_NAME, 4 AS DEPARTMENT_ID, 4 AS SPECIALTY_ID, '97135241' AS MOBILE_NO, 'laylaalhinai@alnoor.om' AS EMAIL, 10 AS CONSULTATION_FEE, 'Active' AS STATUS FROM dual) s
ON (t.DOCTOR_ID = s.DOCTOR_ID)
WHEN NOT MATCHED THEN INSERT (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS)
  VALUES (s.DOCTOR_ID, s.FULL_NAME, s.DEPARTMENT_ID, s.SPECIALTY_ID, s.MOBILE_NO, s.EMAIL, s.CONSULTATION_FEE, s.STATUS);
MERGE INTO doctors t
USING (SELECT 5 AS DOCTOR_ID, 'Dr. Khalid Al-Saidi' AS FULL_NAME, 5 AS DEPARTMENT_ID, 5 AS SPECIALTY_ID, '91973060' AS MOBILE_NO, 'khalidalsaidi@alnoor.om' AS EMAIL, 20 AS CONSULTATION_FEE, 'Active' AS STATUS FROM dual) s
ON (t.DOCTOR_ID = s.DOCTOR_ID)
WHEN NOT MATCHED THEN INSERT (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS)
  VALUES (s.DOCTOR_ID, s.FULL_NAME, s.DEPARTMENT_ID, s.SPECIALTY_ID, s.MOBILE_NO, s.EMAIL, s.CONSULTATION_FEE, s.STATUS);
MERGE INTO doctors t
USING (SELECT 6 AS DOCTOR_ID, 'Dr. Noura Al-Riyami' AS FULL_NAME, 1 AS DEPARTMENT_ID, 1 AS SPECIALTY_ID, '94602037' AS MOBILE_NO, 'nouraalriyami@alnoor.om' AS EMAIL, 20 AS CONSULTATION_FEE, 'Active' AS STATUS FROM dual) s
ON (t.DOCTOR_ID = s.DOCTOR_ID)
WHEN NOT MATCHED THEN INSERT (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS)
  VALUES (s.DOCTOR_ID, s.FULL_NAME, s.DEPARTMENT_ID, s.SPECIALTY_ID, s.MOBILE_NO, s.EMAIL, s.CONSULTATION_FEE, s.STATUS);
MERGE INTO doctors t
USING (SELECT 7 AS DOCTOR_ID, 'Dr. Faisal Al-Amri' AS FULL_NAME, 2 AS DEPARTMENT_ID, 2 AS SPECIALTY_ID, '92441955' AS MOBILE_NO, 'faisalalamri@alnoor.om' AS EMAIL, 10 AS CONSULTATION_FEE, 'Active' AS STATUS FROM dual) s
ON (t.DOCTOR_ID = s.DOCTOR_ID)
WHEN NOT MATCHED THEN INSERT (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS)
  VALUES (s.DOCTOR_ID, s.FULL_NAME, s.DEPARTMENT_ID, s.SPECIALTY_ID, s.MOBILE_NO, s.EMAIL, s.CONSULTATION_FEE, s.STATUS);
MERGE INTO doctors t
USING (SELECT 8 AS DOCTOR_ID, 'Dr. Huda Al-Zadjali' AS FULL_NAME, 3 AS DEPARTMENT_ID, 3 AS SPECIALTY_ID, '98015764' AS MOBILE_NO, 'hudaalzadjali@alnoor.om' AS EMAIL, 18 AS CONSULTATION_FEE, 'Active' AS STATUS FROM dual) s
ON (t.DOCTOR_ID = s.DOCTOR_ID)
WHEN NOT MATCHED THEN INSERT (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS)
  VALUES (s.DOCTOR_ID, s.FULL_NAME, s.DEPARTMENT_ID, s.SPECIALTY_ID, s.MOBILE_NO, s.EMAIL, s.CONSULTATION_FEE, s.STATUS);
MERGE INTO doctors t
USING (SELECT 9 AS DOCTOR_ID, 'Dr. Yousuf Al-Busaidi' AS FULL_NAME, 4 AS DEPARTMENT_ID, 4 AS SPECIALTY_ID, '95037655' AS MOBILE_NO, 'yousufalbusaidi@alnoor.om' AS EMAIL, 10 AS CONSULTATION_FEE, 'Active' AS STATUS FROM dual) s
ON (t.DOCTOR_ID = s.DOCTOR_ID)
WHEN NOT MATCHED THEN INSERT (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS)
  VALUES (s.DOCTOR_ID, s.FULL_NAME, s.DEPARTMENT_ID, s.SPECIALTY_ID, s.MOBILE_NO, s.EMAIL, s.CONSULTATION_FEE, s.STATUS);
MERGE INTO doctors t
USING (SELECT 23 AS DOCTOR_ID, 'Dr. Ahmed Al-Balushi' AS FULL_NAME, 5 AS DEPARTMENT_ID, 5 AS SPECIALTY_ID, '99123456' AS MOBILE_NO, 'ahmed.test@example.com' AS EMAIL, 30 AS CONSULTATION_FEE, 'Active' AS STATUS FROM dual) s
ON (t.DOCTOR_ID = s.DOCTOR_ID)
WHEN NOT MATCHED THEN INSERT (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS)
  VALUES (s.DOCTOR_ID, s.FULL_NAME, s.DEPARTMENT_ID, s.SPECIALTY_ID, s.MOBILE_NO, s.EMAIL, s.CONSULTATION_FEE, s.STATUS);

-- ============================================================
-- Table: patients
-- ============================================================
MERGE INTO patients t
USING (SELECT 21 AS PATIENT_ID, NULL AS EMAIL, NULL AS BLOOD_GROUP, NULL AS ADDRESS, NULL AS EMERGENCY_CONTACT_NAME, NULL AS EMERGENCY_CONTACT_NO, NULL AS CREATED_AT, '20000021' AS CIVIL_ID, 'Test Patient' AS FULL_NAME, 'Male' AS GENDER, NULL AS DATE_OF_BIRTH, '91234567' AS MOBILE_NO FROM dual) s
ON (t.PATIENT_ID = s.PATIENT_ID)
WHEN NOT MATCHED THEN INSERT (PATIENT_ID, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO)
  VALUES (s.PATIENT_ID, s.EMAIL, s.BLOOD_GROUP, s.ADDRESS, s.EMERGENCY_CONTACT_NAME, s.EMERGENCY_CONTACT_NO, s.CREATED_AT, s.CIVIL_ID, s.FULL_NAME, s.GENDER, s.DATE_OF_BIRTH, s.MOBILE_NO);
MERGE INTO patients t
USING (SELECT 1 AS PATIENT_ID, 'yousuf.amri@email.com' AS EMAIL, 'A+' AS BLOOD_GROUP, 'Muttrah, Muscat' AS ADDRESS, 'Hamed Al-Amri' AS EMERGENCY_CONTACT_NAME, '94709137' AS EMERGENCY_CONTACT_NO, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT, '20000001' AS CIVIL_ID, 'Yousuf Al-Amri' AS FULL_NAME, 'Male' AS GENDER, TO_DATE('1962-10-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DATE_OF_BIRTH, '94745328' AS MOBILE_NO FROM dual) s
ON (t.PATIENT_ID = s.PATIENT_ID)
WHEN NOT MATCHED THEN INSERT (PATIENT_ID, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO)
  VALUES (s.PATIENT_ID, s.EMAIL, s.BLOOD_GROUP, s.ADDRESS, s.EMERGENCY_CONTACT_NAME, s.EMERGENCY_CONTACT_NO, s.CREATED_AT, s.CIVIL_ID, s.FULL_NAME, s.GENDER, s.DATE_OF_BIRTH, s.MOBILE_NO);
MERGE INTO patients t
USING (SELECT 2 AS PATIENT_ID, 'noor.zadjali@email.com' AS EMAIL, 'O+' AS BLOOD_GROUP, 'Muttrah, Muscat' AS ADDRESS, 'Ahmed Al-Zadjali' AS EMERGENCY_CONTACT_NAME, '92976225' AS EMERGENCY_CONTACT_NO, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT, '20000002' AS CIVIL_ID, 'Noor Al-Zadjali' AS FULL_NAME, 'Female' AS GENDER, TO_DATE('1960-09-28 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DATE_OF_BIRTH, '93234302' AS MOBILE_NO FROM dual) s
ON (t.PATIENT_ID = s.PATIENT_ID)
WHEN NOT MATCHED THEN INSERT (PATIENT_ID, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO)
  VALUES (s.PATIENT_ID, s.EMAIL, s.BLOOD_GROUP, s.ADDRESS, s.EMERGENCY_CONTACT_NAME, s.EMERGENCY_CONTACT_NO, s.CREATED_AT, s.CIVIL_ID, s.FULL_NAME, s.GENDER, s.DATE_OF_BIRTH, s.MOBILE_NO);
MERGE INTO patients t
USING (SELECT 3 AS PATIENT_ID, 'khalid.busaidi@email.com' AS EMAIL, 'A-' AS BLOOD_GROUP, 'Seeb, Muscat' AS ADDRESS, 'Noor Al-Busaidi' AS EMERGENCY_CONTACT_NAME, '92634613' AS EMERGENCY_CONTACT_NO, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT, '20000003' AS CIVIL_ID, 'Khalid Al-Busaidi' AS FULL_NAME, 'Male' AS GENDER, TO_DATE('1994-09-27 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DATE_OF_BIRTH, '94032085' AS MOBILE_NO FROM dual) s
ON (t.PATIENT_ID = s.PATIENT_ID)
WHEN NOT MATCHED THEN INSERT (PATIENT_ID, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO)
  VALUES (s.PATIENT_ID, s.EMAIL, s.BLOOD_GROUP, s.ADDRESS, s.EMERGENCY_CONTACT_NAME, s.EMERGENCY_CONTACT_NO, s.CREATED_AT, s.CIVIL_ID, s.FULL_NAME, s.GENDER, s.DATE_OF_BIRTH, s.MOBILE_NO);
MERGE INTO patients t
USING (SELECT 4 AS PATIENT_ID, 'mariam.habsi@email.com' AS EMAIL, 'AB-' AS BLOOD_GROUP, 'Muttrah, Muscat' AS ADDRESS, 'Fatima Al-Habsi' AS EMERGENCY_CONTACT_NAME, '98811503' AS EMERGENCY_CONTACT_NO, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT, '20000004' AS CIVIL_ID, 'Mariam Al-Habsi' AS FULL_NAME, 'Female' AS GENDER, TO_DATE('1963-10-02 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DATE_OF_BIRTH, '94455413' AS MOBILE_NO FROM dual) s
ON (t.PATIENT_ID = s.PATIENT_ID)
WHEN NOT MATCHED THEN INSERT (PATIENT_ID, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO)
  VALUES (s.PATIENT_ID, s.EMAIL, s.BLOOD_GROUP, s.ADDRESS, s.EMERGENCY_CONTACT_NAME, s.EMERGENCY_CONTACT_NO, s.CREATED_AT, s.CIVIL_ID, s.FULL_NAME, s.GENDER, s.DATE_OF_BIRTH, s.MOBILE_NO);
MERGE INTO patients t
USING (SELECT 5 AS PATIENT_ID, 'ahmed.balushi@email.com' AS EMAIL, 'B+' AS BLOOD_GROUP, 'Seeb, Muscat' AS ADDRESS, 'Khalid Al-Balushi' AS EMERGENCY_CONTACT_NAME, '96037344' AS EMERGENCY_CONTACT_NO, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT, '20000005' AS CIVIL_ID, 'Ahmed Al-Balushi' AS FULL_NAME, 'Male' AS GENDER, TO_DATE('2013-06-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DATE_OF_BIRTH, '95167906' AS MOBILE_NO FROM dual) s
ON (t.PATIENT_ID = s.PATIENT_ID)
WHEN NOT MATCHED THEN INSERT (PATIENT_ID, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO)
  VALUES (s.PATIENT_ID, s.EMAIL, s.BLOOD_GROUP, s.ADDRESS, s.EMERGENCY_CONTACT_NAME, s.EMERGENCY_CONTACT_NO, s.CREATED_AT, s.CIVIL_ID, s.FULL_NAME, s.GENDER, s.DATE_OF_BIRTH, s.MOBILE_NO);
MERGE INTO patients t
USING (SELECT 6 AS PATIENT_ID, 'layla.farsi@email.com' AS EMAIL, 'O+' AS BLOOD_GROUP, 'Ruwi, Muscat' AS ADDRESS, 'Salim Al-Farsi' AS EMERGENCY_CONTACT_NAME, '99588807' AS EMERGENCY_CONTACT_NO, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT, '20000006' AS CIVIL_ID, 'Layla Al-Farsi' AS FULL_NAME, 'Female' AS GENDER, TO_DATE('2018-06-24 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DATE_OF_BIRTH, '98530188' AS MOBILE_NO FROM dual) s
ON (t.PATIENT_ID = s.PATIENT_ID)
WHEN NOT MATCHED THEN INSERT (PATIENT_ID, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO)
  VALUES (s.PATIENT_ID, s.EMAIL, s.BLOOD_GROUP, s.ADDRESS, s.EMERGENCY_CONTACT_NAME, s.EMERGENCY_CONTACT_NO, s.CREATED_AT, s.CIVIL_ID, s.FULL_NAME, s.GENDER, s.DATE_OF_BIRTH, s.MOBILE_NO);
MERGE INTO patients t
USING (SELECT 7 AS PATIENT_ID, 'nasser.kindi@email.com' AS EMAIL, 'B+' AS BLOOD_GROUP, 'Al Ansab, Muscat' AS ADDRESS, 'Mariam Al-Kindi' AS EMERGENCY_CONTACT_NAME, '91657788' AS EMERGENCY_CONTACT_NO, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT, '20000007' AS CIVIL_ID, 'Nasser Al-Kindi' AS FULL_NAME, 'Male' AS GENDER, TO_DATE('2008-03-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DATE_OF_BIRTH, '96738744' AS MOBILE_NO FROM dual) s
ON (t.PATIENT_ID = s.PATIENT_ID)
WHEN NOT MATCHED THEN INSERT (PATIENT_ID, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO)
  VALUES (s.PATIENT_ID, s.EMAIL, s.BLOOD_GROUP, s.ADDRESS, s.EMERGENCY_CONTACT_NAME, s.EMERGENCY_CONTACT_NO, s.CREATED_AT, s.CIVIL_ID, s.FULL_NAME, s.GENDER, s.DATE_OF_BIRTH, s.MOBILE_NO);
MERGE INTO patients t
USING (SELECT 8 AS PATIENT_ID, 'zahra.hinai@email.com' AS EMAIL, 'O-' AS BLOOD_GROUP, 'Al Amerat, Muscat' AS ADDRESS, 'Reem Al-Hinai' AS EMERGENCY_CONTACT_NAME, '99332820' AS EMERGENCY_CONTACT_NO, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT, '20000008' AS CIVIL_ID, 'Zahra Al-Hinai' AS FULL_NAME, 'Female' AS GENDER, TO_DATE('1964-09-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DATE_OF_BIRTH, '96263809' AS MOBILE_NO FROM dual) s
ON (t.PATIENT_ID = s.PATIENT_ID)
WHEN NOT MATCHED THEN INSERT (PATIENT_ID, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO)
  VALUES (s.PATIENT_ID, s.EMAIL, s.BLOOD_GROUP, s.ADDRESS, s.EMERGENCY_CONTACT_NAME, s.EMERGENCY_CONTACT_NO, s.CREATED_AT, s.CIVIL_ID, s.FULL_NAME, s.GENDER, s.DATE_OF_BIRTH, s.MOBILE_NO);
MERGE INTO patients t
USING (SELECT 9 AS PATIENT_ID, 'talal.saidi@email.com' AS EMAIL, 'O+' AS BLOOD_GROUP, 'Al Ansab, Muscat' AS ADDRESS, 'Khalid Al-Saidi' AS EMERGENCY_CONTACT_NAME, '92017864' AS EMERGENCY_CONTACT_NO, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT, '20000009' AS CIVIL_ID, 'Talal Al-Saidi' AS FULL_NAME, 'Male' AS GENDER, TO_DATE('2013-02-27 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DATE_OF_BIRTH, '92570280' AS MOBILE_NO FROM dual) s
ON (t.PATIENT_ID = s.PATIENT_ID)
WHEN NOT MATCHED THEN INSERT (PATIENT_ID, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO)
  VALUES (s.PATIENT_ID, s.EMAIL, s.BLOOD_GROUP, s.ADDRESS, s.EMERGENCY_CONTACT_NAME, s.EMERGENCY_CONTACT_NO, s.CREATED_AT, s.CIVIL_ID, s.FULL_NAME, s.GENDER, s.DATE_OF_BIRTH, s.MOBILE_NO);
MERGE INTO patients t
USING (SELECT 10 AS PATIENT_ID, 'reem.riyami@email.com' AS EMAIL, 'O+' AS BLOOD_GROUP, 'Muttrah, Muscat' AS ADDRESS, 'Noor Al-Riyami' AS EMERGENCY_CONTACT_NAME, '91378543' AS EMERGENCY_CONTACT_NO, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT, '20000010' AS CIVIL_ID, 'Reem Al-Riyami' AS FULL_NAME, 'Female' AS GENDER, TO_DATE('1994-11-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DATE_OF_BIRTH, '98476611' AS MOBILE_NO FROM dual) s
ON (t.PATIENT_ID = s.PATIENT_ID)
WHEN NOT MATCHED THEN INSERT (PATIENT_ID, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO)
  VALUES (s.PATIENT_ID, s.EMAIL, s.BLOOD_GROUP, s.ADDRESS, s.EMERGENCY_CONTACT_NAME, s.EMERGENCY_CONTACT_NO, s.CREATED_AT, s.CIVIL_ID, s.FULL_NAME, s.GENDER, s.DATE_OF_BIRTH, s.MOBILE_NO);
MERGE INTO patients t
USING (SELECT 11 AS PATIENT_ID, 'yousuf.amri@email.com' AS EMAIL, 'AB-' AS BLOOD_GROUP, 'Al Khuwair, Muscat' AS ADDRESS, 'Nasser Al-Amri' AS EMERGENCY_CONTACT_NAME, '95822307' AS EMERGENCY_CONTACT_NO, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT, '20000011' AS CIVIL_ID, 'Yousuf Al-Amri' AS FULL_NAME, 'Male' AS GENDER, TO_DATE('2014-06-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DATE_OF_BIRTH, '92964541' AS MOBILE_NO FROM dual) s
ON (t.PATIENT_ID = s.PATIENT_ID)
WHEN NOT MATCHED THEN INSERT (PATIENT_ID, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO)
  VALUES (s.PATIENT_ID, s.EMAIL, s.BLOOD_GROUP, s.ADDRESS, s.EMERGENCY_CONTACT_NAME, s.EMERGENCY_CONTACT_NO, s.CREATED_AT, s.CIVIL_ID, s.FULL_NAME, s.GENDER, s.DATE_OF_BIRTH, s.MOBILE_NO);
MERGE INTO patients t
USING (SELECT 12 AS PATIENT_ID, 'noor.zadjali@email.com' AS EMAIL, 'AB+' AS BLOOD_GROUP, 'Al Ansab, Muscat' AS ADDRESS, 'Khalid Al-Zadjali' AS EMERGENCY_CONTACT_NAME, '93791163' AS EMERGENCY_CONTACT_NO, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT, '20000012' AS CIVIL_ID, 'Noor Al-Zadjali' AS FULL_NAME, 'Female' AS GENDER, TO_DATE('1971-12-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DATE_OF_BIRTH, '97675615' AS MOBILE_NO FROM dual) s
ON (t.PATIENT_ID = s.PATIENT_ID)
WHEN NOT MATCHED THEN INSERT (PATIENT_ID, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO)
  VALUES (s.PATIENT_ID, s.EMAIL, s.BLOOD_GROUP, s.ADDRESS, s.EMERGENCY_CONTACT_NAME, s.EMERGENCY_CONTACT_NO, s.CREATED_AT, s.CIVIL_ID, s.FULL_NAME, s.GENDER, s.DATE_OF_BIRTH, s.MOBILE_NO);
MERGE INTO patients t
USING (SELECT 13 AS PATIENT_ID, 'khalid.busaidi@email.com' AS EMAIL, 'B+' AS BLOOD_GROUP, 'Muttrah, Muscat' AS ADDRESS, 'Zahra Al-Busaidi' AS EMERGENCY_CONTACT_NAME, '95671130' AS EMERGENCY_CONTACT_NO, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT, '20000013' AS CIVIL_ID, 'Khalid Al-Busaidi' AS FULL_NAME, 'Male' AS GENDER, TO_DATE('2012-07-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DATE_OF_BIRTH, '95661367' AS MOBILE_NO FROM dual) s
ON (t.PATIENT_ID = s.PATIENT_ID)
WHEN NOT MATCHED THEN INSERT (PATIENT_ID, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO)
  VALUES (s.PATIENT_ID, s.EMAIL, s.BLOOD_GROUP, s.ADDRESS, s.EMERGENCY_CONTACT_NAME, s.EMERGENCY_CONTACT_NO, s.CREATED_AT, s.CIVIL_ID, s.FULL_NAME, s.GENDER, s.DATE_OF_BIRTH, s.MOBILE_NO);
MERGE INTO patients t
USING (SELECT 14 AS PATIENT_ID, 'mariam.habsi@email.com' AS EMAIL, 'B-' AS BLOOD_GROUP, 'Bausher, Muscat' AS ADDRESS, 'Khalid Al-Habsi' AS EMERGENCY_CONTACT_NAME, '93956442' AS EMERGENCY_CONTACT_NO, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT, '20000014' AS CIVIL_ID, 'Mariam Al-Habsi' AS FULL_NAME, 'Female' AS GENDER, TO_DATE('2008-06-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DATE_OF_BIRTH, '97382745' AS MOBILE_NO FROM dual) s
ON (t.PATIENT_ID = s.PATIENT_ID)
WHEN NOT MATCHED THEN INSERT (PATIENT_ID, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO)
  VALUES (s.PATIENT_ID, s.EMAIL, s.BLOOD_GROUP, s.ADDRESS, s.EMERGENCY_CONTACT_NAME, s.EMERGENCY_CONTACT_NO, s.CREATED_AT, s.CIVIL_ID, s.FULL_NAME, s.GENDER, s.DATE_OF_BIRTH, s.MOBILE_NO);
MERGE INTO patients t
USING (SELECT 15 AS PATIENT_ID, 'ahmed.balushi@email.com' AS EMAIL, 'A+' AS BLOOD_GROUP, 'Al Ansab, Muscat' AS ADDRESS, 'Amal Al-Balushi' AS EMERGENCY_CONTACT_NAME, '94059205' AS EMERGENCY_CONTACT_NO, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT, '20000015' AS CIVIL_ID, 'Ahmed Al-Balushi' AS FULL_NAME, 'Male' AS GENDER, TO_DATE('1974-04-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DATE_OF_BIRTH, '94914729' AS MOBILE_NO FROM dual) s
ON (t.PATIENT_ID = s.PATIENT_ID)
WHEN NOT MATCHED THEN INSERT (PATIENT_ID, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO)
  VALUES (s.PATIENT_ID, s.EMAIL, s.BLOOD_GROUP, s.ADDRESS, s.EMERGENCY_CONTACT_NAME, s.EMERGENCY_CONTACT_NO, s.CREATED_AT, s.CIVIL_ID, s.FULL_NAME, s.GENDER, s.DATE_OF_BIRTH, s.MOBILE_NO);
MERGE INTO patients t
USING (SELECT 16 AS PATIENT_ID, 'layla.farsi@email.com' AS EMAIL, 'AB+' AS BLOOD_GROUP, 'Al Amerat, Muscat' AS ADDRESS, 'Reem Al-Farsi' AS EMERGENCY_CONTACT_NAME, '96345416' AS EMERGENCY_CONTACT_NO, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT, '20000016' AS CIVIL_ID, 'Layla Al-Farsi' AS FULL_NAME, 'Female' AS GENDER, TO_DATE('1988-05-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DATE_OF_BIRTH, '93444044' AS MOBILE_NO FROM dual) s
ON (t.PATIENT_ID = s.PATIENT_ID)
WHEN NOT MATCHED THEN INSERT (PATIENT_ID, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO)
  VALUES (s.PATIENT_ID, s.EMAIL, s.BLOOD_GROUP, s.ADDRESS, s.EMERGENCY_CONTACT_NAME, s.EMERGENCY_CONTACT_NO, s.CREATED_AT, s.CIVIL_ID, s.FULL_NAME, s.GENDER, s.DATE_OF_BIRTH, s.MOBILE_NO);
MERGE INTO patients t
USING (SELECT 17 AS PATIENT_ID, 'nasser.kindi@email.com' AS EMAIL, 'A+' AS BLOOD_GROUP, 'Al Ansab, Muscat' AS ADDRESS, 'Zahra Al-Kindi' AS EMERGENCY_CONTACT_NAME, '97583025' AS EMERGENCY_CONTACT_NO, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT, '20000017' AS CIVIL_ID, 'Nasser Al-Kindi' AS FULL_NAME, 'Male' AS GENDER, TO_DATE('1971-12-28 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DATE_OF_BIRTH, '99648511' AS MOBILE_NO FROM dual) s
ON (t.PATIENT_ID = s.PATIENT_ID)
WHEN NOT MATCHED THEN INSERT (PATIENT_ID, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO)
  VALUES (s.PATIENT_ID, s.EMAIL, s.BLOOD_GROUP, s.ADDRESS, s.EMERGENCY_CONTACT_NAME, s.EMERGENCY_CONTACT_NO, s.CREATED_AT, s.CIVIL_ID, s.FULL_NAME, s.GENDER, s.DATE_OF_BIRTH, s.MOBILE_NO);
MERGE INTO patients t
USING (SELECT 18 AS PATIENT_ID, 'zahra.hinai@email.com' AS EMAIL, 'AB-' AS BLOOD_GROUP, 'Muttrah, Muscat' AS ADDRESS, 'Hamed Al-Hinai' AS EMERGENCY_CONTACT_NAME, '94197897' AS EMERGENCY_CONTACT_NO, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT, '20000018' AS CIVIL_ID, 'Zahra Al-Hinai' AS FULL_NAME, 'Female' AS GENDER, TO_DATE('2005-07-13 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DATE_OF_BIRTH, '92737064' AS MOBILE_NO FROM dual) s
ON (t.PATIENT_ID = s.PATIENT_ID)
WHEN NOT MATCHED THEN INSERT (PATIENT_ID, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO)
  VALUES (s.PATIENT_ID, s.EMAIL, s.BLOOD_GROUP, s.ADDRESS, s.EMERGENCY_CONTACT_NAME, s.EMERGENCY_CONTACT_NO, s.CREATED_AT, s.CIVIL_ID, s.FULL_NAME, s.GENDER, s.DATE_OF_BIRTH, s.MOBILE_NO);
MERGE INTO patients t
USING (SELECT 19 AS PATIENT_ID, 'talal.saidi@email.com' AS EMAIL, 'A-' AS BLOOD_GROUP, 'Al Amerat, Muscat' AS ADDRESS, 'Reem Al-Saidi' AS EMERGENCY_CONTACT_NAME, '91882072' AS EMERGENCY_CONTACT_NO, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT, '20000019' AS CIVIL_ID, 'Talal Al-Saidi' AS FULL_NAME, 'Male' AS GENDER, TO_DATE('1963-04-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DATE_OF_BIRTH, '93722995' AS MOBILE_NO FROM dual) s
ON (t.PATIENT_ID = s.PATIENT_ID)
WHEN NOT MATCHED THEN INSERT (PATIENT_ID, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO)
  VALUES (s.PATIENT_ID, s.EMAIL, s.BLOOD_GROUP, s.ADDRESS, s.EMERGENCY_CONTACT_NAME, s.EMERGENCY_CONTACT_NO, s.CREATED_AT, s.CIVIL_ID, s.FULL_NAME, s.GENDER, s.DATE_OF_BIRTH, s.MOBILE_NO);
MERGE INTO patients t
USING (SELECT 20 AS PATIENT_ID, 'reem.riyami@email.com' AS EMAIL, 'A-' AS BLOOD_GROUP, 'Al Amerat, Muscat' AS ADDRESS, 'Reem Al-Riyami' AS EMERGENCY_CONTACT_NAME, '91427833' AS EMERGENCY_CONTACT_NO, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT, '20000020' AS CIVIL_ID, 'Reem Al-Riyami' AS FULL_NAME, 'Female' AS GENDER, TO_DATE('1968-01-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DATE_OF_BIRTH, '93537804' AS MOBILE_NO FROM dual) s
ON (t.PATIENT_ID = s.PATIENT_ID)
WHEN NOT MATCHED THEN INSERT (PATIENT_ID, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO)
  VALUES (s.PATIENT_ID, s.EMAIL, s.BLOOD_GROUP, s.ADDRESS, s.EMERGENCY_CONTACT_NAME, s.EMERGENCY_CONTACT_NO, s.CREATED_AT, s.CIVIL_ID, s.FULL_NAME, s.GENDER, s.DATE_OF_BIRTH, s.MOBILE_NO);

-- ============================================================
-- Table: medicines
-- ============================================================
MERGE INTO medicines t
USING (SELECT 21 AS MEDICINE_ID, 'Test Medicine A' AS MEDICINE_NAME, 2 AS CATEGORY_ID, 'table' AS UNIT, 50 AS CURRENT_STOCK, 20 AS REORDER_LEVEL, 'Active' AS STATUS FROM dual) s
ON (t.MEDICINE_ID = s.MEDICINE_ID)
WHEN NOT MATCHED THEN INSERT (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
  VALUES (s.MEDICINE_ID, s.MEDICINE_NAME, s.CATEGORY_ID, s.UNIT, s.CURRENT_STOCK, s.REORDER_LEVEL, s.STATUS);
MERGE INTO medicines t
USING (SELECT 1 AS MEDICINE_ID, 'Amoxicillin' AS MEDICINE_NAME, 1 AS CATEGORY_ID, 'capsule' AS UNIT, 18 AS CURRENT_STOCK, 33 AS REORDER_LEVEL, 'Active' AS STATUS FROM dual) s
ON (t.MEDICINE_ID = s.MEDICINE_ID)
WHEN NOT MATCHED THEN INSERT (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
  VALUES (s.MEDICINE_ID, s.MEDICINE_NAME, s.CATEGORY_ID, s.UNIT, s.CURRENT_STOCK, s.REORDER_LEVEL, s.STATUS);
MERGE INTO medicines t
USING (SELECT 2 AS MEDICINE_ID, 'Azithromycin' AS MEDICINE_NAME, 1 AS CATEGORY_ID, 'tablet' AS UNIT, 157 AS CURRENT_STOCK, 44 AS REORDER_LEVEL, 'Active' AS STATUS FROM dual) s
ON (t.MEDICINE_ID = s.MEDICINE_ID)
WHEN NOT MATCHED THEN INSERT (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
  VALUES (s.MEDICINE_ID, s.MEDICINE_NAME, s.CATEGORY_ID, s.UNIT, s.CURRENT_STOCK, s.REORDER_LEVEL, s.STATUS);
MERGE INTO medicines t
USING (SELECT 3 AS MEDICINE_ID, 'Ciprofloxacin' AS MEDICINE_NAME, 1 AS CATEGORY_ID, 'tablet' AS UNIT, 38 AS CURRENT_STOCK, 60 AS REORDER_LEVEL, 'Active' AS STATUS FROM dual) s
ON (t.MEDICINE_ID = s.MEDICINE_ID)
WHEN NOT MATCHED THEN INSERT (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
  VALUES (s.MEDICINE_ID, s.MEDICINE_NAME, s.CATEGORY_ID, s.UNIT, s.CURRENT_STOCK, s.REORDER_LEVEL, s.STATUS);
MERGE INTO medicines t
USING (SELECT 4 AS MEDICINE_ID, 'Metronidazole' AS MEDICINE_NAME, 1 AS CATEGORY_ID, 'tablet' AS UNIT, 64 AS CURRENT_STOCK, 42 AS REORDER_LEVEL, 'Active' AS STATUS FROM dual) s
ON (t.MEDICINE_ID = s.MEDICINE_ID)
WHEN NOT MATCHED THEN INSERT (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
  VALUES (s.MEDICINE_ID, s.MEDICINE_NAME, s.CATEGORY_ID, s.UNIT, s.CURRENT_STOCK, s.REORDER_LEVEL, s.STATUS);
MERGE INTO medicines t
USING (SELECT 5 AS MEDICINE_ID, 'Doxycycline' AS MEDICINE_NAME, 1 AS CATEGORY_ID, 'capsule' AS UNIT, 154 AS CURRENT_STOCK, 43 AS REORDER_LEVEL, 'Active' AS STATUS FROM dual) s
ON (t.MEDICINE_ID = s.MEDICINE_ID)
WHEN NOT MATCHED THEN INSERT (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
  VALUES (s.MEDICINE_ID, s.MEDICINE_NAME, s.CATEGORY_ID, s.UNIT, s.CURRENT_STOCK, s.REORDER_LEVEL, s.STATUS);
MERGE INTO medicines t
USING (SELECT 6 AS MEDICINE_ID, 'Paracetamol' AS MEDICINE_NAME, 2 AS CATEGORY_ID, 'tablet' AS UNIT, 121 AS CURRENT_STOCK, 27 AS REORDER_LEVEL, 'Active' AS STATUS FROM dual) s
ON (t.MEDICINE_ID = s.MEDICINE_ID)
WHEN NOT MATCHED THEN INSERT (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
  VALUES (s.MEDICINE_ID, s.MEDICINE_NAME, s.CATEGORY_ID, s.UNIT, s.CURRENT_STOCK, s.REORDER_LEVEL, s.STATUS);
MERGE INTO medicines t
USING (SELECT 7 AS MEDICINE_ID, 'Ibuprofen' AS MEDICINE_NAME, 2 AS CATEGORY_ID, 'tablet' AS UNIT, 29 AS CURRENT_STOCK, 51 AS REORDER_LEVEL, 'Active' AS STATUS FROM dual) s
ON (t.MEDICINE_ID = s.MEDICINE_ID)
WHEN NOT MATCHED THEN INSERT (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
  VALUES (s.MEDICINE_ID, s.MEDICINE_NAME, s.CATEGORY_ID, s.UNIT, s.CURRENT_STOCK, s.REORDER_LEVEL, s.STATUS);
MERGE INTO medicines t
USING (SELECT 8 AS MEDICINE_ID, 'Diclofenac' AS MEDICINE_NAME, 2 AS CATEGORY_ID, 'tablet' AS UNIT, 119 AS CURRENT_STOCK, 50 AS REORDER_LEVEL, 'Active' AS STATUS FROM dual) s
ON (t.MEDICINE_ID = s.MEDICINE_ID)
WHEN NOT MATCHED THEN INSERT (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
  VALUES (s.MEDICINE_ID, s.MEDICINE_NAME, s.CATEGORY_ID, s.UNIT, s.CURRENT_STOCK, s.REORDER_LEVEL, s.STATUS);
MERGE INTO medicines t
USING (SELECT 9 AS MEDICINE_ID, 'Aspirin' AS MEDICINE_NAME, 2 AS CATEGORY_ID, 'tablet' AS UNIT, 123 AS CURRENT_STOCK, 39 AS REORDER_LEVEL, 'Active' AS STATUS FROM dual) s
ON (t.MEDICINE_ID = s.MEDICINE_ID)
WHEN NOT MATCHED THEN INSERT (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
  VALUES (s.MEDICINE_ID, s.MEDICINE_NAME, s.CATEGORY_ID, s.UNIT, s.CURRENT_STOCK, s.REORDER_LEVEL, s.STATUS);
MERGE INTO medicines t
USING (SELECT 10 AS MEDICINE_ID, 'Naproxen' AS MEDICINE_NAME, 2 AS CATEGORY_ID, 'tablet' AS UNIT, 21 AS CURRENT_STOCK, 29 AS REORDER_LEVEL, 'Active' AS STATUS FROM dual) s
ON (t.MEDICINE_ID = s.MEDICINE_ID)
WHEN NOT MATCHED THEN INSERT (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
  VALUES (s.MEDICINE_ID, s.MEDICINE_NAME, s.CATEGORY_ID, s.UNIT, s.CURRENT_STOCK, s.REORDER_LEVEL, s.STATUS);
MERGE INTO medicines t
USING (SELECT 11 AS MEDICINE_ID, 'Metformin' AS MEDICINE_NAME, 3 AS CATEGORY_ID, 'tablet' AS UNIT, 26 AS CURRENT_STOCK, 41 AS REORDER_LEVEL, 'Active' AS STATUS FROM dual) s
ON (t.MEDICINE_ID = s.MEDICINE_ID)
WHEN NOT MATCHED THEN INSERT (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
  VALUES (s.MEDICINE_ID, s.MEDICINE_NAME, s.CATEGORY_ID, s.UNIT, s.CURRENT_STOCK, s.REORDER_LEVEL, s.STATUS);
MERGE INTO medicines t
USING (SELECT 12 AS MEDICINE_ID, 'Insulin Glargine' AS MEDICINE_NAME, 3 AS CATEGORY_ID, 'injection' AS UNIT, 189 AS CURRENT_STOCK, 36 AS REORDER_LEVEL, 'Active' AS STATUS FROM dual) s
ON (t.MEDICINE_ID = s.MEDICINE_ID)
WHEN NOT MATCHED THEN INSERT (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
  VALUES (s.MEDICINE_ID, s.MEDICINE_NAME, s.CATEGORY_ID, s.UNIT, s.CURRENT_STOCK, s.REORDER_LEVEL, s.STATUS);
MERGE INTO medicines t
USING (SELECT 13 AS MEDICINE_ID, 'Gliclazide' AS MEDICINE_NAME, 3 AS CATEGORY_ID, 'tablet' AS UNIT, 122 AS CURRENT_STOCK, 30 AS REORDER_LEVEL, 'Active' AS STATUS FROM dual) s
ON (t.MEDICINE_ID = s.MEDICINE_ID)
WHEN NOT MATCHED THEN INSERT (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
  VALUES (s.MEDICINE_ID, s.MEDICINE_NAME, s.CATEGORY_ID, s.UNIT, s.CURRENT_STOCK, s.REORDER_LEVEL, s.STATUS);
MERGE INTO medicines t
USING (SELECT 14 AS MEDICINE_ID, 'Glimepiride' AS MEDICINE_NAME, 3 AS CATEGORY_ID, 'tablet' AS UNIT, 132 AS CURRENT_STOCK, 21 AS REORDER_LEVEL, 'Active' AS STATUS FROM dual) s
ON (t.MEDICINE_ID = s.MEDICINE_ID)
WHEN NOT MATCHED THEN INSERT (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
  VALUES (s.MEDICINE_ID, s.MEDICINE_NAME, s.CATEGORY_ID, s.UNIT, s.CURRENT_STOCK, s.REORDER_LEVEL, s.STATUS);
MERGE INTO medicines t
USING (SELECT 15 AS MEDICINE_ID, 'Sitagliptin' AS MEDICINE_NAME, 3 AS CATEGORY_ID, 'tablet' AS UNIT, 52 AS CURRENT_STOCK, 53 AS REORDER_LEVEL, 'Active' AS STATUS FROM dual) s
ON (t.MEDICINE_ID = s.MEDICINE_ID)
WHEN NOT MATCHED THEN INSERT (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
  VALUES (s.MEDICINE_ID, s.MEDICINE_NAME, s.CATEGORY_ID, s.UNIT, s.CURRENT_STOCK, s.REORDER_LEVEL, s.STATUS);
MERGE INTO medicines t
USING (SELECT 16 AS MEDICINE_ID, 'Cetirizine' AS MEDICINE_NAME, 4 AS CATEGORY_ID, 'tablet' AS UNIT, 92 AS CURRENT_STOCK, 29 AS REORDER_LEVEL, 'Active' AS STATUS FROM dual) s
ON (t.MEDICINE_ID = s.MEDICINE_ID)
WHEN NOT MATCHED THEN INSERT (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
  VALUES (s.MEDICINE_ID, s.MEDICINE_NAME, s.CATEGORY_ID, s.UNIT, s.CURRENT_STOCK, s.REORDER_LEVEL, s.STATUS);
MERGE INTO medicines t
USING (SELECT 17 AS MEDICINE_ID, 'Loratadine' AS MEDICINE_NAME, 4 AS CATEGORY_ID, 'tablet' AS UNIT, 176 AS CURRENT_STOCK, 54 AS REORDER_LEVEL, 'Active' AS STATUS FROM dual) s
ON (t.MEDICINE_ID = s.MEDICINE_ID)
WHEN NOT MATCHED THEN INSERT (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
  VALUES (s.MEDICINE_ID, s.MEDICINE_NAME, s.CATEGORY_ID, s.UNIT, s.CURRENT_STOCK, s.REORDER_LEVEL, s.STATUS);
MERGE INTO medicines t
USING (SELECT 18 AS MEDICINE_ID, 'Chlorpheniramine' AS MEDICINE_NAME, 4 AS CATEGORY_ID, 'syrup' AS UNIT, 6 AS CURRENT_STOCK, 53 AS REORDER_LEVEL, 'Active' AS STATUS FROM dual) s
ON (t.MEDICINE_ID = s.MEDICINE_ID)
WHEN NOT MATCHED THEN INSERT (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
  VALUES (s.MEDICINE_ID, s.MEDICINE_NAME, s.CATEGORY_ID, s.UNIT, s.CURRENT_STOCK, s.REORDER_LEVEL, s.STATUS);
MERGE INTO medicines t
USING (SELECT 19 AS MEDICINE_ID, 'Vitamin C' AS MEDICINE_NAME, 5 AS CATEGORY_ID, 'tablet' AS UNIT, 76 AS CURRENT_STOCK, 25 AS REORDER_LEVEL, 'Active' AS STATUS FROM dual) s
ON (t.MEDICINE_ID = s.MEDICINE_ID)
WHEN NOT MATCHED THEN INSERT (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
  VALUES (s.MEDICINE_ID, s.MEDICINE_NAME, s.CATEGORY_ID, s.UNIT, s.CURRENT_STOCK, s.REORDER_LEVEL, s.STATUS);
MERGE INTO medicines t
USING (SELECT 20 AS MEDICINE_ID, 'Vitamin D3' AS MEDICINE_NAME, 5 AS CATEGORY_ID, 'capsule' AS UNIT, 178 AS CURRENT_STOCK, 36 AS REORDER_LEVEL, 'Active' AS STATUS FROM dual) s
ON (t.MEDICINE_ID = s.MEDICINE_ID)
WHEN NOT MATCHED THEN INSERT (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
  VALUES (s.MEDICINE_ID, s.MEDICINE_NAME, s.CATEGORY_ID, s.UNIT, s.CURRENT_STOCK, s.REORDER_LEVEL, s.STATUS);

-- ============================================================
-- Table: rooms
-- ============================================================
MERGE INTO rooms t
USING (SELECT 1 AS ROOM_ID, 'A-100' AS ROOM_NO, 'General' AS ROOM_TYPE, 15 AS DAILY_RATE, 'Occupied' AS STATUS FROM dual) s
ON (t.ROOM_ID = s.ROOM_ID)
WHEN NOT MATCHED THEN INSERT (ROOM_ID, ROOM_NO, ROOM_TYPE, DAILY_RATE, STATUS)
  VALUES (s.ROOM_ID, s.ROOM_NO, s.ROOM_TYPE, s.DAILY_RATE, s.STATUS);
MERGE INTO rooms t
USING (SELECT 2 AS ROOM_ID, 'A-101' AS ROOM_NO, 'General' AS ROOM_TYPE, 15 AS DAILY_RATE, 'Available' AS STATUS FROM dual) s
ON (t.ROOM_ID = s.ROOM_ID)
WHEN NOT MATCHED THEN INSERT (ROOM_ID, ROOM_NO, ROOM_TYPE, DAILY_RATE, STATUS)
  VALUES (s.ROOM_ID, s.ROOM_NO, s.ROOM_TYPE, s.DAILY_RATE, s.STATUS);
MERGE INTO rooms t
USING (SELECT 3 AS ROOM_ID, 'A-102' AS ROOM_NO, 'General' AS ROOM_TYPE, 15 AS DAILY_RATE, 'Available' AS STATUS FROM dual) s
ON (t.ROOM_ID = s.ROOM_ID)
WHEN NOT MATCHED THEN INSERT (ROOM_ID, ROOM_NO, ROOM_TYPE, DAILY_RATE, STATUS)
  VALUES (s.ROOM_ID, s.ROOM_NO, s.ROOM_TYPE, s.DAILY_RATE, s.STATUS);
MERGE INTO rooms t
USING (SELECT 4 AS ROOM_ID, 'A-103' AS ROOM_NO, 'Private' AS ROOM_TYPE, 30 AS DAILY_RATE, 'Occupied' AS STATUS FROM dual) s
ON (t.ROOM_ID = s.ROOM_ID)
WHEN NOT MATCHED THEN INSERT (ROOM_ID, ROOM_NO, ROOM_TYPE, DAILY_RATE, STATUS)
  VALUES (s.ROOM_ID, s.ROOM_NO, s.ROOM_TYPE, s.DAILY_RATE, s.STATUS);
MERGE INTO rooms t
USING (SELECT 5 AS ROOM_ID, 'A-104' AS ROOM_NO, 'Private' AS ROOM_TYPE, 30 AS DAILY_RATE, 'Occupied' AS STATUS FROM dual) s
ON (t.ROOM_ID = s.ROOM_ID)
WHEN NOT MATCHED THEN INSERT (ROOM_ID, ROOM_NO, ROOM_TYPE, DAILY_RATE, STATUS)
  VALUES (s.ROOM_ID, s.ROOM_NO, s.ROOM_TYPE, s.DAILY_RATE, s.STATUS);
MERGE INTO rooms t
USING (SELECT 6 AS ROOM_ID, 'B-105' AS ROOM_NO, 'Private' AS ROOM_TYPE, 30 AS DAILY_RATE, 'Occupied' AS STATUS FROM dual) s
ON (t.ROOM_ID = s.ROOM_ID)
WHEN NOT MATCHED THEN INSERT (ROOM_ID, ROOM_NO, ROOM_TYPE, DAILY_RATE, STATUS)
  VALUES (s.ROOM_ID, s.ROOM_NO, s.ROOM_TYPE, s.DAILY_RATE, s.STATUS);
MERGE INTO rooms t
USING (SELECT 7 AS ROOM_ID, 'B-106' AS ROOM_NO, 'ICU' AS ROOM_TYPE, 80 AS DAILY_RATE, 'Occupied' AS STATUS FROM dual) s
ON (t.ROOM_ID = s.ROOM_ID)
WHEN NOT MATCHED THEN INSERT (ROOM_ID, ROOM_NO, ROOM_TYPE, DAILY_RATE, STATUS)
  VALUES (s.ROOM_ID, s.ROOM_NO, s.ROOM_TYPE, s.DAILY_RATE, s.STATUS);
MERGE INTO rooms t
USING (SELECT 8 AS ROOM_ID, 'B-107' AS ROOM_NO, 'ICU' AS ROOM_TYPE, 80 AS DAILY_RATE, 'Occupied' AS STATUS FROM dual) s
ON (t.ROOM_ID = s.ROOM_ID)
WHEN NOT MATCHED THEN INSERT (ROOM_ID, ROOM_NO, ROOM_TYPE, DAILY_RATE, STATUS)
  VALUES (s.ROOM_ID, s.ROOM_NO, s.ROOM_TYPE, s.DAILY_RATE, s.STATUS);
MERGE INTO rooms t
USING (SELECT 9 AS ROOM_ID, 'B-108' AS ROOM_NO, 'General' AS ROOM_TYPE, 15 AS DAILY_RATE, 'Available' AS STATUS FROM dual) s
ON (t.ROOM_ID = s.ROOM_ID)
WHEN NOT MATCHED THEN INSERT (ROOM_ID, ROOM_NO, ROOM_TYPE, DAILY_RATE, STATUS)
  VALUES (s.ROOM_ID, s.ROOM_NO, s.ROOM_TYPE, s.DAILY_RATE, s.STATUS);
MERGE INTO rooms t
USING (SELECT 10 AS ROOM_ID, 'B-109' AS ROOM_NO, 'Private' AS ROOM_TYPE, 30 AS DAILY_RATE, 'Available' AS STATUS FROM dual) s
ON (t.ROOM_ID = s.ROOM_ID)
WHEN NOT MATCHED THEN INSERT (ROOM_ID, ROOM_NO, ROOM_TYPE, DAILY_RATE, STATUS)
  VALUES (s.ROOM_ID, s.ROOM_NO, s.ROOM_TYPE, s.DAILY_RATE, s.STATUS);

-- ============================================================
-- Table: appointments
-- ============================================================
MERGE INTO appointments t
USING (SELECT 1 AS APPOINTMENT_ID, 17 AS PATIENT_ID, 6 AS DOCTOR_ID, TO_DATE('2026-07-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '11:30' AS APPOINTMENT_TIME, 2 AS STATUS_ID, 'Back pain' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 2 AS APPOINTMENT_ID, 18 AS PATIENT_ID, 9 AS DOCTOR_ID, TO_DATE('2026-07-13 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '10:30' AS APPOINTMENT_TIME, 1 AS STATUS_ID, 'Fever' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 3 AS APPOINTMENT_ID, 13 AS PATIENT_ID, 4 AS DOCTOR_ID, TO_DATE('2026-07-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '15:00' AS APPOINTMENT_TIME, 3 AS STATUS_ID, 'Vaccination' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 4 AS APPOINTMENT_ID, 1 AS PATIENT_ID, 1 AS DOCTOR_ID, TO_DATE('2026-07-11 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '14:30' AS APPOINTMENT_TIME, 3 AS STATUS_ID, 'Fever' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 5 AS APPOINTMENT_ID, 20 AS PATIENT_ID, 6 AS DOCTOR_ID, TO_DATE('2026-07-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '11:30' AS APPOINTMENT_TIME, 1 AS STATUS_ID, 'Vaccination' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 6 AS APPOINTMENT_ID, 3 AS PATIENT_ID, 4 AS DOCTOR_ID, TO_DATE('2026-07-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '10:30' AS APPOINTMENT_TIME, 3 AS STATUS_ID, 'Fever' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 7 AS APPOINTMENT_ID, 11 AS PATIENT_ID, 4 AS DOCTOR_ID, TO_DATE('2026-07-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '09:00' AS APPOINTMENT_TIME, 1 AS STATUS_ID, 'Headache' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 8 AS APPOINTMENT_ID, 12 AS PATIENT_ID, 2 AS DOCTOR_ID, TO_DATE('2026-07-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '14:00' AS APPOINTMENT_TIME, 4 AS STATUS_ID, 'Fever' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 9 AS APPOINTMENT_ID, 16 AS PATIENT_ID, 3 AS DOCTOR_ID, TO_DATE('2026-07-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '11:30' AS APPOINTMENT_TIME, 1 AS STATUS_ID, 'Follow-up visit' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 10 AS APPOINTMENT_ID, 13 AS PATIENT_ID, 8 AS DOCTOR_ID, TO_DATE('2026-07-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '09:30' AS APPOINTMENT_TIME, 1 AS STATUS_ID, 'Cough and cold' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 11 AS APPOINTMENT_ID, 6 AS PATIENT_ID, 3 AS DOCTOR_ID, TO_DATE('2026-07-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '09:00' AS APPOINTMENT_TIME, 2 AS STATUS_ID, 'Diabetes checkup' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 12 AS APPOINTMENT_ID, 15 AS PATIENT_ID, 3 AS DOCTOR_ID, TO_DATE('2026-07-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '14:30' AS APPOINTMENT_TIME, 1 AS STATUS_ID, 'Skin rash' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 13 AS APPOINTMENT_ID, 12 AS PATIENT_ID, 3 AS DOCTOR_ID, TO_DATE('2026-07-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '15:00' AS APPOINTMENT_TIME, 1 AS STATUS_ID, 'Chest pain' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 14 AS APPOINTMENT_ID, 1 AS PATIENT_ID, 1 AS DOCTOR_ID, TO_DATE('2026-07-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '09:30' AS APPOINTMENT_TIME, 1 AS STATUS_ID, 'Back pain' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 15 AS APPOINTMENT_ID, 5 AS PATIENT_ID, 7 AS DOCTOR_ID, TO_DATE('2026-07-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '10:30' AS APPOINTMENT_TIME, 2 AS STATUS_ID, 'Knee pain' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 16 AS APPOINTMENT_ID, 7 AS PATIENT_ID, 5 AS DOCTOR_ID, TO_DATE('2026-07-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '10:30' AS APPOINTMENT_TIME, 1 AS STATUS_ID, 'Diabetes checkup' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 17 AS APPOINTMENT_ID, 11 AS PATIENT_ID, 5 AS DOCTOR_ID, TO_DATE('2026-07-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '14:00' AS APPOINTMENT_TIME, 1 AS STATUS_ID, 'Chest pain' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 18 AS APPOINTMENT_ID, 2 AS PATIENT_ID, 6 AS DOCTOR_ID, TO_DATE('2026-07-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '15:00' AS APPOINTMENT_TIME, 1 AS STATUS_ID, 'Routine consultation' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 19 AS APPOINTMENT_ID, 17 AS PATIENT_ID, 3 AS DOCTOR_ID, TO_DATE('2026-07-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '10:00' AS APPOINTMENT_TIME, 1 AS STATUS_ID, 'Back pain' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 20 AS APPOINTMENT_ID, 17 AS PATIENT_ID, 1 AS DOCTOR_ID, TO_DATE('2026-07-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '10:00' AS APPOINTMENT_TIME, 1 AS STATUS_ID, 'Diabetes checkup' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 21 AS APPOINTMENT_ID, 1 AS PATIENT_ID, 3 AS DOCTOR_ID, TO_DATE('2026-07-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '10:00' AS APPOINTMENT_TIME, 3 AS STATUS_ID, 'Diabetes checkup' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 22 AS APPOINTMENT_ID, 4 AS PATIENT_ID, 9 AS DOCTOR_ID, TO_DATE('2026-07-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '11:30' AS APPOINTMENT_TIME, 4 AS STATUS_ID, 'Back pain' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 23 AS APPOINTMENT_ID, 17 AS PATIENT_ID, 9 AS DOCTOR_ID, TO_DATE('2026-07-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '09:30' AS APPOINTMENT_TIME, 1 AS STATUS_ID, 'Back pain' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 24 AS APPOINTMENT_ID, 2 AS PATIENT_ID, 4 AS DOCTOR_ID, TO_DATE('2026-07-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '11:00' AS APPOINTMENT_TIME, 2 AS STATUS_ID, 'Follow-up visit' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 25 AS APPOINTMENT_ID, 17 AS PATIENT_ID, 8 AS DOCTOR_ID, TO_DATE('2026-07-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '09:00' AS APPOINTMENT_TIME, 1 AS STATUS_ID, 'Follow-up visit' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 26 AS APPOINTMENT_ID, 15 AS PATIENT_ID, 6 AS DOCTOR_ID, TO_DATE('2026-07-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '15:00' AS APPOINTMENT_TIME, 1 AS STATUS_ID, 'Diabetes checkup' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 27 AS APPOINTMENT_ID, 17 AS PATIENT_ID, 4 AS DOCTOR_ID, TO_DATE('2026-07-11 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '14:30' AS APPOINTMENT_TIME, 4 AS STATUS_ID, 'Back pain' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 28 AS APPOINTMENT_ID, 16 AS PATIENT_ID, 9 AS DOCTOR_ID, TO_DATE('2026-07-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '15:00' AS APPOINTMENT_TIME, 3 AS STATUS_ID, 'Back pain' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 29 AS APPOINTMENT_ID, 7 AS PATIENT_ID, 8 AS DOCTOR_ID, TO_DATE('2026-07-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '14:00' AS APPOINTMENT_TIME, 2 AS STATUS_ID, 'Routine consultation' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);
MERGE INTO appointments t
USING (SELECT 30 AS APPOINTMENT_ID, 15 AS PATIENT_ID, 6 AS DOCTOR_ID, TO_DATE('2026-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE, '10:30' AS APPOINTMENT_TIME, 3 AS STATUS_ID, 'Follow-up visit' AS REASON_FOR_VISIT, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT FROM dual) s
ON (t.APPOINTMENT_ID = s.APPOINTMENT_ID)
WHEN NOT MATCHED THEN INSERT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
  VALUES (s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_DATE, s.APPOINTMENT_TIME, s.STATUS_ID, s.REASON_FOR_VISIT, s.CREATED_AT);

-- ============================================================
-- Table: visits
-- ============================================================
MERGE INTO visits t
USING (SELECT 1 AS VISIT_ID, 'Mild angina' AS DIAGNOSIS, 'Prescribed medication, advised follow-up in 2 weeks' AS NOTES, 1 AS PATIENT_ID, 1 AS DOCTOR_ID, 1 AS APPOINTMENT_ID, TO_TIMESTAMP('2026-07-13 06:15:58', 'YYYY-MM-DD HH24:MI:SS') AS VISIT_DATE FROM dual) s
ON (t.VISIT_ID = s.VISIT_ID)
WHEN NOT MATCHED THEN INSERT (VISIT_ID, DIAGNOSIS, NOTES, PATIENT_ID, DOCTOR_ID, APPOINTMENT_ID, VISIT_DATE)
  VALUES (s.VISIT_ID, s.DIAGNOSIS, s.NOTES, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_ID, s.VISIT_DATE);
MERGE INTO visits t
USING (SELECT 2 AS VISIT_ID, 'Routine vaccination' AS DIAGNOSIS, 'No complications' AS NOTES, 4 AS PATIENT_ID, 2 AS DOCTOR_ID, 4 AS APPOINTMENT_ID, TO_TIMESTAMP('2026-07-11 06:15:58', 'YYYY-MM-DD HH24:MI:SS') AS VISIT_DATE FROM dual) s
ON (t.VISIT_ID = s.VISIT_ID)
WHEN NOT MATCHED THEN INSERT (VISIT_ID, DIAGNOSIS, NOTES, PATIENT_ID, DOCTOR_ID, APPOINTMENT_ID, VISIT_DATE)
  VALUES (s.VISIT_ID, s.DIAGNOSIS, s.NOTES, s.PATIENT_ID, s.DOCTOR_ID, s.APPOINTMENT_ID, s.VISIT_DATE);

-- ============================================================
-- Table: patient_visits
-- ============================================================
MERGE INTO patient_visits t
USING (SELECT 1 AS VISIT_ID, 1 AS APPOINTMENT_ID, 1 AS PATIENT_ID, 1 AS DOCTOR_ID, TO_DATE('2026-07-03 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS VISIT_DATE, 'Chest tightness and shortness of breath' AS SYMPTOMS, 'Mild angina' AS DIAGNOSIS, 'Advised follow-up in 2 weeks' AS NOTES, TO_DATE('2026-07-26 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS FOLLOW_UP_DATE FROM dual) s
ON (t.VISIT_ID = s.VISIT_ID)
WHEN NOT MATCHED THEN INSERT (VISIT_ID, APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, VISIT_DATE, SYMPTOMS, DIAGNOSIS, NOTES, FOLLOW_UP_DATE)
  VALUES (s.VISIT_ID, s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.VISIT_DATE, s.SYMPTOMS, s.DIAGNOSIS, s.NOTES, s.FOLLOW_UP_DATE);
MERGE INTO patient_visits t
USING (SELECT 2 AS VISIT_ID, 2 AS APPOINTMENT_ID, 2 AS PATIENT_ID, 2 AS DOCTOR_ID, TO_DATE('2026-07-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS VISIT_DATE, 'Mild fever and cough' AS SYMPTOMS, 'Common cold' AS DIAGNOSIS, 'Prescribed rest and fluids' AS NOTES, TO_DATE('2026-07-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS FOLLOW_UP_DATE FROM dual) s
ON (t.VISIT_ID = s.VISIT_ID)
WHEN NOT MATCHED THEN INSERT (VISIT_ID, APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, VISIT_DATE, SYMPTOMS, DIAGNOSIS, NOTES, FOLLOW_UP_DATE)
  VALUES (s.VISIT_ID, s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.VISIT_DATE, s.SYMPTOMS, s.DIAGNOSIS, s.NOTES, s.FOLLOW_UP_DATE);
MERGE INTO patient_visits t
USING (SELECT 3 AS VISIT_ID, 3 AS APPOINTMENT_ID, 3 AS PATIENT_ID, 3 AS DOCTOR_ID, TO_DATE('2026-07-03 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS VISIT_DATE, 'Knee swelling and pain' AS SYMPTOMS, 'Ligament strain' AS DIAGNOSIS, 'Recommended physiotherapy' AS NOTES, TO_DATE('2026-07-24 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS FOLLOW_UP_DATE FROM dual) s
ON (t.VISIT_ID = s.VISIT_ID)
WHEN NOT MATCHED THEN INSERT (VISIT_ID, APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, VISIT_DATE, SYMPTOMS, DIAGNOSIS, NOTES, FOLLOW_UP_DATE)
  VALUES (s.VISIT_ID, s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.VISIT_DATE, s.SYMPTOMS, s.DIAGNOSIS, s.NOTES, s.FOLLOW_UP_DATE);
MERGE INTO patient_visits t
USING (SELECT 4 AS VISIT_ID, 4 AS APPOINTMENT_ID, 4 AS PATIENT_ID, 4 AS DOCTOR_ID, TO_DATE('2026-07-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS VISIT_DATE, 'Persistent headache' AS SYMPTOMS, 'Tension headache' AS DIAGNOSIS, 'Advised stress reduction' AS NOTES, TO_DATE('2026-08-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS FOLLOW_UP_DATE FROM dual) s
ON (t.VISIT_ID = s.VISIT_ID)
WHEN NOT MATCHED THEN INSERT (VISIT_ID, APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, VISIT_DATE, SYMPTOMS, DIAGNOSIS, NOTES, FOLLOW_UP_DATE)
  VALUES (s.VISIT_ID, s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.VISIT_DATE, s.SYMPTOMS, s.DIAGNOSIS, s.NOTES, s.FOLLOW_UP_DATE);
MERGE INTO patient_visits t
USING (SELECT 5 AS VISIT_ID, 5 AS APPOINTMENT_ID, 5 AS PATIENT_ID, 5 AS DOCTOR_ID, TO_DATE('2026-07-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS VISIT_DATE, 'Skin rash and itching' AS SYMPTOMS, 'Allergic dermatitis' AS DIAGNOSIS, 'Prescribed antihistamine' AS NOTES, TO_DATE('2026-07-24 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS FOLLOW_UP_DATE FROM dual) s
ON (t.VISIT_ID = s.VISIT_ID)
WHEN NOT MATCHED THEN INSERT (VISIT_ID, APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, VISIT_DATE, SYMPTOMS, DIAGNOSIS, NOTES, FOLLOW_UP_DATE)
  VALUES (s.VISIT_ID, s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.VISIT_DATE, s.SYMPTOMS, s.DIAGNOSIS, s.NOTES, s.FOLLOW_UP_DATE);
MERGE INTO patient_visits t
USING (SELECT 6 AS VISIT_ID, 6 AS APPOINTMENT_ID, 6 AS PATIENT_ID, 6 AS DOCTOR_ID, TO_DATE('2026-07-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS VISIT_DATE, 'Fatigue and dizziness' AS SYMPTOMS, 'Anemia suspected' AS DIAGNOSIS, 'Blood test ordered' AS NOTES, TO_DATE('2026-07-24 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS FOLLOW_UP_DATE FROM dual) s
ON (t.VISIT_ID = s.VISIT_ID)
WHEN NOT MATCHED THEN INSERT (VISIT_ID, APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, VISIT_DATE, SYMPTOMS, DIAGNOSIS, NOTES, FOLLOW_UP_DATE)
  VALUES (s.VISIT_ID, s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.VISIT_DATE, s.SYMPTOMS, s.DIAGNOSIS, s.NOTES, s.FOLLOW_UP_DATE);
MERGE INTO patient_visits t
USING (SELECT 7 AS VISIT_ID, 7 AS APPOINTMENT_ID, 7 AS PATIENT_ID, 7 AS DOCTOR_ID, TO_DATE('2026-07-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS VISIT_DATE, 'Sore throat and cough' AS SYMPTOMS, 'Viral pharyngitis' AS DIAGNOSIS, 'Advised warm saline gargle' AS NOTES, TO_DATE('2026-07-27 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS FOLLOW_UP_DATE FROM dual) s
ON (t.VISIT_ID = s.VISIT_ID)
WHEN NOT MATCHED THEN INSERT (VISIT_ID, APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, VISIT_DATE, SYMPTOMS, DIAGNOSIS, NOTES, FOLLOW_UP_DATE)
  VALUES (s.VISIT_ID, s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.VISIT_DATE, s.SYMPTOMS, s.DIAGNOSIS, s.NOTES, s.FOLLOW_UP_DATE);
MERGE INTO patient_visits t
USING (SELECT 8 AS VISIT_ID, 8 AS APPOINTMENT_ID, 8 AS PATIENT_ID, 8 AS DOCTOR_ID, TO_DATE('2026-07-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS VISIT_DATE, 'Abdominal pain' AS SYMPTOMS, 'Gastritis' AS DIAGNOSIS, 'Prescribed antacid' AS NOTES, TO_DATE('2026-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS FOLLOW_UP_DATE FROM dual) s
ON (t.VISIT_ID = s.VISIT_ID)
WHEN NOT MATCHED THEN INSERT (VISIT_ID, APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, VISIT_DATE, SYMPTOMS, DIAGNOSIS, NOTES, FOLLOW_UP_DATE)
  VALUES (s.VISIT_ID, s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.VISIT_DATE, s.SYMPTOMS, s.DIAGNOSIS, s.NOTES, s.FOLLOW_UP_DATE);
MERGE INTO patient_visits t
USING (SELECT 9 AS VISIT_ID, 9 AS APPOINTMENT_ID, 9 AS PATIENT_ID, 9 AS DOCTOR_ID, TO_DATE('2026-07-03 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS VISIT_DATE, 'Joint stiffness' AS SYMPTOMS, 'Osteoarthritis' AS DIAGNOSIS, 'Advised light exercise' AS NOTES, TO_DATE('2026-07-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS FOLLOW_UP_DATE FROM dual) s
ON (t.VISIT_ID = s.VISIT_ID)
WHEN NOT MATCHED THEN INSERT (VISIT_ID, APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, VISIT_DATE, SYMPTOMS, DIAGNOSIS, NOTES, FOLLOW_UP_DATE)
  VALUES (s.VISIT_ID, s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.VISIT_DATE, s.SYMPTOMS, s.DIAGNOSIS, s.NOTES, s.FOLLOW_UP_DATE);
MERGE INTO patient_visits t
USING (SELECT 10 AS VISIT_ID, 10 AS APPOINTMENT_ID, 10 AS PATIENT_ID, 1 AS DOCTOR_ID, TO_DATE('2026-07-11 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS VISIT_DATE, 'High blood sugar readings' AS SYMPTOMS, 'Type 2 Diabetes' AS DIAGNOSIS, 'Advised diet control' AS NOTES, TO_DATE('2026-07-27 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS FOLLOW_UP_DATE FROM dual) s
ON (t.VISIT_ID = s.VISIT_ID)
WHEN NOT MATCHED THEN INSERT (VISIT_ID, APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, VISIT_DATE, SYMPTOMS, DIAGNOSIS, NOTES, FOLLOW_UP_DATE)
  VALUES (s.VISIT_ID, s.APPOINTMENT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.VISIT_DATE, s.SYMPTOMS, s.DIAGNOSIS, s.NOTES, s.FOLLOW_UP_DATE);

-- ============================================================
-- Table: prescriptions
-- ============================================================
MERGE INTO prescriptions t
USING (SELECT 1 AS PRESCRIPTION_ID, 1 AS VISIT_ID, 1 AS PATIENT_ID, 1 AS DOCTOR_ID, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS PRESCRIPTION_DATE, 'Take medicines as directed' AS NOTES FROM dual) s
ON (t.PRESCRIPTION_ID = s.PRESCRIPTION_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ID, VISIT_ID, PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES)
  VALUES (s.PRESCRIPTION_ID, s.VISIT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.PRESCRIPTION_DATE, s.NOTES);
MERGE INTO prescriptions t
USING (SELECT 2 AS PRESCRIPTION_ID, 2 AS VISIT_ID, 2 AS PATIENT_ID, 2 AS DOCTOR_ID, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS PRESCRIPTION_DATE, 'Take medicines as directed' AS NOTES FROM dual) s
ON (t.PRESCRIPTION_ID = s.PRESCRIPTION_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ID, VISIT_ID, PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES)
  VALUES (s.PRESCRIPTION_ID, s.VISIT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.PRESCRIPTION_DATE, s.NOTES);
MERGE INTO prescriptions t
USING (SELECT 3 AS PRESCRIPTION_ID, 3 AS VISIT_ID, 3 AS PATIENT_ID, 3 AS DOCTOR_ID, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS PRESCRIPTION_DATE, 'Take medicines as directed' AS NOTES FROM dual) s
ON (t.PRESCRIPTION_ID = s.PRESCRIPTION_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ID, VISIT_ID, PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES)
  VALUES (s.PRESCRIPTION_ID, s.VISIT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.PRESCRIPTION_DATE, s.NOTES);
MERGE INTO prescriptions t
USING (SELECT 4 AS PRESCRIPTION_ID, 4 AS VISIT_ID, 4 AS PATIENT_ID, 4 AS DOCTOR_ID, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS PRESCRIPTION_DATE, 'Take medicines as directed' AS NOTES FROM dual) s
ON (t.PRESCRIPTION_ID = s.PRESCRIPTION_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ID, VISIT_ID, PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES)
  VALUES (s.PRESCRIPTION_ID, s.VISIT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.PRESCRIPTION_DATE, s.NOTES);
MERGE INTO prescriptions t
USING (SELECT 5 AS PRESCRIPTION_ID, 5 AS VISIT_ID, 5 AS PATIENT_ID, 5 AS DOCTOR_ID, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS PRESCRIPTION_DATE, 'Take medicines as directed' AS NOTES FROM dual) s
ON (t.PRESCRIPTION_ID = s.PRESCRIPTION_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ID, VISIT_ID, PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES)
  VALUES (s.PRESCRIPTION_ID, s.VISIT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.PRESCRIPTION_DATE, s.NOTES);
MERGE INTO prescriptions t
USING (SELECT 6 AS PRESCRIPTION_ID, 6 AS VISIT_ID, 6 AS PATIENT_ID, 6 AS DOCTOR_ID, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS PRESCRIPTION_DATE, 'Take medicines as directed' AS NOTES FROM dual) s
ON (t.PRESCRIPTION_ID = s.PRESCRIPTION_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ID, VISIT_ID, PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES)
  VALUES (s.PRESCRIPTION_ID, s.VISIT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.PRESCRIPTION_DATE, s.NOTES);
MERGE INTO prescriptions t
USING (SELECT 7 AS PRESCRIPTION_ID, 7 AS VISIT_ID, 7 AS PATIENT_ID, 7 AS DOCTOR_ID, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS PRESCRIPTION_DATE, 'Take medicines as directed' AS NOTES FROM dual) s
ON (t.PRESCRIPTION_ID = s.PRESCRIPTION_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ID, VISIT_ID, PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES)
  VALUES (s.PRESCRIPTION_ID, s.VISIT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.PRESCRIPTION_DATE, s.NOTES);
MERGE INTO prescriptions t
USING (SELECT 8 AS PRESCRIPTION_ID, 8 AS VISIT_ID, 8 AS PATIENT_ID, 8 AS DOCTOR_ID, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS PRESCRIPTION_DATE, 'Take medicines as directed' AS NOTES FROM dual) s
ON (t.PRESCRIPTION_ID = s.PRESCRIPTION_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ID, VISIT_ID, PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES)
  VALUES (s.PRESCRIPTION_ID, s.VISIT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.PRESCRIPTION_DATE, s.NOTES);
MERGE INTO prescriptions t
USING (SELECT 9 AS PRESCRIPTION_ID, 9 AS VISIT_ID, 9 AS PATIENT_ID, 9 AS DOCTOR_ID, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS PRESCRIPTION_DATE, 'Take medicines as directed' AS NOTES FROM dual) s
ON (t.PRESCRIPTION_ID = s.PRESCRIPTION_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ID, VISIT_ID, PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES)
  VALUES (s.PRESCRIPTION_ID, s.VISIT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.PRESCRIPTION_DATE, s.NOTES);
MERGE INTO prescriptions t
USING (SELECT 10 AS PRESCRIPTION_ID, 10 AS VISIT_ID, 10 AS PATIENT_ID, 1 AS DOCTOR_ID, TO_TIMESTAMP('2026-07-13 08:33:50', 'YYYY-MM-DD HH24:MI:SS') AS PRESCRIPTION_DATE, 'Take medicines as directed' AS NOTES FROM dual) s
ON (t.PRESCRIPTION_ID = s.PRESCRIPTION_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ID, VISIT_ID, PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES)
  VALUES (s.PRESCRIPTION_ID, s.VISIT_ID, s.PATIENT_ID, s.DOCTOR_ID, s.PRESCRIPTION_DATE, s.NOTES);

-- ============================================================
-- Table: prescription_items
-- ============================================================
MERGE INTO prescription_items t
USING (SELECT 1 AS PRESCRIPTION_ITEM_ID, 1 AS PRESCRIPTION_ID, 17 AS MEDICINE_ID, '5mg' AS DOSAGE, 'Three times daily' AS FREQUENCY, 10 AS DURATION_DAYS, 'Before food' AS INSTRUCTIONS FROM dual) s
ON (t.PRESCRIPTION_ITEM_ID = s.PRESCRIPTION_ITEM_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
  VALUES (s.PRESCRIPTION_ITEM_ID, s.PRESCRIPTION_ID, s.MEDICINE_ID, s.DOSAGE, s.FREQUENCY, s.DURATION_DAYS, s.INSTRUCTIONS);
MERGE INTO prescription_items t
USING (SELECT 2 AS PRESCRIPTION_ITEM_ID, 1 AS PRESCRIPTION_ID, 12 AS MEDICINE_ID, '10mg' AS DOSAGE, 'Once daily' AS FREQUENCY, 30 AS DURATION_DAYS, 'With plenty of water' AS INSTRUCTIONS FROM dual) s
ON (t.PRESCRIPTION_ITEM_ID = s.PRESCRIPTION_ITEM_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
  VALUES (s.PRESCRIPTION_ITEM_ID, s.PRESCRIPTION_ID, s.MEDICINE_ID, s.DOSAGE, s.FREQUENCY, s.DURATION_DAYS, s.INSTRUCTIONS);
MERGE INTO prescription_items t
USING (SELECT 3 AS PRESCRIPTION_ITEM_ID, 2 AS PRESCRIPTION_ID, 11 AS MEDICINE_ID, '1 tablet' AS DOSAGE, 'Every 8 hours' AS FREQUENCY, 10 AS DURATION_DAYS, 'After food' AS INSTRUCTIONS FROM dual) s
ON (t.PRESCRIPTION_ITEM_ID = s.PRESCRIPTION_ITEM_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
  VALUES (s.PRESCRIPTION_ITEM_ID, s.PRESCRIPTION_ID, s.MEDICINE_ID, s.DOSAGE, s.FREQUENCY, s.DURATION_DAYS, s.INSTRUCTIONS);
MERGE INTO prescription_items t
USING (SELECT 4 AS PRESCRIPTION_ITEM_ID, 3 AS PRESCRIPTION_ID, 11 AS MEDICINE_ID, '1 tablet' AS DOSAGE, 'At bedtime' AS FREQUENCY, 7 AS DURATION_DAYS, 'After food, avoid dairy' AS INSTRUCTIONS FROM dual) s
ON (t.PRESCRIPTION_ITEM_ID = s.PRESCRIPTION_ITEM_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
  VALUES (s.PRESCRIPTION_ITEM_ID, s.PRESCRIPTION_ID, s.MEDICINE_ID, s.DOSAGE, s.FREQUENCY, s.DURATION_DAYS, s.INSTRUCTIONS);
MERGE INTO prescription_items t
USING (SELECT 5 AS PRESCRIPTION_ITEM_ID, 3 AS PRESCRIPTION_ID, 3 AS MEDICINE_ID, '500mg' AS DOSAGE, 'Twice daily' AS FREQUENCY, 3 AS DURATION_DAYS, 'After food' AS INSTRUCTIONS FROM dual) s
ON (t.PRESCRIPTION_ITEM_ID = s.PRESCRIPTION_ITEM_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
  VALUES (s.PRESCRIPTION_ITEM_ID, s.PRESCRIPTION_ID, s.MEDICINE_ID, s.DOSAGE, s.FREQUENCY, s.DURATION_DAYS, s.INSTRUCTIONS);
MERGE INTO prescription_items t
USING (SELECT 6 AS PRESCRIPTION_ITEM_ID, 4 AS PRESCRIPTION_ID, 9 AS MEDICINE_ID, '500mg' AS DOSAGE, 'Twice daily' AS FREQUENCY, 7 AS DURATION_DAYS, 'Before food' AS INSTRUCTIONS FROM dual) s
ON (t.PRESCRIPTION_ITEM_ID = s.PRESCRIPTION_ITEM_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
  VALUES (s.PRESCRIPTION_ITEM_ID, s.PRESCRIPTION_ID, s.MEDICINE_ID, s.DOSAGE, s.FREQUENCY, s.DURATION_DAYS, s.INSTRUCTIONS);
MERGE INTO prescription_items t
USING (SELECT 7 AS PRESCRIPTION_ITEM_ID, 4 AS PRESCRIPTION_ID, 14 AS MEDICINE_ID, '5ml' AS DOSAGE, 'Three times daily' AS FREQUENCY, 10 AS DURATION_DAYS, 'Before food' AS INSTRUCTIONS FROM dual) s
ON (t.PRESCRIPTION_ITEM_ID = s.PRESCRIPTION_ITEM_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
  VALUES (s.PRESCRIPTION_ITEM_ID, s.PRESCRIPTION_ID, s.MEDICINE_ID, s.DOSAGE, s.FREQUENCY, s.DURATION_DAYS, s.INSTRUCTIONS);
MERGE INTO prescription_items t
USING (SELECT 8 AS PRESCRIPTION_ITEM_ID, 5 AS PRESCRIPTION_ID, 11 AS MEDICINE_ID, '500mg' AS DOSAGE, 'Three times daily' AS FREQUENCY, 3 AS DURATION_DAYS, 'Before food' AS INSTRUCTIONS FROM dual) s
ON (t.PRESCRIPTION_ITEM_ID = s.PRESCRIPTION_ITEM_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
  VALUES (s.PRESCRIPTION_ITEM_ID, s.PRESCRIPTION_ID, s.MEDICINE_ID, s.DOSAGE, s.FREQUENCY, s.DURATION_DAYS, s.INSTRUCTIONS);
MERGE INTO prescription_items t
USING (SELECT 9 AS PRESCRIPTION_ITEM_ID, 5 AS PRESCRIPTION_ID, 14 AS MEDICINE_ID, '500mg' AS DOSAGE, 'Three times daily' AS FREQUENCY, 3 AS DURATION_DAYS, 'After food' AS INSTRUCTIONS FROM dual) s
ON (t.PRESCRIPTION_ITEM_ID = s.PRESCRIPTION_ITEM_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
  VALUES (s.PRESCRIPTION_ITEM_ID, s.PRESCRIPTION_ID, s.MEDICINE_ID, s.DOSAGE, s.FREQUENCY, s.DURATION_DAYS, s.INSTRUCTIONS);
MERGE INTO prescription_items t
USING (SELECT 10 AS PRESCRIPTION_ITEM_ID, 6 AS PRESCRIPTION_ID, 3 AS MEDICINE_ID, '1 tablet' AS DOSAGE, 'Twice daily' AS FREQUENCY, 3 AS DURATION_DAYS, 'With plenty of water' AS INSTRUCTIONS FROM dual) s
ON (t.PRESCRIPTION_ITEM_ID = s.PRESCRIPTION_ITEM_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
  VALUES (s.PRESCRIPTION_ITEM_ID, s.PRESCRIPTION_ID, s.MEDICINE_ID, s.DOSAGE, s.FREQUENCY, s.DURATION_DAYS, s.INSTRUCTIONS);
MERGE INTO prescription_items t
USING (SELECT 11 AS PRESCRIPTION_ITEM_ID, 6 AS PRESCRIPTION_ID, 4 AS MEDICINE_ID, '5mg' AS DOSAGE, 'Once daily' AS FREQUENCY, 7 AS DURATION_DAYS, 'After food, avoid dairy' AS INSTRUCTIONS FROM dual) s
ON (t.PRESCRIPTION_ITEM_ID = s.PRESCRIPTION_ITEM_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
  VALUES (s.PRESCRIPTION_ITEM_ID, s.PRESCRIPTION_ID, s.MEDICINE_ID, s.DOSAGE, s.FREQUENCY, s.DURATION_DAYS, s.INSTRUCTIONS);
MERGE INTO prescription_items t
USING (SELECT 12 AS PRESCRIPTION_ITEM_ID, 7 AS PRESCRIPTION_ID, 9 AS MEDICINE_ID, '1 tablet' AS DOSAGE, 'Twice daily' AS FREQUENCY, 3 AS DURATION_DAYS, 'After food, avoid dairy' AS INSTRUCTIONS FROM dual) s
ON (t.PRESCRIPTION_ITEM_ID = s.PRESCRIPTION_ITEM_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
  VALUES (s.PRESCRIPTION_ITEM_ID, s.PRESCRIPTION_ID, s.MEDICINE_ID, s.DOSAGE, s.FREQUENCY, s.DURATION_DAYS, s.INSTRUCTIONS);
MERGE INTO prescription_items t
USING (SELECT 13 AS PRESCRIPTION_ITEM_ID, 7 AS PRESCRIPTION_ID, 8 AS MEDICINE_ID, '500mg' AS DOSAGE, 'Twice daily' AS FREQUENCY, 7 AS DURATION_DAYS, 'After food' AS INSTRUCTIONS FROM dual) s
ON (t.PRESCRIPTION_ITEM_ID = s.PRESCRIPTION_ITEM_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
  VALUES (s.PRESCRIPTION_ITEM_ID, s.PRESCRIPTION_ID, s.MEDICINE_ID, s.DOSAGE, s.FREQUENCY, s.DURATION_DAYS, s.INSTRUCTIONS);
MERGE INTO prescription_items t
USING (SELECT 14 AS PRESCRIPTION_ITEM_ID, 8 AS PRESCRIPTION_ID, 7 AS MEDICINE_ID, '10mg' AS DOSAGE, 'Three times daily' AS FREQUENCY, 14 AS DURATION_DAYS, 'Before food' AS INSTRUCTIONS FROM dual) s
ON (t.PRESCRIPTION_ITEM_ID = s.PRESCRIPTION_ITEM_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
  VALUES (s.PRESCRIPTION_ITEM_ID, s.PRESCRIPTION_ID, s.MEDICINE_ID, s.DOSAGE, s.FREQUENCY, s.DURATION_DAYS, s.INSTRUCTIONS);
MERGE INTO prescription_items t
USING (SELECT 15 AS PRESCRIPTION_ITEM_ID, 9 AS PRESCRIPTION_ID, 15 AS MEDICINE_ID, '1 tablet' AS DOSAGE, 'Twice daily' AS FREQUENCY, 7 AS DURATION_DAYS, 'With plenty of water' AS INSTRUCTIONS FROM dual) s
ON (t.PRESCRIPTION_ITEM_ID = s.PRESCRIPTION_ITEM_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
  VALUES (s.PRESCRIPTION_ITEM_ID, s.PRESCRIPTION_ID, s.MEDICINE_ID, s.DOSAGE, s.FREQUENCY, s.DURATION_DAYS, s.INSTRUCTIONS);
MERGE INTO prescription_items t
USING (SELECT 16 AS PRESCRIPTION_ITEM_ID, 9 AS PRESCRIPTION_ID, 1 AS MEDICINE_ID, '10mg' AS DOSAGE, 'Once daily' AS FREQUENCY, 3 AS DURATION_DAYS, 'After food' AS INSTRUCTIONS FROM dual) s
ON (t.PRESCRIPTION_ITEM_ID = s.PRESCRIPTION_ITEM_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
  VALUES (s.PRESCRIPTION_ITEM_ID, s.PRESCRIPTION_ID, s.MEDICINE_ID, s.DOSAGE, s.FREQUENCY, s.DURATION_DAYS, s.INSTRUCTIONS);
MERGE INTO prescription_items t
USING (SELECT 17 AS PRESCRIPTION_ITEM_ID, 10 AS PRESCRIPTION_ID, 17 AS MEDICINE_ID, '5mg' AS DOSAGE, 'Twice daily' AS FREQUENCY, 10 AS DURATION_DAYS, 'After food' AS INSTRUCTIONS FROM dual) s
ON (t.PRESCRIPTION_ITEM_ID = s.PRESCRIPTION_ITEM_ID)
WHEN NOT MATCHED THEN INSERT (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
  VALUES (s.PRESCRIPTION_ITEM_ID, s.PRESCRIPTION_ID, s.MEDICINE_ID, s.DOSAGE, s.FREQUENCY, s.DURATION_DAYS, s.INSTRUCTIONS);

-- ============================================================
-- Table: admissions
-- ============================================================
MERGE INTO admissions t
USING (SELECT 21 AS ADMISSION_ID, 'Admitted' AS STATUS, 14 AS PATIENT_ID, 4 AS DOCTOR_ID, 8 AS ROOM_ID, TO_DATE('2026-07-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS ADMISSION_DATE, TO_DATE('2026-07-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DISCHARGE_DATE, 'JKN' AS ADMISSION_REASON FROM dual) s
ON (t.ADMISSION_ID = s.ADMISSION_ID)
WHEN NOT MATCHED THEN INSERT (ADMISSION_ID, STATUS, PATIENT_ID, DOCTOR_ID, ROOM_ID, ADMISSION_DATE, DISCHARGE_DATE, ADMISSION_REASON)
  VALUES (s.ADMISSION_ID, s.STATUS, s.PATIENT_ID, s.DOCTOR_ID, s.ROOM_ID, s.ADMISSION_DATE, s.DISCHARGE_DATE, s.ADMISSION_REASON);
MERGE INTO admissions t
USING (SELECT 26 AS ADMISSION_ID, 'Admitted' AS STATUS, 3 AS PATIENT_ID, 8 AS DOCTOR_ID, 6 AS ROOM_ID, TO_DATE('2026-07-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS ADMISSION_DATE, TO_DATE('2026-07-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DISCHARGE_DATE, 'ttttt' AS ADMISSION_REASON FROM dual) s
ON (t.ADMISSION_ID = s.ADMISSION_ID)
WHEN NOT MATCHED THEN INSERT (ADMISSION_ID, STATUS, PATIENT_ID, DOCTOR_ID, ROOM_ID, ADMISSION_DATE, DISCHARGE_DATE, ADMISSION_REASON)
  VALUES (s.ADMISSION_ID, s.STATUS, s.PATIENT_ID, s.DOCTOR_ID, s.ROOM_ID, s.ADMISSION_DATE, s.DISCHARGE_DATE, s.ADMISSION_REASON);
MERGE INTO admissions t
USING (SELECT 1 AS ADMISSION_ID, 'Admitted' AS STATUS, 3 AS PATIENT_ID, 3 AS DOCTOR_ID, 1 AS ROOM_ID, TO_DATE('2026-07-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS ADMISSION_DATE, NULL AS DISCHARGE_DATE, 'Knee surgery recovery' AS ADMISSION_REASON FROM dual) s
ON (t.ADMISSION_ID = s.ADMISSION_ID)
WHEN NOT MATCHED THEN INSERT (ADMISSION_ID, STATUS, PATIENT_ID, DOCTOR_ID, ROOM_ID, ADMISSION_DATE, DISCHARGE_DATE, ADMISSION_REASON)
  VALUES (s.ADMISSION_ID, s.STATUS, s.PATIENT_ID, s.DOCTOR_ID, s.ROOM_ID, s.ADMISSION_DATE, s.DISCHARGE_DATE, s.ADMISSION_REASON);
MERGE INTO admissions t
USING (SELECT 2 AS ADMISSION_ID, 'Admitted' AS STATUS, 7 AS PATIENT_ID, 5 AS DOCTOR_ID, 7 AS ROOM_ID, TO_DATE('2026-07-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS ADMISSION_DATE, NULL AS DISCHARGE_DATE, 'Chest pain observation' AS ADMISSION_REASON FROM dual) s
ON (t.ADMISSION_ID = s.ADMISSION_ID)
WHEN NOT MATCHED THEN INSERT (ADMISSION_ID, STATUS, PATIENT_ID, DOCTOR_ID, ROOM_ID, ADMISSION_DATE, DISCHARGE_DATE, ADMISSION_REASON)
  VALUES (s.ADMISSION_ID, s.STATUS, s.PATIENT_ID, s.DOCTOR_ID, s.ROOM_ID, s.ADMISSION_DATE, s.DISCHARGE_DATE, s.ADMISSION_REASON);
MERGE INTO admissions t
USING (SELECT 3 AS ADMISSION_ID, 'Discharged' AS STATUS, 12 AS PATIENT_ID, 1 AS DOCTOR_ID, 2 AS ROOM_ID, TO_DATE('2026-07-03 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS ADMISSION_DATE, TO_DATE('2026-07-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DISCHARGE_DATE, 'Post-surgical recovery' AS ADMISSION_REASON FROM dual) s
ON (t.ADMISSION_ID = s.ADMISSION_ID)
WHEN NOT MATCHED THEN INSERT (ADMISSION_ID, STATUS, PATIENT_ID, DOCTOR_ID, ROOM_ID, ADMISSION_DATE, DISCHARGE_DATE, ADMISSION_REASON)
  VALUES (s.ADMISSION_ID, s.STATUS, s.PATIENT_ID, s.DOCTOR_ID, s.ROOM_ID, s.ADMISSION_DATE, s.DISCHARGE_DATE, s.ADMISSION_REASON);
MERGE INTO admissions t
USING (SELECT 4 AS ADMISSION_ID, 'Discharged' AS STATUS, 15 AS PATIENT_ID, 4 AS DOCTOR_ID, 8 AS ROOM_ID, TO_DATE('2026-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS ADMISSION_DATE, TO_DATE('2026-07-11 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DISCHARGE_DATE, 'Diabetes management' AS ADMISSION_REASON FROM dual) s
ON (t.ADMISSION_ID = s.ADMISSION_ID)
WHEN NOT MATCHED THEN INSERT (ADMISSION_ID, STATUS, PATIENT_ID, DOCTOR_ID, ROOM_ID, ADMISSION_DATE, DISCHARGE_DATE, ADMISSION_REASON)
  VALUES (s.ADMISSION_ID, s.STATUS, s.PATIENT_ID, s.DOCTOR_ID, s.ROOM_ID, s.ADMISSION_DATE, s.DISCHARGE_DATE, s.ADMISSION_REASON);
MERGE INTO admissions t
USING (SELECT 5 AS ADMISSION_ID, 'Admitted' AS STATUS, 2 AS PATIENT_ID, 2 AS DOCTOR_ID, 4 AS ROOM_ID, TO_DATE('2026-07-11 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS ADMISSION_DATE, NULL AS DISCHARGE_DATE, 'Pediatric observation' AS ADMISSION_REASON FROM dual) s
ON (t.ADMISSION_ID = s.ADMISSION_ID)
WHEN NOT MATCHED THEN INSERT (ADMISSION_ID, STATUS, PATIENT_ID, DOCTOR_ID, ROOM_ID, ADMISSION_DATE, DISCHARGE_DATE, ADMISSION_REASON)
  VALUES (s.ADMISSION_ID, s.STATUS, s.PATIENT_ID, s.DOCTOR_ID, s.ROOM_ID, s.ADMISSION_DATE, s.DISCHARGE_DATE, s.ADMISSION_REASON);
MERGE INTO admissions t
USING (SELECT 6 AS ADMISSION_ID, 'Discharged' AS STATUS, 18 AS PATIENT_ID, 5 AS DOCTOR_ID, 9 AS ROOM_ID, TO_DATE('2026-06-28 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS ADMISSION_DATE, TO_DATE('2026-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DISCHARGE_DATE, 'Emergency stabilization' AS ADMISSION_REASON FROM dual) s
ON (t.ADMISSION_ID = s.ADMISSION_ID)
WHEN NOT MATCHED THEN INSERT (ADMISSION_ID, STATUS, PATIENT_ID, DOCTOR_ID, ROOM_ID, ADMISSION_DATE, DISCHARGE_DATE, ADMISSION_REASON)
  VALUES (s.ADMISSION_ID, s.STATUS, s.PATIENT_ID, s.DOCTOR_ID, s.ROOM_ID, s.ADMISSION_DATE, s.DISCHARGE_DATE, s.ADMISSION_REASON);
MERGE INTO admissions t
USING (SELECT 22 AS ADMISSION_ID, 'Discharged' AS STATUS, 6 AS PATIENT_ID, 4 AS DOCTOR_ID, 5 AS ROOM_ID, TO_DATE('2026-07-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS ADMISSION_DATE, TO_DATE('2026-07-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DISCHARGE_DATE, 'fghsxf' AS ADMISSION_REASON FROM dual) s
ON (t.ADMISSION_ID = s.ADMISSION_ID)
WHEN NOT MATCHED THEN INSERT (ADMISSION_ID, STATUS, PATIENT_ID, DOCTOR_ID, ROOM_ID, ADMISSION_DATE, DISCHARGE_DATE, ADMISSION_REASON)
  VALUES (s.ADMISSION_ID, s.STATUS, s.PATIENT_ID, s.DOCTOR_ID, s.ROOM_ID, s.ADMISSION_DATE, s.DISCHARGE_DATE, s.ADMISSION_REASON);

COMMIT;