  CREATE TABLE "APPOINTMENTS" 
   (	"APPOINTMENT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PATIENT_ID" NUMBER NOT NULL ENABLE, 
	"DOCTOR_ID" NUMBER NOT NULL ENABLE, 
	"APPOINTMENT_DATE" DATE NOT NULL ENABLE, 
	"APPOINTMENT_TIME" VARCHAR2(10) NOT NULL ENABLE, 
	"STATUS_ID" NUMBER NOT NULL ENABLE, 
	"REASON_FOR_VISIT" VARCHAR2(300), 
	"CREATED_AT" DATE NOT NULL ENABLE, 
	 PRIMARY KEY ("APPOINTMENT_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "APPOINTMENT_STATUSES" 
   (	"STATUS_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"STATUS_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	 CHECK (STATUS_NAME IN ('Scheduled', 'Completed', 'Cancelled', 'No Show')) ENABLE, 
	 PRIMARY KEY ("STATUS_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "DEPARTMENTS" 
   (	"DEPARTMENT_ID" NUMBER(*,0), 
	"DEPARTMENT_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"FLOOR_NO" NUMBER(*,0) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(10) NOT NULL ENABLE, 
	 CHECK (STATUS IN ('Active', 'Inactive')) ENABLE, 
	 PRIMARY KEY ("DEPARTMENT_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "DOCTORS" 
   (	"DOCTOR_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"FULL_NAME" VARCHAR2(150) NOT NULL ENABLE, 
	"DEPARTMENT_ID" NUMBER NOT NULL ENABLE, 
	"SPECIALTY_ID" NUMBER NOT NULL ENABLE, 
	"MOBILE_NO" VARCHAR2(20) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(150), 
	"CONSULTATION_FEE" NUMBER(8,2) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(10) NOT NULL ENABLE, 
	 CHECK (STATUS IN ('Active', 'Inactive')) ENABLE, 
	 PRIMARY KEY ("DOCTOR_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "DOCTOR_SPECIALTIES" 
   (	"SPECIALTY_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"SPECIALTY_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(10) NOT NULL ENABLE, 
	 CHECK (STATUS IN ('Active', 'Inactive')) ENABLE, 
	 PRIMARY KEY ("SPECIALTY_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "MEDICINES" 
   (	"MEDICINE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"MEDICINE_NAME" VARCHAR2(150) NOT NULL ENABLE, 
	"CATEGORY_ID" NUMBER NOT NULL ENABLE, 
	"UNIT" VARCHAR2(30) NOT NULL ENABLE, 
	"CURRENT_STOCK" NUMBER NOT NULL ENABLE, 
	"REORDER_LEVEL" NUMBER NOT NULL ENABLE, 
	"STATUS" VARCHAR2(10) NOT NULL ENABLE, 
	 CHECK (STATUS IN ('Active', 'Inactive')) ENABLE, 
	 PRIMARY KEY ("MEDICINE_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "MEDICINE_CATEGORIES" 
   (	"CATEGORY_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CATEGORY_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(10) NOT NULL ENABLE, 
	 CHECK (STATUS IN ('Active', 'Inactive')) ENABLE, 
	 PRIMARY KEY ("CATEGORY_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PATIENTS" 
   (	"PATIENT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CIVIL_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"FULL_NAME" VARCHAR2(150) NOT NULL ENABLE, 
	"GENDER" VARCHAR2(10) NOT NULL ENABLE, 
	"DATE_OF_BIRTH" DATE NOT NULL ENABLE, 
	"MOBILE_NO" VARCHAR2(20) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(150), 
	"BLOOD_GROUP" VARCHAR2(5), 
	"ADDRESS" VARCHAR2(300), 
	"EMERGENCY_CONTACT_NAME" VARCHAR2(150), 
	"EMERGENCY_CONTACT_NO" VARCHAR2(20), 
	"CREATED_AT" DATE NOT NULL ENABLE, 
	 CHECK (GENDER IN ('Male', 'Female')) ENABLE, 
	 CHECK (BLOOD_GROUP IN ('A+','A-','B+','B-','O+','O-','AB+','AB-')) ENABLE, 
	 PRIMARY KEY ("PATIENT_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("CIVIL_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PATIENT_VISITS" 
   (	"VISIT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"APPOINTMENT_ID" NUMBER NOT NULL ENABLE, 
	"PATIENT_ID" NUMBER NOT NULL ENABLE, 
	"DOCTOR_ID" NUMBER NOT NULL ENABLE, 
	"VISIT_DATE" DATE NOT NULL ENABLE, 
	"SYMPTOMS" VARCHAR2(500), 
	"DIAGNOSIS" VARCHAR2(500), 
	"NOTES" VARCHAR2(1000), 
	"FOLLOW_UP_DATE" DATE, 
	 PRIMARY KEY ("VISIT_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PRESCRIPTIONS" 
   (	"PRESCRIPTION_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"VISIT_ID" NUMBER NOT NULL ENABLE, 
	"PATIENT_ID" NUMBER NOT NULL ENABLE, 
	"DOCTOR_ID" NUMBER NOT NULL ENABLE, 
	"PRESCRIPTION_DATE" DATE NOT NULL ENABLE, 
	"NOTES" VARCHAR2(500), 
	 PRIMARY KEY ("PRESCRIPTION_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_PRESCRIPTIONS_VISIT_ID" UNIQUE ("VISIT_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PRESCRIPTION_ITEMS" 
   (	"PRESCRIPTION_ITEM_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PRESCRIPTION_ID" NUMBER NOT NULL ENABLE, 
	"MEDICINE_ID" NUMBER NOT NULL ENABLE, 
	"DOSAGE" VARCHAR2(50) NOT NULL ENABLE, 
	"FREQUENCY" VARCHAR2(50) NOT NULL ENABLE, 
	"DURATION_DAYS" NUMBER NOT NULL ENABLE, 
	"INSTRUCTIONS" VARCHAR2(200), 
	 PRIMARY KEY ("PRESCRIPTION_ITEM_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "ROOMS" 
   (	"ROOM_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ROOM_NO" VARCHAR2(10) NOT NULL ENABLE, 
	"ROOM_TYPE" VARCHAR2(20) NOT NULL ENABLE, 
	"DAILY_RATE" NUMBER(8,2) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(15) NOT NULL ENABLE, 
	 CHECK (ROOM_TYPE IN ('General', 'Private', 'ICU')) ENABLE, 
	 CHECK (STATUS IN ('Available', 'Occupied', 'Maintenance')) ENABLE, 
	 PRIMARY KEY ("ROOM_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("ROOM_NO")
  USING INDEX  ENABLE
   ) ;
   
     CREATE TABLE "ADMISSIONS" 
   (     "ADMISSION_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
        "PATIENT_ID" NUMBER NOT NULL ENABLE, 
        "DOCTOR_ID" NUMBER NOT NULL ENABLE, 
        "ROOM_ID" NUMBER NOT NULL ENABLE, 
        "ADMISSION_DATE" DATE NOT NULL ENABLE, 
        "DISCHARGE_DATE" DATE, 
        "ADMISSION_REASON" VARCHAR2(300) NOT NULL ENABLE, 
        "STATUS" VARCHAR2(15) NOT NULL ENABLE, 
         CHECK (STATUS IN ('Admitted', 'Discharged')) ENABLE, 
         PRIMARY KEY ("ADMISSION_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "ADMISSIONS" ADD CONSTRAINT "FK_ADMISSION_PATIENT" FOREIGN KEY ("PATIENT_ID")
          REFERENCES "PATIENTS" ("PATIENT_ID") ENABLE;
  ALTER TABLE "ADMISSIONS" ADD CONSTRAINT "FK_ADMISSION_DOCTOR" FOREIGN KEY ("DOCTOR_ID")
          REFERENCES "DOCTORS" ("DOCTOR_ID") ENABLE;
  ALTER TABLE "ADMISSIONS" ADD CONSTRAINT "FK_ADMISSION_ROOM" FOREIGN KEY ("ROOM_ID")
          REFERENCES "ROOMS" ("ROOM_ID") ENABLE;


  ALTER TABLE "APPOINTMENTS" ADD CONSTRAINT "FK_APPT_PATIENT" FOREIGN KEY ("PATIENT_ID")
	  REFERENCES "PATIENTS" ("PATIENT_ID") ENABLE;
  ALTER TABLE "APPOINTMENTS" ADD CONSTRAINT "FK_APPT_DOCTOR" FOREIGN KEY ("DOCTOR_ID")
	  REFERENCES "DOCTORS" ("DOCTOR_ID") ENABLE;
  ALTER TABLE "APPOINTMENTS" ADD CONSTRAINT "FK_APPT_STATUS" FOREIGN KEY ("STATUS_ID")
	  REFERENCES "APPOINTMENT_STATUSES" ("STATUS_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_APPOINTMENTS_CREATED_AT" 
BEFORE INSERT ON APPOINTMENTS
FOR EACH ROW
BEGIN
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSDATE;
    END IF;
END;
/
ALTER TRIGGER "TRG_APPOINTMENTS_CREATED_AT" ENABLE;

  ALTER TABLE "DOCTORS" ADD CONSTRAINT "FK_DOCTORS_DEPARTMENT" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "DEPARTMENTS" ("DEPARTMENT_ID") ENABLE;
  ALTER TABLE "DOCTORS" ADD CONSTRAINT "FK_DOCTORS_SPECIALTY" FOREIGN KEY ("SPECIALTY_ID")
	  REFERENCES "DOCTOR_SPECIALTIES" ("SPECIALTY_ID") ENABLE;

  ALTER TABLE "MEDICINES" ADD CONSTRAINT "FK_MEDICINES_CATEGORY" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "MEDICINE_CATEGORIES" ("CATEGORY_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_PATIENTS_CREATED_AT" 
BEFORE INSERT ON PATIENTS
FOR EACH ROW
BEGIN
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSDATE;
    END IF;
END;
/
ALTER TRIGGER "TRG_PATIENTS_CREATED_AT" ENABLE;

  ALTER TABLE "PATIENT_VISITS" ADD CONSTRAINT "FK_VISIT_APPOINTMENT" FOREIGN KEY ("APPOINTMENT_ID")
	  REFERENCES "APPOINTMENTS" ("APPOINTMENT_ID") ENABLE;
  ALTER TABLE "PATIENT_VISITS" ADD CONSTRAINT "FK_VISIT_PATIENT" FOREIGN KEY ("PATIENT_ID")
	  REFERENCES "PATIENTS" ("PATIENT_ID") ENABLE;
  ALTER TABLE "PATIENT_VISITS" ADD CONSTRAINT "FK_VISIT_DOCTOR" FOREIGN KEY ("DOCTOR_ID")
	  REFERENCES "DOCTORS" ("DOCTOR_ID") ENABLE;

  ALTER TABLE "PRESCRIPTIONS" ADD CONSTRAINT "FK_PRESC_VISIT" FOREIGN KEY ("VISIT_ID")
	  REFERENCES "PATIENT_VISITS" ("VISIT_ID") ENABLE;
  ALTER TABLE "PRESCRIPTIONS" ADD CONSTRAINT "FK_PRESC_PATIENT" FOREIGN KEY ("PATIENT_ID")
	  REFERENCES "PATIENTS" ("PATIENT_ID") ENABLE;
  ALTER TABLE "PRESCRIPTIONS" ADD CONSTRAINT "FK_PRESC_DOCTOR" FOREIGN KEY ("DOCTOR_ID")
	  REFERENCES "DOCTORS" ("DOCTOR_ID") ENABLE;

  ALTER TABLE "PRESCRIPTION_ITEMS" ADD CONSTRAINT "FK_ITEM_PRESCRIPTION" FOREIGN KEY ("PRESCRIPTION_ID")
	  REFERENCES "PRESCRIPTIONS" ("PRESCRIPTION_ID") ENABLE;
  ALTER TABLE "PRESCRIPTION_ITEMS" ADD CONSTRAINT "FK_ITEM_MEDICINE" FOREIGN KEY ("MEDICINE_ID")
	  REFERENCES "MEDICINES" ("MEDICINE_ID") ENABLE;

























































create or replace TRIGGER TRG_APPOINTMENTS_CREATED_AT
BEFORE INSERT ON APPOINTMENTS
FOR EACH ROW
BEGIN
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSDATE;
    END IF;
END;
/
create or replace TRIGGER TRG_PATIENTS_CREATED_AT
BEFORE INSERT ON PATIENTS
FOR EACH ROW
BEGIN
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSDATE;
    END IF;
END;
/

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_APPOINTMENTS_CREATED_AT" 
BEFORE INSERT ON APPOINTMENTS
FOR EACH ROW
BEGIN
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSDATE;
    END IF;
END;
/
ALTER TRIGGER "TRG_APPOINTMENTS_CREATED_AT" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_PATIENTS_CREATED_AT" 
BEFORE INSERT ON PATIENTS
FOR EACH ROW
BEGIN
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSDATE;
    END IF;
END;
/
ALTER TRIGGER "TRG_PATIENTS_CREATED_AT" ENABLE;
















  CREATE UNIQUE INDEX "SYS_C0014101" ON "APPOINTMENTS" ("APPOINTMENT_ID") 
  ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_APPOINTMENTS_CREATED_AT" 
BEFORE INSERT ON APPOINTMENTS
FOR EACH ROW
BEGIN
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSDATE;
    END IF;
END;
/
ALTER TRIGGER "TRG_APPOINTMENTS_CREATED_AT" ENABLE;

  CREATE UNIQUE INDEX "SYS_C0014061" ON "APPOINTMENT_STATUSES" ("STATUS_ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C0014047" ON "DEPARTMENTS" ("DEPARTMENT_ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C0014081" ON "DOCTORS" ("DOCTOR_ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C0014052" ON "DOCTOR_SPECIALTIES" ("SPECIALTY_ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C0014092" ON "MEDICINES" ("MEDICINE_ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C0014057" ON "MEDICINE_CATEGORIES" ("CATEGORY_ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C0014072" ON "PATIENTS" ("CIVIL_ID") 
  ;
  CREATE UNIQUE INDEX "SYS_C0014071" ON "PATIENTS" ("PATIENT_ID") 
  ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_PATIENTS_CREATED_AT" 
BEFORE INSERT ON PATIENTS
FOR EACH ROW
BEGIN
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSDATE;
    END IF;
END;
/
ALTER TRIGGER "TRG_PATIENTS_CREATED_AT" ENABLE;

  CREATE UNIQUE INDEX "SYS_C0014110" ON "PATIENT_VISITS" ("VISIT_ID") 
  ;

  CREATE UNIQUE INDEX "UQ_PRESCRIPTIONS_VISIT_ID" ON "PRESCRIPTIONS" ("VISIT_ID") 
  ;
  CREATE UNIQUE INDEX "SYS_C0014119" ON "PRESCRIPTIONS" ("PRESCRIPTION_ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C0014129" ON "PRESCRIPTION_ITEMS" ("PRESCRIPTION_ITEM_ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C0014139" ON "ROOMS" ("ROOM_ID") 
  ;
  CREATE UNIQUE INDEX "SYS_C0014140" ON "ROOMS" ("ROOM_NO") 
  ;



























