
-- Traffic signals table


CREATE TABLE traffic_signals (
    signal_id NUMBER
    GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,

    signal_name VARCHAR2(100) NOT NULL,

    state VARCHAR2(10) DEFAULT 'RED' NOT NULL
    CONSTRAINT ck_signal_state
    CHECK (state IN ('RED', 'YELLOW', 'GREEN')),

    last_changed_at TIMESTAMP WITH TIME ZONE
    DEFAULT (SYSTIMESTAMP AT TIME ZONE 'Asia/Muscat')
    NOT NULL
);


-- Check one signal and advance it when enough time passed

CREATE OR REPLACE PROCEDURE check_and_advance_signal (
    p_signal_id IN traffic_signals.signal_id%TYPE
)
AS
    PRAGMA AUTONOMOUS_TRANSACTION;

    v_state           traffic_signals.state%TYPE;
    v_last_changed_at traffic_signals.last_changed_at%TYPE;
    v_now             traffic_signals.last_changed_at%TYPE;
BEGIN
    v_now := SYSTIMESTAMP AT TIME ZONE 'Asia/Muscat';

SELECT state, last_changed_at
INTO v_state, v_last_changed_at
FROM traffic_signals
WHERE signal_id = p_signal_id
    FOR UPDATE;

IF v_state = 'RED'
       AND v_now >= v_last_changed_at + INTERVAL '10' SECOND
    THEN
UPDATE traffic_signals
SET state = 'YELLOW',
    last_changed_at = v_now
WHERE signal_id = p_signal_id;

ELSIF v_state = 'YELLOW'
          AND v_now >= v_last_changed_at + INTERVAL '5' SECOND
    THEN
UPDATE traffic_signals
SET state = 'GREEN',
    last_changed_at = v_now
WHERE signal_id = p_signal_id;

ELSIF v_state = 'GREEN'
          AND v_now >= v_last_changed_at + INTERVAL '10' SECOND
    THEN
UPDATE traffic_signals
SET state = 'RED',
    last_changed_at = v_now
WHERE signal_id = p_signal_id;
END IF;

COMMIT;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        ROLLBACK;

WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/


-- Create an individual Scheduler job for one signal


CREATE OR REPLACE PROCEDURE start_signal_watch (
    p_signal_id IN traffic_signals.signal_id%TYPE
)
AS
    PRAGMA AUTONOMOUS_TRANSACTION;

    v_job_name VARCHAR2(128);
BEGIN
    v_job_name := 'STATE_CHANGE_' || TO_CHAR(p_signal_id);

    DBMS_SCHEDULER.CREATE_JOB(
        job_name            => v_job_name,
        job_type            => 'STORED_PROCEDURE',
        job_action          => 'CHECK_AND_ADVANCE_SIGNAL',
        number_of_arguments => 1,
        start_date          => SYSTIMESTAMP,
        repeat_interval     => 'FREQ=SECONDLY;INTERVAL=1',
        enabled             => FALSE,
        auto_drop           => FALSE,
        comments            => 'Cycles traffic signal '
                               || TO_CHAR(p_signal_id)
    );

    DBMS_SCHEDULER.SET_JOB_ARGUMENT_VALUE(
        job_name          => v_job_name,
        argument_position => 1,
        argument_value    => TO_CHAR(p_signal_id)
    );

    DBMS_SCHEDULER.ENABLE(
        name => v_job_name
    );

COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/


-- Automatically start a signal after insertion


CREATE OR REPLACE TRIGGER trg_traffic_signal_insert
AFTER INSERT ON traffic_signals
FOR EACH ROW
BEGIN
    start_signal_watch(
        p_signal_id => :NEW.signal_id
    );
END;
/


-- Stop one signal without affecting the others


CREATE OR REPLACE PROCEDURE stop_signal_watch (
    p_signal_id IN traffic_signals.signal_id%TYPE
)
AS
    PRAGMA AUTONOMOUS_TRANSACTION;

    v_job_name VARCHAR2(128);
BEGIN
    v_job_name := 'STATE_CHANGE_' || TO_CHAR(p_signal_id);

    DBMS_SCHEDULER.DISABLE(
        name  => v_job_name,
        force => TRUE
    );

COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/
