CREATE TABLE traffic_signals (
                                 signal_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 signal_name     VARCHAR2(100) NOT NULL,
                                 state           VARCHAR2(10) DEFAULT 'RED' NOT NULL
                  CONSTRAINT ck_signal_state CHECK (state IN ('RED','YELLOW','GREEN')),
                                 last_changed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);


--update procedure
CREATE OR REPLACE PROCEDURE check_and_update_signal_status ( p_signal_id IN NUMBER)
AS
  v_state             VARCHAR2(10);
  v_last_changed_at   TIMESTAMP;
  v_next_state        VARCHAR2(10);
  v_required_seconds  NUMBER;

BEGIN
    DBMS_OUTPUT.PUT_LINE('Checking and Updating Signal Status for Signal with ID: ' || p_signal_id );
SELECT state, last_changed_at INTO v_state, v_last_changed_at FROM traffic_signals WHERE signal_id = p_signal_id;

IF v_state = 'RED' THEN
        v_next_state := 'YELLOW'; v_required_seconds := 10;
    ELSIF v_state = 'YELLOW' THEN
        v_next_state := 'GREEN';  v_required_seconds := 5;
ELSE
        v_next_state := 'RED'; v_required_seconds := 10;
END IF;

    IF SYSTIMESTAMP >= v_last_changed_at + NUMTODSINTERVAL(v_required_seconds, 'SECOND') THEN
UPDATE traffic_signals SET state = v_next_state, last_changed_at = SYSTIMESTAMP WHERE signal_id = p_signal_id;
COMMIT;
END IF;
END check_and_update_signal_status;


--start job procedure
CREATE OR REPLACE PROCEDURE start_signal_watch ( p_signal_id IN NUMBER) AS
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  DBMS_SCHEDULER.CREATE_JOB(
    job_name => 'SIG_WATCH_' || p_signal_id,
    job_type => 'PLSQL_BLOCK',
    job_action => 'BEGIN check_and_update_signal_status(' || p_signal_id ||  '); END;',
    start_date => SYSTIMESTAMP + INTERVAL '5' SECOND,
    repeat_interval => 'FREQ=SECONDLY;INTERVAL=5',
    enabled => TRUE
  );
COMMIT;
END start_signal_watch;
/


CREATE OR REPLACE TRIGGER handle_traffic_signal_insert_event
AFTER INSERT ON traffic_signals
FOR EACH ROW
BEGIN
  start_signal_watch(:NEW.signal_id);
END handle_traffic_signal_insert_event;
/



insert into traffic_signals (signal_name) values ('Al-Ansab Lulu signal');
