 ----create table----
 CREATE TABLE traffic_signals (
  signal_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  signal_name     VARCHAR2(50)  NOT NULL,
  signal_state    VARCHAR2(10)  DEFAULT 'RED' NOT NULL
                  CONSTRAINT ck_signal_state CHECK (signal_state IN ('RED','YELLOW','GREEN')),
  last_changed_at TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);
----to cheke if it is create ---
SELECT * FROM traffic_signals;
----procedure----
CREATE OR REPLACE PROCEDURE check_and_update_signal_status (p_signal_id IN NUMBER)
AS
BEGIN
  DBMS_OUTPUT.PUT_LINE('To Do');
END check_and_update_signal_status;
/
-----read the signal-----
CREATE OR REPLACE PROCEDURE check_and_update_signal_status (p_signal_id IN NUMBER)
AS
  v_state            traffic_signals.signal_state%TYPE;
  v_last_changed_at  traffic_signals.last_changed_at%TYPE;
BEGIN
  SELECT signal_state, last_changed_at
    INTO v_state, v_last_changed_at
    FROM traffic_signals
   WHERE signal_id = p_signal_id;

  DBMS_OUTPUT.PUT_LINE('v_state is ' || v_state || ' , v_last_changed_at is ' || v_last_changed_at);
END check_and_update_signal_status;
/
---test---
INSERT INTO traffic_signals (signal_name) VALUES ('Ghala Industrial Signal');
COMMIT;
--procedure--
BEGIN
  check_and_update_signal_status(1);
END;
/
---4---
CREATE OR REPLACE PROCEDURE check_and_update_signal_status (p_signal_id IN NUMBER)
AS
  v_state            VARCHAR2(10);
  v_last_changed_at  TIMESTAMP;
  v_next_state       VARCHAR2(10);
  v_required_seconds NUMBER;
BEGIN
  SELECT signal_state, last_changed_at
    INTO v_state, v_last_changed_at
    FROM traffic_signals
   WHERE signal_id = p_signal_id;

  IF v_state = 'RED' THEN
    v_next_state := 'YELLOW'; v_required_seconds := 10;
  ELSIF v_state = 'YELLOW' THEN
    v_next_state := 'GREEN';  v_required_seconds := 5;
  ELSE -- GREEN
    v_next_state := 'RED';    v_required_seconds := 10;
  END IF;

  IF SYSTIMESTAMP >= v_last_changed_at + NUMTODSINTERVAL(v_required_seconds, 'SECOND') THEN
    UPDATE traffic_signals
       SET signal_state    = v_next_state,
           last_changed_at = SYSTIMESTAMP
     WHERE signal_id = p_signal_id;
    COMMIT;
  END IF;
END check_and_update_signal_status;
/
----test after 10 minuts RED to YELLOW----
UPDATE traffic_signals SET last_changed_at = SYSTIMESTAMP - INTERVAL '15' SECOND WHERE signal_id = 1;
COMMIT;

BEGIN
  check_and_update_signal_status(1);
END;
/

SELECT signal_id, signal_state, last_changed_at FROM traffic_signals WHERE signal_id = 1;
--green test light--
UPDATE traffic_signals SET last_changed_at = SYSTIMESTAMP - INTERVAL '10' SECOND WHERE signal_id = 1;
COMMIT;

BEGIN
  check_and_update_signal_status(1);
END;
/

SELECT signal_state, last_changed_at FROM traffic_signals WHERE signal_id = 1; 
---green to red test light---
UPDATE traffic_signals SET last_changed_at = SYSTIMESTAMP - INTERVAL '15' SECOND WHERE signal_id = 1;
COMMIT;

BEGIN
  check_and_update_signal_status(1);
END;
/

SELECT signal_state, last_changed_at FROM traffic_signals WHERE signal_id = 1;

----5:start_signal_watch----
CREATE OR REPLACE PROCEDURE start_signal_watch (p_signal_id IN NUMBER)
AS
BEGIN
  DBMS_OUTPUT.PUT_LINE('To Do');
END start_signal_watch;
/
----6:DBMS_SCHEDULER.CREATE_JOB----
CREATE OR REPLACE PROCEDURE start_signal_watch (p_signal_id IN NUMBER)
AS
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  DBMS_OUTPUT.PUT_LINE('To Do');
  DBMS_SCHEDULER.CREATE_JOB(
    job_name        => 'sig_watch_' || p_signal_id,
    job_type        => 'PLSQL_BLOCK',
    job_action      => 'BEGIN check_and_update_signal_status(' || p_signal_id || '); END;',
    repeat_interval => 'FREQ=SECONDLY; INTERVAL=5',
    start_date      => SYSTIMESTAMP,
    enabled         => TRUE
  );
  COMMIT;
END start_signal_watch;
/
----6:test trigger----
BEGIN
  start_signal_watch(1);
END;
/

SELECT job_name, state, next_run_date FROM user_scheduler_jobs WHERE job_name LIKE 'SIG_WATCH_%';

---6:c. test the job 5-10 second---
SELECT signal_state, last_changed_at FROM traffic_signals WHERE signal_id = 1;

----7:a way to stop one specific signal's cycle without affecting any other signal----
CREATE OR REPLACE PROCEDURE stop_signal_watch (p_signal_id IN NUMBER)
AS
BEGIN
  DBMS_SCHEDULER.STOP_JOB('sig_watch_' || p_signal_id, force => TRUE);
  DBMS_SCHEDULER.DROP_JOB('sig_watch_' || p_signal_id, force => TRUE);
END stop_signal_watch;
/
----test step 7----
BEGIN
  stop_signal_watch(1);
END;
/

SELECT job_name FROM user_scheduler_jobs WHERE job_name LIKE 'SIG_WATCH_%';

---try to check the error---
BEGIN
  DBMS_SCHEDULER.DROP_JOB('SIG_WATCH_1');
END;
/
--7:stop_signal_watch--
CREATE OR REPLACE PROCEDURE stop_signal_watch (p_signal_id IN NUMBER)
AS
BEGIN
  BEGIN
    DBMS_SCHEDULER.STOP_JOB('sig_watch_' || p_signal_id);
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -27366 THEN
        RAISE;
      END IF;
  END;
  DBMS_SCHEDULER.DROP_JOB('sig_watch_' || p_signal_id);
END stop_signal_watch;
/
---test 7 by delet job ---
BEGIN
  start_signal_watch(1);
END;
/
---7 tst stop---
BEGIN
  stop_signal_watch(1);
END;
/

SELECT job_name FROM user_scheduler_jobs WHERE job_name LIKE 'SIG_WATCH_%';

----step 8:trigger----
CREATE OR REPLACE TRIGGER handle_traffic_signal_insert_event
AFTER INSERT ON traffic_signals
FOR EACH ROW
BEGIN
  start_signal_watch(:NEW.signal_id);
END handle_traffic_signal_insert_event;
/
---insert frist i check the step 6 :procedure---
INSERT INTO traffic_signals (signal_name) VALUES ('Seeb Signal Test');
COMMIT;
----test agine---
SELECT signal_id, signal_name, signal_state, last_changed_at FROM traffic_signals WHERE signal_name = 'Seeb Signal Test';
----test the light work spret----
INSERT INTO traffic_signals (signal_name) VALUES ('Al Khuwair Signal Test');
COMMIT;
----test the two (alkhuwair and seeb)----
SELECT signal_id, signal_name, signal_state, last_changed_at 
FROM traffic_signals 
WHERE signal_id >= 3
ORDER BY signal_id;