CREATE TABLE traffic_signals (
    signal_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_name VARCHAR2(100) NOT NULL,
    state VARCHAR2(10) DEFAULT 'RED' NOT NULL
        CONSTRAINT ck_signal_state CHECK (state IN ('RED', 'YELLOW', 'GREEN')),
    last_changed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);


CREATE OR REPLACE PROCEDURE check_and_update_signal_status (
    p_signal_id IN NUMBER
) IS
    v_state traffic_signals.state%TYPE;
    v_last_changed_at traffic_signals.last_changed_at%TYPE;
    v_next_state traffic_signals.state%TYPE;
    v_required_secs NUMBER;
BEGIN
    SELECT state, last_changed_at
    INTO v_state, v_last_changed_at
    FROM traffic_signals
    WHERE signal_id = p_signal_id;

    IF v_state = 'RED' THEN
        v_next_state := 'YELLOW';
        v_required_secs := 10;
    ELSIF v_state = 'YELLOW' THEN
        v_next_state := 'GREEN';
        v_required_secs := 5;
    ELSIF v_state = 'GREEN' THEN
        v_next_state := 'RED';
        v_required_secs := 10;
    END IF;

    IF SYSTIMESTAMP >= v_last_changed_at
        + NUMTODSINTERVAL(v_required_secs, 'SECOND') THEN
        UPDATE traffic_signals
        SET state = v_next_state,
            last_changed_at = SYSTIMESTAMP
        WHERE signal_id = p_signal_id;

        COMMIT;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        NULL;
END check_and_update_signal_status;
/
CREATE OR REPLACE PROCEDURE start_signal_watch (
    p_signal_id IN NUMBER
) IS
    PRAGMA AUTONOMOUS_TRANSACTION;
    v_job_name VARCHAR2(128);
BEGIN
    v_job_name := 'SIGNAL_WATCH_' || p_signal_id;

    DBMS_SCHEDULER.CREATE_JOB(
        job_name => v_job_name,
        job_type => 'STORED_PROCEDURE',
        job_action => 'CHECK_AND_UPDATE_SIGNAL_STATUS',
        number_of_arguments => 1,
        start_date => SYSTIMESTAMP + NUMTODSINTERVAL(2, 'SECOND'),
        repeat_interval => 'FREQ=SECONDLY;INTERVAL=1',
        enabled => FALSE,
        auto_drop => FALSE,
        comments => 'Cycles traffic signal ' || p_signal_id
    );

    DBMS_SCHEDULER.SET_JOB_ARGUMENT_VALUE(
        job_name => v_job_name,
        argument_position => 1,
        argument_value => TO_CHAR(p_signal_id)
    );

    DBMS_SCHEDULER.ENABLE(v_job_name);

    COMMIT;
END start_signal_watch;
/

CREATE OR REPLACE TRIGGER trg_traffic_signal_after_insert
AFTER INSERT ON traffic_signals
FOR EACH ROW
BEGIN
    start_signal_watch(:NEW.signal_id);
END;
/

CREATE OR REPLACE PROCEDURE stop_signal_watch (
    p_signal_id IN NUMBER
) IS
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    DBMS_SCHEDULER.DROP_JOB(
        job_name => 'SIGNAL_WATCH_' || p_signal_id,
        force => TRUE
    );

    COMMIT;
END stop_signal_watch;
/
