

SELECT USER FROM DUAL;

--1.create table 
CREATE TABLE traffic_signals (
  signal_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  signal_name     VARCHAR2(100) NOT NULL,
  state           VARCHAR2(10) DEFAULT 'RED' NOT NULL
                  CONSTRAINT ck_signal_state CHECK (state IN ('RED','YELLOW','GREEN')),
  last_changed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

SELECT table_name
FROM user_tables
WHERE table_name = 'TRAFFIC_SIGNALS';

SELECT *
FROM user_sys_privs
WHERE privilege LIKE '%JOB%';

SELECT USER FROM dual;



------------------------------------------------
--2.Create the procedure:
CREATE OR REPLACE PROCEDURE process_traffic_signal (
    p_signal_id IN NUMBER
)
IS
    PRAGMA AUTONOMOUS_TRANSACTION;

    v_state        traffic_signals.state%TYPE;
    v_last_changed traffic_signals.last_changed_at%TYPE;
    v_elapsed      NUMBER;
    v_new_state    traffic_signals.state%TYPE;

BEGIN

    SELECT state, last_changed_at
    INTO v_state, v_last_changed
    FROM traffic_signals
    WHERE signal_id = p_signal_id
    FOR UPDATE;


    -- Calculate elapsed time in seconds
    v_elapsed :=
          EXTRACT(DAY    FROM (SYSTIMESTAMP - v_last_changed)) * 86400
        + EXTRACT(HOUR   FROM (SYSTIMESTAMP - v_last_changed)) * 3600
        + EXTRACT(MINUTE FROM (SYSTIMESTAMP - v_last_changed)) * 60
        + EXTRACT(SECOND FROM (SYSTIMESTAMP - v_last_changed));


    -- RED → YELLOW after 10 seconds
    IF v_state = 'RED' AND v_elapsed >= 10 THEN

        v_new_state := 'YELLOW';


    -- YELLOW → GREEN after 5 seconds
    ELSIF v_state = 'YELLOW' AND v_elapsed >= 5 THEN

        v_new_state := 'GREEN';


    -- GREEN → RED after 10 seconds
    ELSIF v_state = 'GREEN' AND v_elapsed >= 10 THEN

        v_new_state := 'RED';


    ELSE

        v_new_state := NULL;

    END IF;


    -- Update the state if a transition is required
    IF v_new_state IS NOT NULL THEN

        UPDATE traffic_signals
        SET state = v_new_state,
            last_changed_at = SYSTIMESTAMP
        WHERE signal_id = p_signal_id;

    END IF;


    COMMIT;


EXCEPTION

    WHEN NO_DATA_FOUND THEN
        COMMIT;

    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;

END;
/

--------to check :

SELECT object_name,
       object_type,
       status
FROM user_objects
WHERE object_name = 'PROCESS_TRAFFIC_SIGNAL';


----.test 
INSERT INTO traffic_signals (signal_name)
VALUES ('Test Intersection');

COMMIT;

SELECT
    signal_id,
    signal_name,
    state,
    last_changed_at
FROM traffic_signals;



--------you can manually test the procedure after waiting 10 seconds:
BEGIN
    process_traffic_signal(1);
END;
/


SELECT
    signal_id,
    signal_name,
    state,
    last_changed_at
FROM traffic_signals;

------wait 5 seconds and run:

BEGIN
    process_traffic_signal(1);
END;
/
---------------------------------------------
--3.Create START_TRAFFIC_SIGNAL
--purpose of this procedure is:
--When the trigger tells it that a new signal was inserted, it creates a Scheduler job dedicated to that signal.

--3.1 Create the procedure
CREATE OR REPLACE PROCEDURE start_traffic_signal (
    p_signal_id IN NUMBER
)
IS
    PRAGMA AUTONOMOUS_TRANSACTION;

    v_job_name VARCHAR2(100);

BEGIN

    -- Create a predictable job name for this signal
    v_job_name := 'TRAFFIC_SIGNAL_JOB_' || p_signal_id;


    -- Create Scheduler job
    DBMS_SCHEDULER.CREATE_JOB (
        job_name        => v_job_name,

        job_type        => 'PLSQL_BLOCK',

        job_action      =>
            'BEGIN process_traffic_signal(' || p_signal_id || '); END;',

        start_date      => SYSTIMESTAMP,

        repeat_interval => 'FREQ=SECONDLY;INTERVAL=1',

        enabled         => TRUE,

        auto_drop       => FALSE
    );


    COMMIT;


EXCEPTION

    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;

END;
/


SELECT object_name,
       object_type,
       status
FROM user_objects
WHERE object_name = 'START_TRAFFIC_SIGNAL';

BEGIN
    start_traffic_signal(1);
END;
/

GRANT CREATE JOB TO SYSTEM;

-------------------------------------------------------
SELECT privilege
FROM user_sys_privs
WHERE privilege = 'CREATE JOB';

----------------------------------------------------
---check the Scheduler job:
SELECT
    job_name,
    enabled,
    state,
    repeat_interval
FROM user_scheduler_jobs
WHERE job_name = 'TRAFFIC_SIGNAL_JOB_1';


----------------------
---first check:
SELECT job_name, enabled, state
FROM user_scheduler_jobs
WHERE job_name = 'TRAFFIC_SIGNAL_JOB_1';

----------------------
--4.Create the AFTER INSERT Trigger
DESC TRAFFIC_SIGNALS;


--Create the trigger
CREATE OR REPLACE TRIGGER TRG_TRAFFIC_SIGNAL_AI
AFTER INSERT ON TRAFFIC_SIGNALS
FOR EACH ROW
BEGIN
    START_TRAFFIC_SIGNAL(:NEW.SIGNAL_ID);
END;
/

--Check whether it compiled successfully
SELECT trigger_name,
       status
FROM user_triggers
WHERE trigger_name = 'TRG_TRAFFIC_SIGNAL_AI';


INSERT INTO TRAFFIC_SIGNALS
    (SIGNAL_ID, SIGNAL_NAME, STATE, LAST_CHANGED_AT)
VALUES
    (2, 'Test Intersection 2', 'RED', SYSTIMESTAMP);

COMMIT;


SELECT *
FROM TRAFFIC_SIGNALS
ORDER BY SIGNAL_ID;

SELECT job_name,
       enabled,
       state
FROM user_scheduler_jobs
ORDER BY job_name;
-------------------------------
------------------------------------
---------------------------------
UPDATE TRAFFIC_SIGNALS
SET SIGNAL_NAME = 'Seeb'
WHERE SIGNAL_ID = 1;

UPDATE TRAFFIC_SIGNALS
SET SIGNAL_NAME = 'Al Khoudh'
WHERE SIGNAL_ID = 2;

COMMIT;

INSERT INTO TRAFFIC_SIGNALS (SIGNAL_ID, SIGNAL_NAME, STATE, LAST_CHANGED_AT)
VALUES (3, 'Al Hail', 'RED', SYSTIMESTAMP);

COMMIT;

SELECT * FROM TRAFFIC_SIGNALS ORDER BY SIGNAL_ID;
-------------------------------------------------------
-----check the Scheduler
SELECT job_name,
       enabled,
       state
FROM user_scheduler_jobs
ORDER BY job_name;


-------------------------------------------------------











