SET SERVEROUTPUT ON;

--------------------- CREATE TABLE ---------------------
CREATE TABLE traffic_signals (
    signal_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_name VARCHAR2(100) NOT NULL,
    state VARCHAR2(10) DEFAULT 'RED' NOT NULL,
    CONSTRAINT ck_signal_state CHECK (state IN ('RED', 'YELLOW', 'GREEN')),
    last_changed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

--------------------- PROCEDURE: UPDATE SIGNAL STATE ---------------------
CREATE OR REPLACE PROCEDURE update_traffic_signal (p_signal_id IN NUMBER)
AS
    v_state VARCHAR2(10);
    v_last_changed_at TIMESTAMP;
    v_next_state VARCHAR2(10);
    v_required_seconds NUMBER;
BEGIN
    SELECT state, last_changed_at
    INTO v_state, v_last_changed_at
    FROM traffic_signals
    WHERE signal_id = p_signal_id;

    IF v_state = 'RED' THEN v_next_state := 'YELLOW'; v_required_seconds := 10;
    ELSIF v_state = 'YELLOW' THEN v_next_state := 'GREEN'; v_required_seconds := 5;
    ELSIF v_state = 'GREEN' THEN v_next_state := 'RED'; v_required_seconds := 10;
    END IF;
    
    IF SYSTIMESTAMP >= v_last_changed_at + NUMTODSINTERVAL(v_required_seconds, 'SECOND')
    THEN
        UPDATE traffic_signals
        SET state = v_next_state, last_changed_at = SYSTIMESTAMP
        WHERE signal_id = p_signal_id;
        
        DBMS_OUTPUT.PUT_LINE('Signal ' || p_signal_id || ' changed from ' || v_state || ' to ' || v_next_state);
        
        COMMIT;
    END IF;
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;    
END;
/

--------------------- PROCEDURE: CREATE SCHEDULER JOB ---------------------
CREATE OR REPLACE PROCEDURE start_traffic_signal (p_signal_id IN NUMBER)
AS
    PRAGMA AUTONOMOUS_TRANSACTION; -- allows a PL/SQL block to run and commit independently from the main transaction.
    v_job_name VARCHAR2(100);
BEGIN
    v_job_name := 'TRAFFIC_SIGNAL_' || p_signal_id;
    
    DBMS_OUTPUT.PUT_LINE('Creating job: ' || v_job_name);
    
    DBMS_SCHEDULER.CREATE_JOB(
        job_name        => v_job_name,
        job_type        => 'PLSQL_BLOCK', -- means the scheduler job will execute a PL/SQL block
        job_action      =>
            'BEGIN
                update_traffic_signal(' || p_signal_id || ');
             END;',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=SECONDLY;INTERVAL=1',
        enabled         => TRUE, -- Start the job immediately
        auto_drop       => FALSE -- Keep the job after execution; do not delete it automatically
    );
    
    DBMS_OUTPUT.PUT_LINE('Job ' || v_job_name || ' created successfully.');
    
    COMMIT;
END;
/

--------------------- TRIGGER: START SIGNAL AUTOMATICALLY AFTER INSERT ---------------------
CREATE OR REPLACE TRIGGER trg_start_traffic_signal
AFTER INSERT ON traffic_signals
FOR EACH ROW
BEGIN
    start_traffic_signal(:NEW.signal_id);
END;
/

--------------------- PROCEDURE: STOP ONE SIGNAL ---------------------
CREATE OR REPLACE PROCEDURE stop_traffic_signal (p_signal_id IN NUMBER)
AS
    v_job_name VARCHAR2(100);
BEGIN
    v_job_name := 'TRAFFIC_SIGNAL_' || p_signal_id;
    DBMS_SCHEDULER.DISABLE(
        name  => v_job_name,
        force => TRUE
    );
    
    DBMS_OUTPUT.PUT_LINE('Job ' || v_job_name || ' stopped successfully.');
    
END;
/

-- ######################## Testing ########################
--------------------- INSERT SIGNAL A ---------------------
INSERT INTO traffic_signals (signal_name)
VALUES ('Signal A');
COMMIT;

--------------------- CHECK CURRENT STATE ---------------------
SELECT signal_id, signal_name, state, last_changed_at
FROM traffic_signals;

--------------------- INSERT SIGNAL B ---------------------
INSERT INTO traffic_signals (signal_name)
VALUES ('Signal B');
COMMIT;

--------------------- CHECK CURRENT STATE ---------------------
SELECT signal_id, signal_name, state, last_changed_at
FROM traffic_signals;

--------------------- CHECK SCHEDULER JOBS ---------------------
SELECT job_name, enabled, state, repeat_interval
FROM user_scheduler_jobs
WHERE job_name LIKE 'TRAFFIC_SIGNAL_%';

--------------------- STOP SIGNAL ---------------------
BEGIN
    stop_traffic_signal(1);
END;
/

--------------------- CHECK JOBS AFTER STOP ---------------------
SELECT job_name, enabled, state, repeat_interval
FROM user_scheduler_jobs
WHERE job_name LIKE 'TRAFFIC_SIGNAL_%';

--------------------- Check Job Run History ---------------------
SELECT job_name, status, actual_start_date, run_duration
FROM user_scheduler_job_run_details
WHERE job_name LIKE 'TRAFFIC_SIGNAL_%'
ORDER BY actual_start_date DESC;