CREATE TABLE departments (
    department_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    department_name VARCHAR2(100) NOT NULL,
    floor_no         VARCHAR2(10),
    status           VARCHAR2(20) DEFAULT 'Active' NOT NULL,
    CONSTRAINT pk_departments PRIMARY KEY (department_id),
    CONSTRAINT ck_dept_status CHECK (status IN ('Active', 'Inactive'))
);

CREATE TABLE doctor_specialties (
    specialty_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    specialty_name VARCHAR2(100) NOT NULL,
    status         VARCHAR2(20) DEFAULT 'Active' NOT NULL,
    CONSTRAINT pk_doctor_specialties PRIMARY KEY (specialty_id),
    CONSTRAINT ck_specialty_status CHECK (status IN ('Active', 'Inactive'))
);

CREATE TABLE medicine_categories (
    category_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    category_name VARCHAR2(100) NOT NULL,
    status        VARCHAR2(20) DEFAULT 'Active' NOT NULL,
    CONSTRAINT pk_medicine_categories PRIMARY KEY (category_id),
    CONSTRAINT ck_med_category_status CHECK (status IN ('Active', 'Inactive'))
);

CREATE TABLE appointment_statuses (
    status_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    status_name VARCHAR2(30) NOT NULL,
    CONSTRAINT pk_appointment_statuses PRIMARY KEY (status_id)
);

CREATE TABLE patients (
    patient_id             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    civil_id               VARCHAR2(20) NOT NULL,
    full_name              VARCHAR2(150) NOT NULL,
    gender                 VARCHAR2(10),
    date_of_birth          DATE,
    mobile_no              VARCHAR2(20) NOT NULL,
    email                  VARCHAR2(255),
    blood_group            VARCHAR2(3),
    address                VARCHAR2(500),
    emergency_contact_name VARCHAR2(150),
    emergency_contact_no   VARCHAR2(20),
    created_at             DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_patients PRIMARY KEY (patient_id),
    CONSTRAINT uq_patient_civil_id UNIQUE (civil_id),
    CONSTRAINT ck_patient_gender CHECK (gender IN ('Male', 'Female')),
    CONSTRAINT ck_patient_blood_group
        CHECK (blood_group IN ('A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'))
);

CREATE TABLE rooms (
    room_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    room_no    VARCHAR2(20) NOT NULL,
    room_type  VARCHAR2(20) NOT NULL,
    daily_rate NUMBER(10,2) NOT NULL,
    status     VARCHAR2(20) DEFAULT 'Available' NOT NULL,
    CONSTRAINT pk_rooms PRIMARY KEY (room_id),
    CONSTRAINT ck_room_type CHECK (room_type IN ('General', 'Private', 'ICU')),
    CONSTRAINT ck_room_status CHECK (status IN ('Available', 'Occupied', 'Maintenance'))
);

CREATE TABLE doctors (
    doctor_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    full_name        VARCHAR2(150) NOT NULL,
    department_id    NUMBER NOT NULL,
    specialty_id     NUMBER NOT NULL,
    mobile_no        VARCHAR2(20),
    email            VARCHAR2(255),
    consultation_fee NUMBER(10,2),
    status            VARCHAR2(20) DEFAULT 'Active' NOT NULL,
    CONSTRAINT pk_doctors PRIMARY KEY (doctor_id),
    CONSTRAINT fk_doc_department
        FOREIGN KEY (department_id) REFERENCES departments (department_id),
    CONSTRAINT fk_doc_specialty
        FOREIGN KEY (specialty_id) REFERENCES doctor_specialties (specialty_id),
    CONSTRAINT ck_doctor_status CHECK (status IN ('Active', 'Inactive'))
);

CREATE TABLE medicines (
    medicine_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    medicine_name VARCHAR2(150) NOT NULL,
    category_id   NUMBER NOT NULL,
    unit          VARCHAR2(50) NOT NULL,
    current_stock NUMBER(10,0) NOT NULL,
    reorder_level NUMBER(10,0) NOT NULL,
    status        VARCHAR2(20) DEFAULT 'Active' NOT NULL,
    CONSTRAINT pk_medicines PRIMARY KEY (medicine_id),
    CONSTRAINT fk_med_category
        FOREIGN KEY (category_id) REFERENCES medicine_categories (category_id),
    CONSTRAINT ck_med_current_stock CHECK (current_stock >= 0),
    CONSTRAINT ck_med_reorder_level CHECK (reorder_level >= 0),
    CONSTRAINT ck_medicine_status CHECK (status IN ('Active', 'Inactive'))
);

CREATE TABLE appointments (
    appointment_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    patient_id       NUMBER NOT NULL,
    doctor_id        NUMBER NOT NULL,
    appointment_date DATE NOT NULL,
    appointment_time VARCHAR2(5) NOT NULL,
    status_id        NUMBER NOT NULL,
    reason_for_visit VARCHAR2(500),
    created_at       DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_appointments PRIMARY KEY (appointment_id),
    CONSTRAINT fk_appt_patient
        FOREIGN KEY (patient_id) REFERENCES patients (patient_id),
    CONSTRAINT fk_appt_doctor
        FOREIGN KEY (doctor_id) REFERENCES doctors (doctor_id),
    CONSTRAINT fk_appt_status
        FOREIGN KEY (status_id) REFERENCES appointment_statuses (status_id)
);

CREATE TABLE patient_visits (
    visit_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    appointment_id NUMBER NOT NULL,
    patient_id     NUMBER NOT NULL,
    doctor_id      NUMBER NOT NULL,
    visit_date     DATE NOT NULL,
    symptoms       VARCHAR2(4000),
    diagnosis      VARCHAR2(4000),
    notes          VARCHAR2(4000),
    follow_up_date DATE,
    CONSTRAINT pk_patient_visits PRIMARY KEY (visit_id),
    CONSTRAINT uq_visit_appointment UNIQUE (appointment_id),
    CONSTRAINT fk_visit_appointment
        FOREIGN KEY (appointment_id) REFERENCES appointments (appointment_id),
    CONSTRAINT fk_visit_patient
        FOREIGN KEY (patient_id) REFERENCES patients (patient_id),
    CONSTRAINT fk_visit_doctor
        FOREIGN KEY (doctor_id) REFERENCES doctors (doctor_id)
);

CREATE TABLE prescriptions (
    prescription_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    visit_id          NUMBER NOT NULL,
    patient_id        NUMBER NOT NULL,
    doctor_id         NUMBER NOT NULL,
    prescription_date DATE NOT NULL,
    notes             VARCHAR2(4000),
    CONSTRAINT pk_prescriptions PRIMARY KEY (prescription_id),
    CONSTRAINT uq_rx_visit UNIQUE (visit_id),
    CONSTRAINT fk_rx_visit
        FOREIGN KEY (visit_id) REFERENCES patient_visits (visit_id),
    CONSTRAINT fk_rx_patient
        FOREIGN KEY (patient_id) REFERENCES patients (patient_id),
    CONSTRAINT fk_rx_doctor
        FOREIGN KEY (doctor_id) REFERENCES doctors (doctor_id)
);

CREATE TABLE prescription_items (
    prescription_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    prescription_id      NUMBER NOT NULL,
    medicine_id          NUMBER NOT NULL,
    dosage                VARCHAR2(50) NOT NULL,
    frequency             VARCHAR2(100) NOT NULL,
    duration_days         NUMBER(3,0) NOT NULL,
    instructions          VARCHAR2(500) NOT NULL,
    CONSTRAINT pk_prescription_items PRIMARY KEY (prescription_item_id),
    CONSTRAINT fk_rx_item_prescription
        FOREIGN KEY (prescription_id) REFERENCES prescriptions (prescription_id),
    CONSTRAINT fk_rx_item_medicine
        FOREIGN KEY (medicine_id) REFERENCES medicines (medicine_id),
    CONSTRAINT ck_rx_item_duration CHECK (duration_days > 0)
);

CREATE TABLE admissions (
    admission_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    patient_id       NUMBER NOT NULL,
    doctor_id        NUMBER NOT NULL,
    room_id          NUMBER NOT NULL,
    admission_date   DATE NOT NULL,
    discharge_date   DATE,
    admission_reason VARCHAR2(1000) NOT NULL,
    status           VARCHAR2(20) DEFAULT 'Admitted' NOT NULL,
    CONSTRAINT pk_admissions PRIMARY KEY (admission_id),
    CONSTRAINT fk_admission_patient
        FOREIGN KEY (patient_id) REFERENCES patients (patient_id),
    CONSTRAINT fk_admission_doctor
        FOREIGN KEY (doctor_id) REFERENCES doctors (doctor_id),
    CONSTRAINT fk_admission_room
        FOREIGN KEY (room_id) REFERENCES rooms (room_id),
    CONSTRAINT ck_admission_status CHECK (status IN ('Admitted', 'Discharged')),
    CONSTRAINT ck_admission_discharge
        CHECK (status <> 'Discharged' OR discharge_date IS NOT NULL)
);

CREATE INDEX idx_doc_department ON doctors (department_id);
CREATE INDEX idx_doc_specialty ON doctors (specialty_id);
CREATE INDEX idx_med_category ON medicines (category_id);
CREATE INDEX idx_appt_patient ON appointments (patient_id);
CREATE INDEX idx_appt_doctor ON appointments (doctor_id);
CREATE INDEX idx_appt_status ON appointments (status_id);
CREATE INDEX idx_visit_patient ON patient_visits (patient_id);
CREATE INDEX idx_visit_doctor ON patient_visits (doctor_id);
CREATE INDEX idx_rx_patient ON prescriptions (patient_id);
CREATE INDEX idx_rx_doctor ON prescriptions (doctor_id);
CREATE INDEX idx_rx_item_prescription ON prescription_items (prescription_id);
CREATE INDEX idx_rx_item_medicine ON prescription_items (medicine_id);
CREATE INDEX idx_admission_patient ON admissions (patient_id);
CREATE INDEX idx_admission_doctor ON admissions (doctor_id);
CREATE INDEX idx_admission_room ON admissions (room_id);
