--------------------------------------------------------------------------
-- SELF-DRIVING TRAFFIC SIGNAL
--
-- The idea:
--   Insert a signal -> it starts cycling on its own, forever:
--   RED (10s) -> YELLOW (5s) -> GREEN (10s) -> RED ...
--------------------------------------------------------------------------


--------------------------------------------------------------------------
-- STEP 0: Give permission to create scheduler jobs.
-- Run ONCE, logged in as SYS AS SYSDBA (not as SYSTEM).
--------------------------------------------------------------------------
-- GRANT CREATE JOB TO SYSTEM;

--------------------------------------------------------------------------
-- STEP 1: The table. It only stores facts: name, current color,
--         and when the color last changed.
--------------------------------------------------------------------------
CREATE TABLE traffic_signals (
                                 signal_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 signal_name     VARCHAR2(100) NOT NULL,
                                 state           VARCHAR2(10) DEFAULT 'RED' NOT NULL
                  CONSTRAINT ck_signal_state CHECK (state IN ('RED','YELLOW','GREEN')),
                                 last_changed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
/