--------------------------------------------------------------------------
-- SELF-DRIVING TRAFFIC SIGNAL
--
-- The idea:
--   Insert a signal -> it starts cycling on its own, forever:
--   RED (10s) -> YELLOW (5s) -> GREEN (10s) -> RED ...
--------------------------------------------------------------------------


--------------------------------------------------------------------------
-- STEP 0: Give permission to create scheduler jobs.
-- Run ONCE, logged in as SYS AS SYSDBA (not as SYSTEM).
--------------------------------------------------------------------------
-- GRANT CREATE JOB TO SYSTEM;

--------------------------------------------------------------------------
-- STEP 1: The table. It only stores facts: name, current color,
--         and when the color last changed.
--------------------------------------------------------------------------
CREATE TABLE traffic_signals (
                                 signal_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 signal_name     VARCHAR2(100) NOT NULL,
                                 state           VARCHAR2(10) DEFAULT 'RED' NOT NULL
                  CONSTRAINT ck_signal_state CHECK (state IN ('RED','YELLOW','GREEN')),
                                 last_changed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
/

--------------------------------------------------------------------------
-- STEP 2: The "check and change" procedure.
--         The job calls this every 5 seconds. It asks:
--         "has the current color lasted long enough? if yes, change it."
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE process_signal_tick(p_signal_id IN NUMBER) IS
  PRAGMA AUTONOMOUS_TRANSACTION;                          -- own safe transaction
  v_state           traffic_signals.state%TYPE;           -- holds current color
  v_last_changed_at traffic_signals.last_changed_at%TYPE; -- holds last change time
BEGIN
  -- read this signal's current color and time
SELECT state, last_changed_at
INTO v_state, v_last_changed_at
FROM traffic_signals
WHERE signal_id = p_signal_id;

-- RED for 10s -> YELLOW
IF v_state = 'RED' AND SYSTIMESTAMP >= v_last_changed_at + INTERVAL '10' SECOND THEN
UPDATE traffic_signals SET state = 'YELLOW', last_changed_at = SYSTIMESTAMP
WHERE signal_id = p_signal_id;

-- YELLOW for 5s -> GREEN
ELSIF v_state = 'YELLOW' AND SYSTIMESTAMP >= v_last_changed_at + INTERVAL '5' SECOND THEN
UPDATE traffic_signals SET state = 'GREEN', last_changed_at = SYSTIMESTAMP
WHERE signal_id = p_signal_id;

-- GREEN for 10s -> RED
ELSIF v_state = 'GREEN' AND SYSTIMESTAMP >= v_last_changed_at + INTERVAL '10' SECOND THEN
UPDATE traffic_signals SET state = 'RED', last_changed_at = SYSTIMESTAMP
WHERE signal_id = p_signal_id;
END IF;
  -- if not enough time passed, do nothing

COMMIT; -- save the change
END process_signal_tick;
/

--------------------------------------------------------------------------
-- STEP 3: The "start the timer" procedure.
--         Creates a background job that ticks every 5 seconds.
--         Kept separate because creating a job does a COMMIT,
--         which a trigger is not allowed to do directly.
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE start_signal_cycle(p_signal_id IN NUMBER) IS
  PRAGMA AUTONOMOUS_TRANSACTION;                             -- own safe transaction
  v_job_name VARCHAR2(128) := 'TRAFFIC_SIG_' || p_signal_id; -- unique job name
BEGIN
  DBMS_SCHEDULER.CREATE_JOB(
    job_name        => v_job_name,
    job_type        => 'PLSQL_BLOCK',
    job_action      => 'BEGIN process_signal_tick(' || p_signal_id || '); END;', -- what to run
    start_date      => SYSTIMESTAMP,               -- start now
    repeat_interval => 'FREQ=SECONDLY;INTERVAL=5', -- every 5 seconds
    enabled         => TRUE,                        -- turn on now
    auto_drop       => FALSE                        -- keep forever
  );
COMMIT;
END start_signal_cycle;
/

--------------------------------------------------------------------------
-- STEP 4: The trigger. Runs right after a row is inserted and starts
--         its timer. The INSERT finishes instantly (no waiting).
--------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_signal_after_insert
AFTER INSERT ON traffic_signals
FOR EACH ROW
BEGIN
  start_signal_cycle(:NEW.signal_id); -- :NEW.signal_id = the new row's id
END;
/


--------------------------------------------------------------------------
-- STEP 5: Stop ONE signal. Because job names are predictable
--         (TRAFFIC_SIG_<id>), this stops only that one signal.
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE stop_signal_cycle(p_signal_id IN NUMBER) IS
BEGIN
  DBMS_SCHEDULER.DROP_JOB(job_name => 'TRAFFIC_SIG_' || p_signal_id, force => TRUE);
END stop_signal_cycle;
/
