-- Enable DBMS Output:

SET SERVEROUTPUT ON;

-- Create TRAFFIC_SIGNALS Table; 

CREATE TABLE traffic_signals (
    signal_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    signal_name     VARCHAR2(100) NOT NULL,
    state           VARCHAR2(10)
                    DEFAULT 'RED'
                    NOT NULL
                    CONSTRAINT ck_signal_state
                    CHECK (state IN ('RED', 'YELLOW', 'GREEN')),

    last_changed_at TIMESTAMP
                    DEFAULT SYSTIMESTAMP
                    NOT NULL
);

-- Test the table by inserting a row:

INSERT INTO traffic_signals (signal_name) VALUES ('Al Ansab Temporary Signals');
COMMIT;

-- check if the row inserted: 

select * from traffic_signals;
-- signal_id   signal_name                  state       last_changed_at
-- 1	       Al Ansab Temporary Signals	RED	        31-AUG-26 05.16.43.214887000 AM

-- The default state of the traffic is automatically set to red as default.

-- CREATE the Procedure check_and_update_signal_status
CREATE or Replace PROCEDURE check_and_update_signal_status (p_signal_id IN NUMBER) 
as 
    v_state            traffic_signals.state%TYPE;
    v_last_changed_at  TIMESTAMP;
    v_next_state       traffic_signals.state%TYPE;
    v_required_seconds NUMBER;
begin
    dbms_output.put_line('Checking and Updating Signal Status for Signal with ID: ' || p_signal_id);
    select state,
           last_changed_at
    into   v_state,
           v_last_changed_at
    from traffic_signals
    where signal_id = p_signal_id;

    IF v_state = 'RED' THEN
        v_next_state := 'YELLOW';
        v_required_seconds := 10;

    ELSIF v_state = 'YELLOW' THEN
        v_next_state := 'GREEN';
        v_required_seconds := 5;

    ELSE
        v_next_state := 'RED';
        v_required_seconds := 10;

    END IF;

    IF systimestamp >=
       v_last_changed_at +
       NUMTODSINTERVAL(v_required_seconds, 'SECOND')
    THEN
        update traffic_signals
        set state   = v_next_state,
            last_changed_at = systimestamp
        where signal_id = p_signal_id;
        commit;
    END IF;
    
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
        dbms_output.put_line(
            'Signal ID ' || p_signal_id || ' does not exist.'
        );
end check_and_update_signal_status;
/

-- Compile Procedure check_and_update_signal_status

-- Scripu Output: Procedure CHECK_AND_UPDATE_SIGNAL_STATUS compiled

-- Test check_and_update_signal_status Procedure Manually
BEGIN
    check_and_update_signal_status(1);
END;
/

-- Scripu Output: PL/SQL procedure successfully completed.

-- check the status 
SELECT signal_id, signal_name, state, last_changed_at FROM traffic_signals WHERE signal_id = 1;

-- After 10 seconds, the status chnged from RED to Yellow 

-- Output: 
-- signal_id   signal_name                  state       last_changed_at
-- 1	       Al Ansab Temporary Signals	YELLOW	        31-AUG-26 06.07.27.567999000 AM

-- After 5 second I run the Procedure
BEGIN
    check_and_update_signal_status(1);
END;
/

-- The status changed to GREEN 
-- Output: 
-- signal_id   signal_name                  state           last_changed_at
-- 1	       Al Ansab Temporary Signals	GREEN	        31-AUG-26 06.12.34.754175000 AM

-- CREATE START_SIGNAL_WATCH PROCEDURE
CREATE OR REPLACE PROCEDURE start_signal_watch (p_signal_id IN number)
as
begin
    dbms_scheduler.create_job(
        job_name        => 'signal_watch_' || p_signal_id,
        job_type        => 'PLSQL_BLOCK',
        job_action      => 'BEGIN check_and_update_signal_status(' || p_signal_id ||'); END;',
        repeat_interval => 'FREQ=SECONDLY; INTERVAL=5',
        start_date      => systimestamp,
        enabled         => TRUE
    );
end;
/

-- Compile start_signal_watch

-- Scripu Output: Procedure START_SIGNAL_WATCH compiled

SHOW ERRORS PROCEDURE start_signal_watch;

-- No errors:

-- to enable the Privilege of CREATE JOB 
GRANT CREATE JOB TO SYSTEM;

-- Test the START_SIGNAL_WATCH PROCEDURE Manually

BEGIN
    start_signal_watch(1);
END;
/
-- Scripu Output: PL/SQL procedure successfully completed.

-- Verify the JOB exists:

SELECT job_name, enabled, state, repeat_interval, last_start_date, next_run_date FROM user_scheduler_jobs
WHERE job_name LIKE 'SIGNAL_WATCH_%';

-- Output: 
-- job_name        enable    state        repeat_interval            last_start_date                        next_run_date
-- SIGNAL_WATCH_1  TRUE      SCHEDULED    FREQ=SECONDLY; INTERVAL=5  31-AUG-26 06.33.44.136557000 AM GMT    31-AUG-26 06.33.49.000000000 AM GMT


-- Check if the job is executing
SELECT job_name, status, actual_start_date, run_duration, additional_info FROM user_scheduler_job_run_details
WHERE job_name LIKE 'SIGNAL_WATCH_%' ORDER BY log_date DESC;

-- Run several times and check the status change between the Three colors 

SELECT signal_id, signal_name, state, last_changed_at FROM traffic_signals WHERE signal_id = 1;

-- Create the Trigger HANDLE_TRAFFIC_SIGNAL_INSERT_EVENT 

CREATE OR REPLACE NONEDITIONABLE TRIGGER handle_traffic_signal_insert_event
AFTER INSERT ON traffic_signals
FOR EACH ROW

BEGIN
    dbms_output.put_line(:NEW.signal_id);
END handle_traffic_signal_insert_event;
/

-- Before testing the Trigger, Insert a new recore 

INSERT INTO traffic_signals (signal_name) VALUES ('Al Qurum Signals');

COMMIT;

-- Check the ID for this record 
SELECT signal_id, signal_name, state, last_changed_at FROM traffic_signals ORDER BY signal_id;

-- signal_id = 2

BEGIN
    start_signal_watch(2);
END;
/

-- Check Oracle Scheduler:

SELECT job_name, enabled, state, repeat_interval, last_start_date, next_run_date FROM user_scheduler_jobs
WHERE job_name LIKE 'SIGNAL_WATCH_%';

-- Output: 
-- job_name        enable    state        repeat_interval            last_start_date                        next_run_date
-- SIGNAL_WATCH_1  TRUE      SCHEDULED    FREQ=SECONDLY; INTERVAL=5  31-AUG-26 06.33.44.136557000 AM GMT    31-AUG-26 06.33.49.000000000 AM GMT
-- SIGNAL_WATCH_2  TRUE      SCHEDULED    FREQ=SECONDLY; INTERVAL=5  31-AUG-26 07.16.42.127773000 AM GMT    31-AUG-26 07.16.47.000000000 AM GMT


INSERT INTO traffic_signals (signal_name) VALUES ('ALKhuwair Signal');

COMMIT;

BEGIN
    start_signal_watch(3);
END;
/

SELECT signal_id,
       signal_name,
       state,
       last_changed_at
FROM traffic_signals
ORDER BY signal_id;
-- signal_id   signal_name                  state       last_changed_at
-- 1	       Al Ansab Temporary Signals	RED	        31-AUG-26 07.19.44.180823000 AM
-- 2           Al Qurum Signals             YELLOW      31-AUG-26 07.19.42.157321000 AM
-- 3           ALKhuwair Signal             RED         31-AUG-26 07.19.28.432506000 AM