services:
  oracle-db:
    image: gvenzl/oracle-free:23-slim
    container_name: app-container
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      APP_USER: ${DB_USERNAME}
      APP_USER_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - app-network
    restart: unless-stopped

  api:
    build: .
    image: ibrahimrahbi/healthcheck:latest
    container_name: healthcheckapp
    ports:
      - "8000:8080"
    environment:
      DB_URL: "jdbc:oracle:thin:@oracle-db:1521/FREEPDB1"
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      oracle-db:
        condition: service_healthy
        restart: true
    volumes:
      - ./shared_upload_files:/app/uploaded_files
    networks:
      - app-network
    restart: unless-stopped

volumes:
  oracle_data:

networks:
  app-network:
    driver: bridge
