/*
    TRAFFIC LIGHTS - ORACLE PL/SQL BUILD

    Run this whole file in DbVisualizer using Execute Script.

    Design:
      1. TRAFFIC_SIGNALS table
      2. UPDATE_SIGNAL_STATE procedure
      3. MANAGE_SIGNAL_CYCLE procedure
      4. AUTO-START trigger

    Cycle:
      RED    -> 10 seconds -> YELLOW
      YELLOW ->  5 seconds -> GREEN
      GREEN  -> 10 seconds -> RED

    Each signal gets its own DBMS_SCHEDULER job.
    No dummy/test data is included.

    DbVisualizer note:
      --/ starts a PL/SQL SQL block
      /   ends the SQL block
*/


/* =========================================================
   1. CREATE TRAFFIC SIGNAL TABLE
   ========================================================= */

CREATE TABLE traffic_signals (
  signal_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  signal_name     VARCHAR2(100) NOT NULL,
  state           VARCHAR2(10) DEFAULT 'RED' NOT NULL
                  CONSTRAINT ck_signal_state
                  CHECK (state IN ('RED','YELLOW','GREEN')),
  last_changed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);


/* =========================================================
   2. PROCEDURE 1 - UPDATE SIGNAL STATE

   Checks whether the current state has reached its required
   duration. It does not WAIT or SLEEP.
   ========================================================= */

--/
CREATE OR REPLACE PROCEDURE update_signal_state (
    p_signal_id IN NUMBER
)
AS
    PRAGMA AUTONOMOUS_TRANSACTION;

    v_state             VARCHAR2(10);
    v_last_changed_at   TIMESTAMP;
    v_required_seconds  NUMBER;
BEGIN

    SELECT state,
           last_changed_at
    INTO   v_state,
           v_last_changed_at
    FROM   traffic_signals
    WHERE  signal_id = p_signal_id
    FOR UPDATE;

    IF v_state = 'RED' THEN
        v_required_seconds := 10;

    ELSIF v_state = 'YELLOW' THEN
        v_required_seconds := 5;

    ELSIF v_state = 'GREEN' THEN
        v_required_seconds := 10;
    END IF;

    IF SYSTIMESTAMP >=
       v_last_changed_at
       + NUMTODSINTERVAL(v_required_seconds, 'SECOND')
    THEN

        IF v_state = 'RED' THEN
            v_state := 'YELLOW';

        ELSIF v_state = 'YELLOW' THEN
            v_state := 'GREEN';

        ELSIF v_state = 'GREEN' THEN
            v_state := 'RED';
        END IF;

        UPDATE traffic_signals
        SET state = v_state,
            last_changed_at =
                v_last_changed_at
                + NUMTODSINTERVAL(v_required_seconds, 'SECOND')
        WHERE signal_id = p_signal_id;

    END IF;

    COMMIT;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        ROLLBACK;

    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

/* =========================================================
   3. PROCEDURE 2 - MANAGE SIGNAL CYCLE

   START:
     Creates one Scheduler job for one traffic signal.

   STOP:
     Removes only that signal's Scheduler job.
   ========================================================= */

--/
CREATE OR REPLACE PROCEDURE manage_signal_cycle (
    p_signal_id IN NUMBER,
    p_action    IN VARCHAR2
)
AS
    PRAGMA AUTONOMOUS_TRANSACTION;

    v_job_name  VARCHAR2(100);
    v_job_count NUMBER;
BEGIN

    v_job_name := 'TS_SIGNAL_' || p_signal_id;

    SELECT COUNT(*)
    INTO   v_job_count
    FROM   user_scheduler_jobs
    WHERE  job_name = v_job_name;

    IF UPPER(p_action) = 'START' THEN

        IF v_job_count = 0 THEN

            DBMS_SCHEDULER.CREATE_JOB (
                job_name            => v_job_name,
                job_type            => 'STORED_PROCEDURE',
                job_action          => 'UPDATE_SIGNAL_STATE',
                number_of_arguments => 1,
                start_date          => SYSTIMESTAMP,
                repeat_interval     => 'FREQ=SECONDLY;INTERVAL=5',
                enabled             => FALSE
            );

            DBMS_SCHEDULER.SET_JOB_ARGUMENT_VALUE (
                job_name          => v_job_name,
                argument_position => 1,
                argument_value    => TO_CHAR(p_signal_id)
            );

            DBMS_SCHEDULER.ENABLE(v_job_name);

        END IF;

    ELSIF UPPER(p_action) = 'STOP' THEN

        IF v_job_count > 0 THEN

            DBMS_SCHEDULER.DROP_JOB (
                job_name => v_job_name,
                force    => TRUE
            );

        END IF;

    ELSE
        RAISE_APPLICATION_ERROR(
            -20001,
            'Use START or STOP'
        );
    END IF;

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

/* =========================================================
   4. AUTO-START TRIGGER

   Every newly inserted signal automatically starts its own
   Scheduler job. No separate START command is needed.
   ========================================================= */

--/
CREATE OR REPLACE TRIGGER trg_traffic_signal_auto_start
AFTER INSERT ON traffic_signals
FOR EACH ROW
BEGIN
    manage_signal_cycle(
        :NEW.signal_id,
        'START'
    );
END;
/

/* =========================================================
   BUILD VERIFICATION
   ========================================================= */

SELECT object_name,
       object_type,
       status
FROM user_objects
WHERE object_name IN (
    'TRAFFIC_SIGNALS',
    'UPDATE_SIGNAL_STATE',
    'MANAGE_SIGNAL_CYCLE',
    'TRG_TRAFFIC_SIGNAL_AUTO_START'
)
ORDER BY object_type, object_name;

SELECT name,
       type,
       line,
       position,
       text
FROM user_errors
WHERE name IN (
    'UPDATE_SIGNAL_STATE',
    'MANAGE_SIGNAL_CYCLE',
    'TRG_TRAFFIC_SIGNAL_AUTO_START'
)
ORDER BY name, sequence;
