-- ============================================================================
--  COMPLAINT ESCALATION WATCHDOG - CHALLENGE SETUP
--  08_escalation_challenge_setup.sql
--  Self-contained schema + seed data for the "Complaint Escalation Watchdog"
--  challenge (07_challenge_escalation_watchdog.md). Includes only what that
--  challenge needs - not the full complaint portal schema.
--  Localized for an Omani training audience (names, +968 numbers).
--  Re-runnable: drops and recreates everything below.
--  Target: Oracle Database 23ai Free / 21c XE. Run in SQL Developer, F5.
-- ============================================================================

SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED

-- ---------------------------------------------------------------------------
-- 0. Clean slate
-- ---------------------------------------------------------------------------
BEGIN
  FOR r IN (
    SELECT table_name FROM user_tables
    WHERE table_name IN ('COMPLAINT_AUDIT','NOTIFICATIONS','COMPLAINTS',
                          'CATEGORIES','AGENTS','DEPARTMENTS','CUSTOMERS')
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/

-- ---------------------------------------------------------------------------
-- 1. Reference / master data
-- ---------------------------------------------------------------------------
CREATE TABLE departments (
  dept_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dept_code  VARCHAR2(20)  NOT NULL UNIQUE,
  dept_name  VARCHAR2(100) NOT NULL,
  email_box  VARCHAR2(150),
  is_active  CHAR(1) DEFAULT 'Y' NOT NULL
             CONSTRAINT ck_dept_active CHECK (is_active IN ('Y','N'))
);

CREATE TABLE agents (
  agent_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_name     VARCHAR2(100) NOT NULL,
  email          VARCHAR2(150) NOT NULL UNIQUE,
  dept_id        NUMBER        NOT NULL REFERENCES departments(dept_id),
  max_open_cases NUMBER(3) DEFAULT 10 NOT NULL,
  is_active      CHAR(1)   DEFAULT 'Y' NOT NULL
                 CONSTRAINT ck_agent_active CHECK (is_active IN ('Y','N'))
);

CREATE TABLE categories (
  category_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_code    VARCHAR2(30)  NOT NULL UNIQUE,
  category_name    VARCHAR2(100) NOT NULL,
  dept_id          NUMBER        NOT NULL REFERENCES departments(dept_id),
  default_priority VARCHAR2(10)  DEFAULT 'MEDIUM' NOT NULL
                   CONSTRAINT ck_cat_priority
                   CHECK (default_priority IN ('LOW','MEDIUM','HIGH','CRITICAL')),
  sla_hours        NUMBER(5)     NOT NULL,
  is_active        CHAR(1) DEFAULT 'Y' NOT NULL
                   CONSTRAINT ck_cat_active CHECK (is_active IN ('Y','N'))
);

CREATE TABLE customers (
  customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name   VARCHAR2(120) NOT NULL,
  email       VARCHAR2(150) NOT NULL UNIQUE,
  phone       VARCHAR2(20),
  tier        VARCHAR2(10) DEFAULT 'STANDARD' NOT NULL
              CONSTRAINT ck_cust_tier CHECK (tier IN ('STANDARD','PREMIUM','VIP')),
  created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- ---------------------------------------------------------------------------
-- 2. Transactional table
-- ---------------------------------------------------------------------------
CREATE TABLE complaints (
  complaint_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference_no      VARCHAR2(20) UNIQUE,
  customer_id       NUMBER        NOT NULL REFERENCES customers(customer_id),
  category_id       NUMBER        NOT NULL REFERENCES categories(category_id),
  dept_id           NUMBER        REFERENCES departments(dept_id),
  assigned_agent_id NUMBER        REFERENCES agents(agent_id),
  subject           VARCHAR2(200) NOT NULL,
  description       CLOB,
  status            VARCHAR2(20)  DEFAULT 'NEW' NOT NULL
                    CONSTRAINT ck_cmp_status CHECK (status IN
                    ('NEW','ASSIGNED','IN_PROGRESS','PENDING_CUSTOMER',
                     'RESOLVED','CLOSED','REJECTED')),
  priority          VARCHAR2(10)  DEFAULT 'MEDIUM' NOT NULL
                    CONSTRAINT ck_cmp_priority CHECK (priority IN
                    ('LOW','MEDIUM','HIGH','CRITICAL')),
  escalation_level  NUMBER(1)     DEFAULT 0 NOT NULL
                    CONSTRAINT ck_cmp_esc CHECK (escalation_level BETWEEN 0 AND 3),
  source_channel    VARCHAR2(20)  DEFAULT 'WEB' NOT NULL,
  created_at        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  due_at            TIMESTAMP,
  resolved_at       TIMESTAMP,
  closed_at         TIMESTAMP,
  created_by        VARCHAR2(50)  DEFAULT USER NOT NULL,
  updated_at        TIMESTAMP,
  updated_by        VARCHAR2(50)
);

-- ---------------------------------------------------------------------------
-- 3. Tables the challenge writes to
-- ---------------------------------------------------------------------------
CREATE TABLE notifications (
  id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  for_id NUMBER,
  type   VARCHAR2(10),
  msg    VARCHAR2(200)
);

CREATE TABLE complaint_audit (
  audit_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complaint_id NUMBER       NOT NULL,
  reference_no VARCHAR2(20),
  action       VARCHAR2(10) NOT NULL
               CONSTRAINT ck_audit_action CHECK (action IN ('INSERT','UPDATE','DELETE')),
  column_name  VARCHAR2(30),
  old_value    VARCHAR2(4000),
  new_value    VARCHAR2(4000),
  changed_by   VARCHAR2(50) DEFAULT USER NOT NULL,
  changed_at   TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL
);

-- ---------------------------------------------------------------------------
-- 4. View used by the "is overdue" hint
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW v_complaint_detail AS
SELECT c.complaint_id,
       c.reference_no,
       cu.full_name    AS customer_name,
       cu.email        AS customer_email,
       cu.tier         AS customer_tier,
       cat.category_code,
       cat.category_name,
       cat.sla_hours,
       d.dept_code,
       d.dept_name,
       a.agent_name,
       c.subject,
       c.status,
       c.priority,
       c.escalation_level,
       c.created_at,
       c.due_at,
       c.resolved_at,
       CASE WHEN c.status NOT IN ('RESOLVED','CLOSED','REJECTED')
             AND c.due_at < SYSTIMESTAMP THEN 'Y' ELSE 'N' END AS is_overdue
FROM   complaints c
JOIN   customers  cu  ON cu.customer_id = c.customer_id
JOIN   categories cat ON cat.category_id = c.category_id
LEFT   JOIN departments d ON d.dept_id  = c.dept_id
LEFT   JOIN agents      a ON a.agent_id = c.assigned_agent_id;

-- ---------------------------------------------------------------------------
-- 5. Seed data - departments
-- ---------------------------------------------------------------------------
INSERT INTO departments (dept_id, dept_code, dept_name, email_box) VALUES (10,'BILLING','Billing & Payments','billing@portal.local');
INSERT INTO departments (dept_id, dept_code, dept_name, email_box) VALUES (20,'TECH','Technical Support','tech@portal.local');
INSERT INTO departments (dept_id, dept_code, dept_name, email_box) VALUES (30,'FIELD','Field Operations','field@portal.local');
INSERT INTO departments (dept_id, dept_code, dept_name, email_box) VALUES (40,'CARE','Customer Care','care@portal.local');

-- ---------------------------------------------------------------------------
-- 6. Seed data - categories
-- ---------------------------------------------------------------------------
INSERT INTO categories (category_id, category_code, category_name, dept_id, default_priority, sla_hours) VALUES (200,'BILL_WRONG_AMT','Incorrect bill amount',       10,'MEDIUM',  24);
INSERT INTO categories (category_id, category_code, category_name, dept_id, default_priority, sla_hours) VALUES (201,'NET_DOWN',      'No internet / service down',  20,'CRITICAL', 4);
INSERT INTO categories (category_id, category_code, category_name, dept_id, default_priority, sla_hours) VALUES (202,'NET_SLOW',      'Slow connection',             20,'MEDIUM',  24);
INSERT INTO categories (category_id, category_code, category_name, dept_id, default_priority, sla_hours) VALUES (203,'INSTALL_DELAY', 'Installation delayed',        30,'HIGH',     8);
INSERT INTO categories (category_id, category_code, category_name, dept_id, default_priority, sla_hours) VALUES (204,'STAFF_RUDE',    'Staff behaviour',             40,'MEDIUM',  40);

-- ---------------------------------------------------------------------------
-- 7. Seed data - agents
-- ---------------------------------------------------------------------------
INSERT INTO agents (agent_id, agent_name, email, dept_id, max_open_cases) VALUES (300,'Aisha Al-Balushi','aisha@portal.local', 10, 8);
INSERT INTO agents (agent_id, agent_name, email, dept_id, max_open_cases) VALUES (301,'Omar Al-Hinai',   'omar@portal.local',  20,10);
INSERT INTO agents (agent_id, agent_name, email, dept_id, max_open_cases) VALUES (302,'Yousuf Al-Amri',  'yousuf@portal.local',20,10);
INSERT INTO agents (agent_id, agent_name, email, dept_id, max_open_cases) VALUES (303,'Salma Al-Kindi',  'salma@portal.local', 30, 5);
INSERT INTO agents (agent_id, agent_name, email, dept_id, max_open_cases) VALUES (304,'Noor Al-Saadi',   'noor@portal.local',  40,12);

-- ---------------------------------------------------------------------------
-- 8. Seed data - customers
-- ---------------------------------------------------------------------------
INSERT INTO customers (customer_id, full_name, email, phone, tier) VALUES (100,'Fatma Al-Habsi',  'fatma@example.com',  '+96891000001','VIP');
INSERT INTO customers (customer_id, full_name, email, phone, tier) VALUES (101,'Said Al-Mahrouqi','said@example.com',   '+96891000002','STANDARD');
INSERT INTO customers (customer_id, full_name, email, phone, tier) VALUES (102,'Zainab Al-Lawati','zainab@example.com', '+96891000003','PREMIUM');
INSERT INTO customers (customer_id, full_name, email, phone, tier) VALUES (103,'Khalid Al-Rawahi','khalid@example.com', '+96891000004','STANDARD');
INSERT INTO customers (customer_id, full_name, email, phone, tier) VALUES (104,'Mariam Al-Farsi', 'mariam@example.com', '+96891000005','STANDARD');
INSERT INTO customers (customer_id, full_name, email, phone, tier) VALUES (105,'Tariq Al-Busaidi','tariq@example.com',  '+96891000006','VIP');

COMMIT;

-- ---------------------------------------------------------------------------
-- 9. Seed data - complaints
--    Deliberately hand-built (not generated) so every branch of the
--    challenge's logic gets exercised at least once. Explanation of intent
--    is on each row - remove the comments before handing this to trainees
--    if you don't want to give the answer away.
-- ---------------------------------------------------------------------------

-- (1) Overdue, open, level 0 -> should escalate to level 1
INSERT INTO complaints (complaint_id, reference_no, customer_id, category_id, dept_id, assigned_agent_id, subject, description, status, priority, escalation_level, created_at, due_at) VALUES
 (1,'CMP-2026-000001',100,201,20,302,'Internet down since yesterday','No lights on the router at all.','IN_PROGRESS','CRITICAL',0, SYSTIMESTAMP - INTERVAL '3' DAY, SYSTIMESTAMP - INTERVAL '2' DAY);

-- (2) Overdue, open, level 1 -> should escalate to level 2
INSERT INTO complaints (complaint_id, reference_no, customer_id, category_id, dept_id, assigned_agent_id, subject, description, status, priority, escalation_level, created_at, due_at) VALUES
 (2,'CMP-2026-000002',101,200,10,300,'Wrong amount charged twice','Two debits for the same bill.','NEW','MEDIUM',1, SYSTIMESTAMP - INTERVAL '5' DAY, SYSTIMESTAMP - INTERVAL '4' DAY);

-- (3) Overdue, open, level 2 -> should escalate to level 3
INSERT INTO complaints (complaint_id, reference_no, customer_id, category_id, dept_id, assigned_agent_id, subject, description, status, priority, escalation_level, created_at, due_at) VALUES
 (3,'CMP-2026-000003',102,203,30,303,'Installation delayed again','Third reschedule this month.','ASSIGNED','HIGH',2, SYSTIMESTAMP - INTERVAL '10' DAY, SYSTIMESTAMP - INTERVAL '9' DAY);

-- (4) Overdue, open, but ALREADY at the max level 3 -> must NOT escalate further
INSERT INTO complaints (complaint_id, reference_no, customer_id, category_id, dept_id, assigned_agent_id, subject, description, status, priority, escalation_level, created_at, due_at) VALUES
 (4,'CMP-2026-000004',103,201,20,302,'No internet for a week','Ongoing outage, multiple call backs.','IN_PROGRESS','CRITICAL',3, SYSTIMESTAMP - INTERVAL '15' DAY, SYSTIMESTAMP - INTERVAL '14' DAY);

-- (5) Overdue-looking due date, but status RESOLVED -> not "open", must NOT escalate
INSERT INTO complaints (complaint_id, reference_no, customer_id, category_id, dept_id, assigned_agent_id, subject, description, status, priority, escalation_level, created_at, due_at, resolved_at) VALUES
 (5,'CMP-2026-000005',104,204,40,304,'Agent was rude on call','Customer felt dismissed.','RESOLVED','MEDIUM',0, SYSTIMESTAMP - INTERVAL '6' DAY, SYSTIMESTAMP - INTERVAL '5' DAY, SYSTIMESTAMP - INTERVAL '4' DAY);

-- (6) Overdue-looking due date, but status CLOSED -> must NOT escalate
INSERT INTO complaints (complaint_id, reference_no, customer_id, category_id, dept_id, assigned_agent_id, subject, description, status, priority, escalation_level, created_at, due_at, closed_at) VALUES
 (6,'CMP-2026-000006',105,200,10,300,'Refund never processed','Refund confirmed by finance, closed after payout.','CLOSED','HIGH',1, SYSTIMESTAMP - INTERVAL '8' DAY, SYSTIMESTAMP - INTERVAL '7' DAY, SYSTIMESTAMP - INTERVAL '6' DAY);

-- (7) NOT overdue yet (due date is in the future) -> must NOT escalate
INSERT INTO complaints (complaint_id, reference_no, customer_id, category_id, dept_id, assigned_agent_id, subject, description, status, priority, escalation_level, created_at, due_at) VALUES
 (7,'CMP-2026-000007',100,202,20,302,'Speed way below plan','Getting 2 Mbps on a 100 Mbps plan.','IN_PROGRESS','MEDIUM',0, SYSTIMESTAMP - INTERVAL '1' HOUR, SYSTIMESTAMP + INTERVAL '23' HOUR);

-- (8) Overdue, PENDING_CUSTOMER counts as open (not in the final-state list) -> should escalate to level 1
INSERT INTO complaints (complaint_id, reference_no, customer_id, category_id, dept_id, assigned_agent_id, subject, description, status, priority, escalation_level, created_at, due_at) VALUES
 (8,'CMP-2026-000008',101,201,20,303,'Router lights all red','Waiting on customer to confirm a reset window.','PENDING_CUSTOMER','CRITICAL',0, SYSTIMESTAMP - INTERVAL '4' DAY, SYSTIMESTAMP - INTERVAL '3' DAY);

-- (9) Overdue-looking due date, but status REJECTED -> final state, must NOT escalate
INSERT INTO complaints (complaint_id, reference_no, customer_id, category_id, dept_id, assigned_agent_id, subject, description, status, priority, escalation_level, created_at, due_at) VALUES
 (9,'CMP-2026-000009',102,203,30,303,'Technician cancelled twice','Deemed out of SLA scope, rejected.','REJECTED','HIGH',0, SYSTIMESTAMP - INTERVAL '12' DAY, SYSTIMESTAMP - INTERVAL '11' DAY);

-- (10) Overdue, open, level 0 -> should escalate to level 1
INSERT INTO complaints (complaint_id, reference_no, customer_id, category_id, dept_id, assigned_agent_id, subject, description, status, priority, escalation_level, created_at, due_at) VALUES
 (10,'CMP-2026-000010',103,200,10,300,'Double billed for July','Two identical charges same day.','NEW','MEDIUM',0, SYSTIMESTAMP - INTERVAL '2' DAY, SYSTIMESTAMP - INTERVAL '1' DAY);

COMMIT;

-- Re-align identity generators past the explicit IDs above
ALTER TABLE departments MODIFY (dept_id      GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE));
ALTER TABLE categories  MODIFY (category_id  GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE));
ALTER TABLE agents      MODIFY (agent_id     GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE));
ALTER TABLE customers   MODIFY (customer_id  GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE));
ALTER TABLE complaints  MODIFY (complaint_id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE));

-- ---------------------------------------------------------------------------
-- 10. Sanity check - eyeball this before starting the challenge
-- ---------------------------------------------------------------------------
SELECT complaint_id, status, escalation_level, is_overdue, due_at
FROM   v_complaint_detail
ORDER  BY complaint_id;

-------------------------
SET SERVEROUTPUT ON;

CREATE OR REPLACE FUNCTION is_complaint_overdue_open (
    p_complaint_id IN complaints.complaint_id%TYPE
) RETURN BOOLEAN
IS
    v_is_overdue v_complaint_detail.is_overdue%TYPE;
BEGIN
    SELECT is_overdue
      INTO v_is_overdue
      FROM v_complaint_detail
     WHERE complaint_id = p_complaint_id;

    RETURN v_is_overdue = 'Y';

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN FALSE;
END;
/

CREATE OR REPLACE PROCEDURE p_run_escalation_watchdog
AS
    v_escalated_count NUMBER := 0;
    v_new_level       complaints.escalation_level%TYPE;
BEGIN
    FOR c_rec IN (SELECT complaint_id, reference_no, escalation_level FROM complaints)
    LOOP
        IF is_complaint_overdue_open(c_rec.complaint_id) AND c_rec.escalation_level < 3 THEN

            v_new_level := c_rec.escalation_level + 1;

            UPDATE complaints
               SET escalation_level = v_new_level
             WHERE complaint_id = c_rec.complaint_id;

            INSERT INTO notifications (for_id, type, msg)
            VALUES (
                c_rec.complaint_id,
                'WARN',
                'Complaint ' || c_rec.reference_no ||
                ' is overdue - escalated to level ' || v_new_level
            );

            v_escalated_count := v_escalated_count + 1;
        END IF;
    END LOOP;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Watchdog finished. Complaints escalated: ' || v_escalated_count);
END;
/
BEGIN
    p_run_escalation_watchdog();
END;
/
--
SELECT * FROM notifications WHERE type = 'WARN';
