-- CREATE TABLE
-- CREATE TABLE traffic_signals (
--    signal_id NUMBER--
--        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

--    signal_name VARCHAR2(100) NOT NULL,

--    state VARCHAR2(10)
--        DEFAULT 'RED' NOT NULL
--        CONSTRAINT ck_signal_state CHECK (state IN ('RED', 'YELLOW', 'GREEN')),

--    last_changed_at TIMESTAMP WITH TIME ZONE
--        DEFAULT (SYSTIMESTAMP AT TIME ZONE 'Asia/Muscat') NOT NULL
--);

-- check one signal and change color when time is enough
CREATE OR REPLACE PROCEDURE check_and_update_signal_status (
    p_signal_id IN NUMBER
) AS
    v_state            VARCHAR2(10);
    v_last_changed_at  TIMESTAMP WITH TIME ZONE;
    v_next_state       VARCHAR2(10);
    v_required_seconds NUMBER;
    v_oman_time        TIMESTAMP WITH TIME ZONE;
BEGIN
    v_oman_time := SYSTIMESTAMP AT TIME ZONE 'Asia/Muscat';

    DBMS_OUTPUT.PUT_LINE(
        'Checking and Updating Signal Status for Signal with ID: ' || p_signal_id
    );

SELECT state, last_changed_at
INTO   v_state, v_last_changed_at
FROM   traffic_signals
WHERE  signal_id = p_signal_id;

IF v_state = 'RED' THEN
        v_next_state := 'YELLOW';
        v_required_seconds := 10;
    ELSIF v_state = 'YELLOW' THEN
        v_next_state := 'GREEN';
        v_required_seconds := 5;
ELSE
        v_next_state := 'RED';
        v_required_seconds := 10;
END IF;

    IF v_oman_time >= v_last_changed_at
                      + NUMTODSINTERVAL(v_required_seconds, 'SECOND')
    THEN
UPDATE traffic_signals
SET    state = v_next_state,
       last_changed_at = v_oman_time
WHERE  signal_id = p_signal_id;

COMMIT;
END IF;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        NULL;
END;
/

-- start scheduler job for one signal
CREATE OR REPLACE PROCEDURE start_signal_watch (
    p_signal_id IN NUMBER
) AS
    PRAGMA AUTONOMOUS_TRANSACTION;

    v_job_name  VARCHAR2(100);
    v_oman_time TIMESTAMP WITH TIME ZONE;
BEGIN
    v_job_name := 'SIG_WATCH_' || p_signal_id;
    v_oman_time := SYSTIMESTAMP AT TIME ZONE 'Asia/Muscat';

    DBMS_OUTPUT.PUT_LINE(
        'Scheduling a job for Signal with ID: ' || p_signal_id
    );

BEGIN
        DBMS_SCHEDULER.DROP_JOB(v_job_name, TRUE);
EXCEPTION
        WHEN OTHERS THEN
            NULL;
END;

    DBMS_SCHEDULER.CREATE_JOB(
        job_name        => v_job_name,
        job_type        => 'PLSQL_BLOCK',
        job_action      => 'BEGIN check_and_update_signal_status('
                           || p_signal_id || '); END;',
        start_date      => v_oman_time,
        repeat_interval => 'FREQ=SECONDLY;INTERVAL=5',
        enabled         => TRUE
    );

COMMIT;
END;
/

-- after insert, start the job
CREATE OR REPLACE TRIGGER trg_start_signal_watch
AFTER INSERT ON traffic_signals
FOR EACH ROW
BEGIN
    start_signal_watch(:NEW.signal_id);
END;
/

-- stop one signal
CREATE OR REPLACE PROCEDURE stop_signal_watch (
    p_signal_id IN NUMBER
) AS
    v_job_name VARCHAR2(100);
BEGIN
    v_job_name := 'SIG_WATCH_' || p_signal_id;
    DBMS_SCHEDULER.DISABLE(name => v_job_name);
END;
/