-- display on the console
SET SERVEROUTPUT ON;

 -- dropping id column
alter table notifications drop column id;

-- making id column auto increment
alter table notifications add id number generated by default on null as identity (start with 1) primary key;

-- function to check if a complaint is overdue and still open
create or replace function f_is_overdue_open (p_complaint_id in number) return varchar2
as
  v_status varchar2(20);
  v_due_at timestamp;
begin
select status, due_at into v_status, v_due_at
from complaints
where complaint_id = p_complaint_id;

if v_status not in ('RESOLVED', 'CLOSED', 'REJECTED') and v_due_at < systimestamp then
    return 'Y';
else
    return 'N';
end if;
end;
/

-- procedure to escalate overdue complaints and log a notification for each
create or replace procedure p_escalate_overdue
as
  v_count number := 0;
begin
for c_rec in (select complaint_id, reference_no, escalation_level from complaints) loop
    if f_is_overdue_open(c_rec.complaint_id) = 'Y' and c_rec.escalation_level < 3 then
update complaints
set escalation_level = escalation_level + 1
where complaint_id = c_rec.complaint_id;

insert into notifications (for_id, msg_type, msg)
values (c_rec.complaint_id, 'WARN', 'Complaint ' || c_rec.reference_no || ' escalated to level ' || (c_rec.escalation_level + 1));

v_count := v_count + 1;
end if;
end loop;
  dbms_output.put_line(v_count || ' complaints escalated.');
end;
/

-- running the procedure
begin
  p_escalate_overdue();
end;

-- check the results
select * from notifications where msg_type = 'WARN';