SET SERVEROUTPUT ON;

-- creating signal table
CREATE TABLE traffic_signals (
                                 signal_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 signal_name     VARCHAR2(100) NOT NULL,
                                 state           VARCHAR2(10) DEFAULT 'RED' NOT NULL
                  CONSTRAINT ck_signal_state CHECK (state IN ('RED','YELLOW','GREEN')),
                                 last_changed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- inserting into table
INSERT INTO TRAFFIC_SIGNALS (SIGNAL_NAME, STATE) VALUES ('SEEB','RED');

-- displaying the table
SELECT * FROM TRAFFIC_SIGNALS;

-- procedure to check the state of the signal
CREATE OR REPLACE PROCEDURE CHECK_SIGNAL (p_signal_id IN NUMBER)
AS
  v_state VARCHAR2;
  v_last_changed_at TIMESTAMP;
BEGIN
  DBMS_OUTPUT.PUT_LINE('Chceking signal status for signal with ID: ' || p_signal_id);
SELECT STATE, LAST_CHANGED_AT INTO v_state, v_last_changed_at FROM TRAFFIC_SIGNALS WHERE SIGNAL_ID = p_signal_id;

DBMS_OUTPUT.PUT_LINE('Signal state is: ' || v_state|| ' - ' || 'Signal last changed at: ' || v_last_changed_at);
END CHECK_SIGNAL;
/

--running the procedure
BEGIN
  CHECK_SIGNAL (1);
END;

-- ANOTHER PROCEEDURE FOR CHANGING THE SIGNAL
CREATE OR REPLACE PROCEDURE CHECK_AND_UPDATE_SIGNAL (p_signal_id IN NUMBER)
AS
  v_state VARCHAR2(10);
  v_last_changed_at TIMESTAMP;
  v_next_state VARCHAR2(10);
  v_required_seconds NUMBER;
BEGIN
  DBMS_OUTPUT.PUT_LINE('Chcekin and Updating singal status for signal with ID: ' || p_signal_id);
SELECT STATE, LAST_CHANGED_AT INTO v_state, v_last_changed_at FROM TRAFFIC_SIGNALS WHERE SIGNAL_ID = p_signal_id;

IF v_state = 'RED' THEN
    v_next_state := 'YELLOW'; v_required_seconds := 10;
  ELSIF v_state = 'YELLOW' THEN
    v_next_state := 'GREEN'; v_required_seconds := 5;
ELSE
    v_next_state := 'RED'; v_required_seconds := 10;
END IF;

  IF systimestamp >= v_last_changed_at + NUMTODSINTERVAL(v_required_seconds, 'SECOND') THEN
UPDATE TRAFFIC_SIGNALS SET STATE = v_next_state,last_changed_at = systimestamp WHERE SIGNAL_ID = p_signal_id;
COMMIT;
END IF;
END CHECK_AND_UPDATE_SIGNAL;
/

--running the procedure
BEGIN
  CHECK_AND_UPDATE_SIGNAL (1);
END;

-- creating a JOB for the signal to start
CREATE OR REPLACE PROCEDURE START_SIGNAL_WATCH (p_signal_id IN NUMBER) AS
  PRAGMA AUTONOMOUS_TRANSACTION; -- treats it as a separate transaction so it doesnt rely on  top procedure
BEGIN
  DBMS_SCHEDULER.CREATE_JOB(
    JOB_NAME => 'signal' || p_signal_id,
    JOB_TYPE => 'PLSQL_BLOCK',
    JOB_ACTION => 'BEGIN CHECK_AND_UPDATE_SIGNAL('||p_signal_id||');END;',
    REPEAT_INTERVAL => 'FREQ=SECONDLY; INTERVAL=5',
    START_DATE => systimestamp,
    ENABLED => TRUE
  );
COMMIT;
END START_SIGNAL_WATCH;
/

-- CREATE TRIGGER for when inserting a new signal
CREATE OR REPLACE TRIGGER TRAFFIC_SIGNAL_INSERTION
AFTER INSERT ON TRAFFIC_SIGNALS
FOR EACH ROW
BEGIN
  DBMS_OUTPUT.PUT_LINE('TO DO');
    start_signal_watch(:NEW.signal_id);
END TRAFFIC_SIGNAL_INSERTION;
/


-- testing
INSERT INTO TRAFFIC_SIGNALS (SIGNAL_NAME) VALUES ('Seeb');
INSERT INTO TRAFFIC_SIGNALS (SIGNAL_NAME) VALUES ('Bowsher');
INSERT INTO TRAFFIC_SIGNALS (SIGNAL_NAME) VALUES ('MQ');
INSERT INTO TRAFFIC_SIGNALS (SIGNAL_NAME) VALUES ('Muttrah');
COMMIT;

SELECT * FROM TRAFFIC_SIGNALS;

BEGIN
  CHECK_SIGNAL (25);
END;


