-- Disable constraints for clean drop/recreate
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE prescription_items CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE visits CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE admissions CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE appointments CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE medicines CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE doctors CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE patients CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 1. Patients Table
CREATE TABLE patients (
                          patient_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          full_name     VARCHAR2(150) NOT NULL,
                          date_of_birth DATE,
                          gender        VARCHAR2(10),
                          phone_number  VARCHAR2(20),
                          address       VARCHAR2(255),
                          created_at    TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 2. Doctors Table
CREATE TABLE doctors (
                         doctor_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         doctor_name   VARCHAR2(150) NOT NULL,
                         specialization VARCHAR2(100),
                         phone_number  VARCHAR2(20),
                         email         VARCHAR2(100)
);

-- 3. Medicines Table
CREATE TABLE medicines (
                           medicine_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           medicine_name VARCHAR2(150) NOT NULL,
                           category      VARCHAR2(100),
                           unit_price    NUMBER(10,2),
                           stock_qty     NUMBER(10)
);

-- 4. Appointments Table
CREATE TABLE appointments (
                              appointment_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              patient_id       NUMBER REFERENCES patients(patient_id),
                              doctor_id        NUMBER REFERENCES doctors(doctor_id),
                              appointment_date DATE NOT NULL,
                              status           VARCHAR2(30) DEFAULT 'SCHEDULED',
                              notes            VARCHAR2(500)
);

-- 5. Admissions Table (Admission Form / Report)
CREATE TABLE admissions (
                            admission_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            patient_id     NUMBER REFERENCES patients(patient_id),
                            admission_date DATE DEFAULT SYSDATE,
                            discharge_date DATE,
                            room_number    VARCHAR2(20),
                            condition_desc VARCHAR2(500)
);

-- 6. Clinical Visits Table
CREATE TABLE visits (
                        visit_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        patient_id     NUMBER REFERENCES patients(patient_id),
                        doctor_id      NUMBER REFERENCES doctors(doctor_id),
                        visit_date     DATE DEFAULT SYSDATE,
                        diagnosis      CLOB,
                        prescription   CLOB
);

-- 7. Prescription Items Table
CREATE TABLE prescription_items (
                                    item_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    visit_id       NUMBER REFERENCES visits(visit_id),
                                    medicine_id    NUMBER REFERENCES medicines(medicine_id),
                                    dosage         VARCHAR2(100),
                                    quantity       NUMBER(5)
);

COMMIT;