--Create the traffic signals table and set RED as the default state
CREATE TABLE traffic_signals (
    signal_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_name     VARCHAR2(100) NOT NULL,
    state           VARCHAR2(10) DEFAULT 'RED' NOT NULL
                    CONSTRAINT ck_signal_state
                    CHECK (state IN ('RED','YELLOW','GREEN')),
    last_changed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
-- Check the current signal state and update it when the required time has passed
CREATE OR REPLACE PROCEDURE CHECK_AND_UPDATE_SIGNAL_STATUS ( P_SIGNAL_ID IN NUMBER )
AS
    V_STATE VARCHAR2(10);
    V_LAST_CHANGED_AT TIMESTAMP;
    V_NEXT_STATE VARCHAR2(10);
    V_REQUIRED_SECONDS NUMBER;
BEGIN

    SELECT state  , last_changed_at  
    INTO V_STATE  , V_LAST_CHANGED_AT  
    FROM traffic_signals
    WHERE signal_id = P_SIGNAL_ID;

    IF V_STATE = 'RED' THEN
        V_NEXT_STATE := 'YELLOW'; V_REQUIRED_SECONDS := 10;

    ELSIF V_STATE = 'YELLOW' THEN
        V_NEXT_STATE := 'GREEN'; V_REQUIRED_SECONDS := 5;

    ELSE
        V_NEXT_STATE := 'RED'; V_REQUIRED_SECONDS := 10;
    END IF;

    IF SYSTIMESTAMP >= V_LAST_CHANGED_AT + NUMTODSINTERVAL(V_REQUIRED_SECONDS, 'SECOND')
    THEN

        UPDATE traffic_signals SET state = V_NEXT_STATE, last_changed_at = SYSTIMESTAMP WHERE signal_id = P_SIGNAL_ID;

    END IF;
    COMMIT;

END CHECK_AND_UPDATE_SIGNAL_STATUS;
/

--Create and start an independent scheduler job for a specific traffic signal

CREATE OR REPLACE PROCEDURE START_SIGNAL_WATCH ( P_SIGNAL_ID IN NUMBER )
AS
    V_JOB_NAME VARCHAR2(100);

    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN

    V_JOB_NAME := 'SIG_WATCH_' || P_SIGNAL_ID;

    DBMS_SCHEDULER.CREATE_JOB(
        job_name        => V_JOB_NAME,
        job_type        => 'PLSQL_BLOCK',
        job_action      => 'BEGIN CHECK_AND_UPDATE_SIGNAL_STATUS(' || P_SIGNAL_ID || '); END;',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=SECONDLY;INTERVAL=5',
        enabled         => TRUE
    );

    COMMIT;

END START_SIGNAL_WATCH;
/

--- Row-level trigger to automatically start the signal scheduler after a new signal is inserted

CREATE OR REPLACE TRIGGER TRG_START_SIGNAL_WATCH
AFTER INSERT ON traffic_signals
FOR EACH ROW
BEGIN

    START_SIGNAL_WATCH(:NEW.signal_id);

END TRG_START_SIGNAL_WATCH;
/

---Insert a new traffic signals to test the automatic signal cycle

INSERT INTO traffic_signals (signal_name) VALUES ('Al Khoudh Signal');
INSERT INTO traffic_signals (signal_name) VALUES ('Ghala Signal');
INSERT INTO traffic_signals (signal_name) VALUES ('Al Khuwair Signal');
INSERT INTO traffic_signals (signal_name) VALUES ('Seeb Signal');
COMMIT;

--Verify the current state and last change time of the traffic signals

SELECT signal_id, signal_name, state, last_changed_at FROM traffic_signals;

 --Verify that a scheduler job was automatically created for each signal
 
SELECT job_name, enabled, state, repeat_interval FROM user_scheduler_jobs WHERE job_name LIKE 'SIG_WATCH_%';