CREATE TABLE "ADMISSIONS"
(	"ADMISSION_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
     "PATIENT_ID" NUMBER NOT NULL ENABLE,
     "DOCTOR_ID" NUMBER NOT NULL ENABLE,
     "ROOM_ID" NUMBER NOT NULL ENABLE,
     "ADMISSION_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
     "DISCHARGE_DATE" DATE,
     "ADMISSION_REASON" VARCHAR2(300),
     "STATUS" VARCHAR2(15) DEFAULT 'Admitted' NOT NULL ENABLE,
     CONSTRAINT "CK_ADMISSION_STATUS" CHECK (status IN ('Admitted','Discharged')) ENABLE,
     CONSTRAINT "CK_ADMISSION_DISCHARGE" CHECK (
         (status = 'Discharged' AND discharge_date IS NOT NULL)
             OR (status = 'Admitted')
         ) ENABLE,
     PRIMARY KEY ("ADMISSION_ID")
         USING INDEX  ENABLE
) ;

CREATE TABLE "APPOINTMENTS"
(	"APPOINTMENT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
     "PATIENT_ID" NUMBER NOT NULL ENABLE,
     "DOCTOR_ID" NUMBER NOT NULL ENABLE,
     "APPOINTMENT_DATE" DATE NOT NULL ENABLE,
     "APPOINTMENT_TIME" VARCHAR2(10),
     "STATUS_ID" NUMBER NOT NULL ENABLE,
     "REASON_FOR_VISIT" VARCHAR2(300),
     "CREATED_AT" DATE DEFAULT SYSDATE NOT NULL ENABLE,
     PRIMARY KEY ("APPOINTMENT_ID")
         USING INDEX  ENABLE
) ;

CREATE TABLE "APPOINTMENT_STATUSES"
(	"STATUS_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
     "STATUS_NAME" VARCHAR2(20) NOT NULL ENABLE,
     PRIMARY KEY ("STATUS_ID")
         USING INDEX  ENABLE,
     CONSTRAINT "UQ_APPT_STATUS_NAME" UNIQUE ("STATUS_NAME")
         USING INDEX  ENABLE
) ;

CREATE TABLE "DEPARTMENTS"
(	"DEPARTMENT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
     "DEPARTMENT_NAME" VARCHAR2(100) NOT NULL ENABLE,
     "FLOOR_NO" VARCHAR2(20),
     "STATUS" VARCHAR2(10) DEFAULT 'Active' NOT NULL ENABLE,
     CONSTRAINT "CK_DEPARTMENTS_STATUS" CHECK (status IN ('Active','Inactive')) ENABLE,
     PRIMARY KEY ("DEPARTMENT_ID")
         USING INDEX  ENABLE
) ;

CREATE TABLE "DOCTORS"
(	"DOCTOR_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
     "FULL_NAME" VARCHAR2(150) NOT NULL ENABLE,
     "DEPARTMENT_ID" NUMBER NOT NULL ENABLE,
     "SPECIALTY_ID" NUMBER NOT NULL ENABLE,
     "MOBILE_NO" VARCHAR2(20),
     "EMAIL" VARCHAR2(150),
     "CONSULTATION_FEE" NUMBER(8,2),
     "STATUS" VARCHAR2(10) DEFAULT 'Active' NOT NULL ENABLE,
     CONSTRAINT "CK_DOCTORS_STATUS" CHECK (status IN ('Active','Inactive')) ENABLE,
     PRIMARY KEY ("DOCTOR_ID")
         USING INDEX  ENABLE
) ;

CREATE TABLE "DOCTOR_SPECIALTIES"
(	"SPECIALTY_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
     "SPECIALTY_NAME" VARCHAR2(100) NOT NULL ENABLE,
     "STATUS" VARCHAR2(10) DEFAULT 'Active' NOT NULL ENABLE,
     CONSTRAINT "CK_SPECIALTIES_STATUS" CHECK (status IN ('Active','Inactive')) ENABLE,
     PRIMARY KEY ("SPECIALTY_ID")
         USING INDEX  ENABLE
) ;

CREATE TABLE "MEDICINES"
(	"MEDICINE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
     "MEDICINE_NAME" VARCHAR2(150) NOT NULL ENABLE,
     "CATEGORY_ID" NUMBER NOT NULL ENABLE,
     "UNIT" VARCHAR2(30),
     "CURRENT_STOCK" NUMBER DEFAULT 0 NOT NULL ENABLE,
     "REORDER_LEVEL" NUMBER DEFAULT 0 NOT NULL ENABLE,
     "STATUS" VARCHAR2(10) DEFAULT 'Active' NOT NULL ENABLE,
     CONSTRAINT "CK_MEDICINES_STATUS" CHECK (status IN ('Active','Inactive')) ENABLE,
     CONSTRAINT "CK_MEDICINES_STOCK_NONNEG" CHECK (current_stock >= 0) ENABLE,
     PRIMARY KEY ("MEDICINE_ID")
         USING INDEX  ENABLE
) ;

CREATE TABLE "MEDICINE_CATEGORIES"
(	"CATEGORY_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
     "CATEGORY_NAME" VARCHAR2(100) NOT NULL ENABLE,
     "STATUS" VARCHAR2(10) DEFAULT 'Active' NOT NULL ENABLE,
     CONSTRAINT "CK_MEDCAT_STATUS" CHECK (status IN ('Active','Inactive')) ENABLE,
     PRIMARY KEY ("CATEGORY_ID")
         USING INDEX  ENABLE
) ;

CREATE TABLE "PATIENTS"
(	"PATIENT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
     "CIVIL_ID" VARCHAR2(30) NOT NULL ENABLE,
     "FULL_NAME" VARCHAR2(150) NOT NULL ENABLE,
     "GENDER" VARCHAR2(10),
     "DATE_OF_BIRTH" DATE,
     "MOBILE_NO" VARCHAR2(20) NOT NULL ENABLE,
     "EMAIL" VARCHAR2(150),
     "BLOOD_GROUP" VARCHAR2(5),
     "ADDRESS" VARCHAR2(300),
     "EMERGENCY_CONTACT_NAME" VARCHAR2(150),
     "EMERGENCY_CONTACT_NO" VARCHAR2(20),
     "CREATED_AT" DATE DEFAULT SYSDATE NOT NULL ENABLE,
     CONSTRAINT "CK_PATIENTS_GENDER" CHECK (gender IN ('Male','Female')) ENABLE,
     CONSTRAINT "CK_PATIENTS_BLOOD_GROUP" CHECK (
         blood_group IN ('A+','A-','B+','B-','O+','O-','AB+','AB-')
         ) ENABLE,
     PRIMARY KEY ("PATIENT_ID")
         USING INDEX  ENABLE,
     CONSTRAINT "UQ_PATIENTS_CIVIL_ID" UNIQUE ("CIVIL_ID")
         USING INDEX  ENABLE
) ;

CREATE TABLE "PATIENT_VISITS"
(	"VISIT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
     "APPOINTMENT_ID" NUMBER NOT NULL ENABLE,
     "PATIENT_ID" NUMBER NOT NULL ENABLE,
     "DOCTOR_ID" NUMBER NOT NULL ENABLE,
     "VISIT_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
     "SYMPTOMS" VARCHAR2(500),
     "DIAGNOSIS" VARCHAR2(500),
     "NOTES" VARCHAR2(1000),
     "FOLLOW_UP_DATE" DATE,
     PRIMARY KEY ("VISIT_ID")
         USING INDEX  ENABLE
) ;

CREATE TABLE "PRESCRIPTIONS"
(	"PRESCRIPTION_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
     "VISIT_ID" NUMBER NOT NULL ENABLE,
     "PATIENT_ID" NUMBER NOT NULL ENABLE,
     "DOCTOR_ID" NUMBER NOT NULL ENABLE,
     "PRESCRIPTION_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
     "NOTES" VARCHAR2(500),
     PRIMARY KEY ("PRESCRIPTION_ID")
         USING INDEX  ENABLE
) ;

CREATE TABLE "PRESCRIPTION_ITEMS"
(	"PRESCRIPTION_ITEM_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
     "PRESCRIPTION_ID" NUMBER NOT NULL ENABLE,
     "MEDICINE_ID" NUMBER NOT NULL ENABLE,
     "DOSAGE" VARCHAR2(50),
     "FREQUENCY" VARCHAR2(50),
     "DURATION_DAYS" NUMBER,
     "INSTRUCTIONS" VARCHAR2(300),
     PRIMARY KEY ("PRESCRIPTION_ITEM_ID")
         USING INDEX  ENABLE
) ;

CREATE TABLE "ROOMS"
(	"ROOM_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
     "ROOM_NO" VARCHAR2(20) NOT NULL ENABLE,
     "ROOM_TYPE" VARCHAR2(20) NOT NULL ENABLE,
     "DAILY_RATE" NUMBER(8,2),
     "STATUS" VARCHAR2(15) DEFAULT 'Available' NOT NULL ENABLE,
     CONSTRAINT "CK_ROOMS_TYPE" CHECK (room_type IN ('General','Private','ICU')) ENABLE,
     CONSTRAINT "CK_ROOMS_STATUS" CHECK (status IN ('Available','Occupied','Maintenance')) ENABLE,
     PRIMARY KEY ("ROOM_ID")
         USING INDEX  ENABLE,
     CONSTRAINT "UQ_ROOMS_ROOM_NO" UNIQUE ("ROOM_NO")
         USING INDEX  ENABLE
) ;

ALTER TABLE "ADMISSIONS" ADD CONSTRAINT "FK_ADMISSION_PATIENT" FOREIGN KEY ("PATIENT_ID")
    REFERENCES "PATIENTS" ("PATIENT_ID") ENABLE;
ALTER TABLE "ADMISSIONS" ADD CONSTRAINT "FK_ADMISSION_DOCTOR" FOREIGN KEY ("DOCTOR_ID")
    REFERENCES "DOCTORS" ("DOCTOR_ID") ENABLE;
ALTER TABLE "ADMISSIONS" ADD CONSTRAINT "FK_ADMISSION_ROOM" FOREIGN KEY ("ROOM_ID")
    REFERENCES "ROOMS" ("ROOM_ID") ENABLE;

CREATE INDEX "IX_ADMISSIONS_PATIENT" ON "ADMISSIONS" ("PATIENT_ID")
;

CREATE INDEX "IX_ADMISSIONS_DOCTOR" ON "ADMISSIONS" ("DOCTOR_ID")
;

CREATE INDEX "IX_ADMISSIONS_ROOM" ON "ADMISSIONS" ("ROOM_ID")
;

CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_ADMISSIONS_ROOM_STATUS"
AFTER INSERT OR UPDATE OF STATUS ON ADMISSIONS
    FOR EACH ROW
BEGIN
  IF :NEW.STATUS = 'Admitted' THEN
UPDATE ROOMS SET STATUS = 'Occupied' WHERE ROOM_ID = :NEW.ROOM_ID;
ELSIF :NEW.STATUS = 'Discharged' THEN
UPDATE ROOMS SET STATUS = 'Available' WHERE ROOM_ID = :NEW.ROOM_ID;
END IF;
END;
/
ALTER TRIGGER "TRG_ADMISSIONS_ROOM_STATUS" ENABLE;

ALTER TABLE "APPOINTMENTS" ADD CONSTRAINT "FK_APPT_PATIENT" FOREIGN KEY ("PATIENT_ID")
    REFERENCES "PATIENTS" ("PATIENT_ID") ENABLE;
ALTER TABLE "APPOINTMENTS" ADD CONSTRAINT "FK_APPT_DOCTOR" FOREIGN KEY ("DOCTOR_ID")
    REFERENCES "DOCTORS" ("DOCTOR_ID") ENABLE;
ALTER TABLE "APPOINTMENTS" ADD CONSTRAINT "FK_APPT_STATUS" FOREIGN KEY ("STATUS_ID")
    REFERENCES "APPOINTMENT_STATUSES" ("STATUS_ID") ENABLE;

CREATE INDEX "IX_APPT_DOCTOR" ON "APPOINTMENTS" ("DOCTOR_ID")
;

CREATE INDEX "IX_APPT_STATUS" ON "APPOINTMENTS" ("STATUS_ID")
;

CREATE INDEX "IX_APPT_PATIENT" ON "APPOINTMENTS" ("PATIENT_ID")
;

ALTER TABLE "DOCTORS" ADD CONSTRAINT "FK_DOCTORS_DEPARTMENT" FOREIGN KEY ("DEPARTMENT_ID")
    REFERENCES "DEPARTMENTS" ("DEPARTMENT_ID") ENABLE;
ALTER TABLE "DOCTORS" ADD CONSTRAINT "FK_DOCTORS_SPECIALTY" FOREIGN KEY ("SPECIALTY_ID")
    REFERENCES "DOCTOR_SPECIALTIES" ("SPECIALTY_ID") ENABLE;

CREATE INDEX "IX_DOCTORS_DEPARTMENT" ON "DOCTORS" ("DEPARTMENT_ID")
;

CREATE INDEX "IX_DOCTORS_SPECIALTY" ON "DOCTORS" ("SPECIALTY_ID")
;

ALTER TABLE "MEDICINES" ADD CONSTRAINT "FK_MEDICINES_CATEGORY" FOREIGN KEY ("CATEGORY_ID")
    REFERENCES "MEDICINE_CATEGORIES" ("CATEGORY_ID") ENABLE;

CREATE INDEX "IX_MEDICINES_CATEGORY" ON "MEDICINES" ("CATEGORY_ID")
;

ALTER TABLE "PATIENT_VISITS" ADD CONSTRAINT "FK_VISIT_APPOINTMENT" FOREIGN KEY ("APPOINTMENT_ID")
    REFERENCES "APPOINTMENTS" ("APPOINTMENT_ID") ENABLE;
ALTER TABLE "PATIENT_VISITS" ADD CONSTRAINT "FK_VISIT_PATIENT" FOREIGN KEY ("PATIENT_ID")
    REFERENCES "PATIENTS" ("PATIENT_ID") ENABLE;
ALTER TABLE "PATIENT_VISITS" ADD CONSTRAINT "FK_VISIT_DOCTOR" FOREIGN KEY ("DOCTOR_ID")
    REFERENCES "DOCTORS" ("DOCTOR_ID") ENABLE;

CREATE INDEX "IX_VISITS_APPOINTMENT" ON "PATIENT_VISITS" ("APPOINTMENT_ID")
;

CREATE INDEX "IX_VISITS_DOCTOR" ON "PATIENT_VISITS" ("DOCTOR_ID")
;

CREATE INDEX "IX_VISITS_PATIENT" ON "PATIENT_VISITS" ("PATIENT_ID")
;

ALTER TABLE "PRESCRIPTIONS" ADD CONSTRAINT "FK_PRESC_VISIT" FOREIGN KEY ("VISIT_ID")
    REFERENCES "PATIENT_VISITS" ("VISIT_ID") ENABLE;
ALTER TABLE "PRESCRIPTIONS" ADD CONSTRAINT "FK_PRESC_PATIENT" FOREIGN KEY ("PATIENT_ID")
    REFERENCES "PATIENTS" ("PATIENT_ID") ENABLE;
ALTER TABLE "PRESCRIPTIONS" ADD CONSTRAINT "FK_PRESC_DOCTOR" FOREIGN KEY ("DOCTOR_ID")
    REFERENCES "DOCTORS" ("DOCTOR_ID") ENABLE;

CREATE INDEX "IX_PRESC_DOCTOR" ON "PRESCRIPTIONS" ("DOCTOR_ID")
;

CREATE INDEX "IX_PRESC_VISIT" ON "PRESCRIPTIONS" ("VISIT_ID")
;

CREATE INDEX "IX_PRESC_PATIENT" ON "PRESCRIPTIONS" ("PATIENT_ID")
;

ALTER TABLE "PRESCRIPTION_ITEMS" ADD CONSTRAINT "FK_ITEM_PRESCRIPTION" FOREIGN KEY ("PRESCRIPTION_ID")
    REFERENCES "PRESCRIPTIONS" ("PRESCRIPTION_ID") ENABLE;
ALTER TABLE "PRESCRIPTION_ITEMS" ADD CONSTRAINT "FK_ITEM_MEDICINE" FOREIGN KEY ("MEDICINE_ID")
    REFERENCES "MEDICINES" ("MEDICINE_ID") ENABLE;

CREATE INDEX "IX_ITEMS_PRESCRIPTION" ON "PRESCRIPTION_ITEMS" ("PRESCRIPTION_ID")
;

CREATE INDEX "IX_ITEMS_MEDICINE" ON "PRESCRIPTION_ITEMS" ("MEDICINE_ID")
;





























































CREATE INDEX "IX_APPT_DOCTOR" ON "APPOINTMENTS" ("DOCTOR_ID")
;

CREATE INDEX "IX_APPT_STATUS" ON "APPOINTMENTS" ("STATUS_ID")
;

CREATE INDEX "IX_VISITS_APPOINTMENT" ON "PATIENT_VISITS" ("APPOINTMENT_ID")
;

CREATE INDEX "IX_VISITS_DOCTOR" ON "PATIENT_VISITS" ("DOCTOR_ID")
;

CREATE UNIQUE INDEX "SYS_C0014101" ON "ROOMS" ("ROOM_ID")
;

CREATE INDEX "IX_PRESC_DOCTOR" ON "PRESCRIPTIONS" ("DOCTOR_ID")
;

CREATE UNIQUE INDEX "SYS_C0014127" ON "PRESCRIPTIONS" ("PRESCRIPTION_ID")
;

CREATE INDEX "IX_PRESC_VISIT" ON "PRESCRIPTIONS" ("VISIT_ID")
;

CREATE UNIQUE INDEX "SYS_C0014109" ON "APPOINTMENTS" ("APPOINTMENT_ID")
;

CREATE UNIQUE INDEX "SYS_C0014134" ON "PRESCRIPTION_ITEMS" ("PRESCRIPTION_ITEM_ID")
;

CREATE UNIQUE INDEX "SYS_C0014145" ON "ADMISSIONS" ("ADMISSION_ID")
;

CREATE INDEX "IX_ADMISSIONS_PATIENT" ON "ADMISSIONS" ("PATIENT_ID")
;

CREATE INDEX "IX_PRESC_PATIENT" ON "PRESCRIPTIONS" ("PATIENT_ID")
;

CREATE INDEX "IX_APPT_PATIENT" ON "APPOINTMENTS" ("PATIENT_ID")
;

CREATE INDEX "IX_ADMISSIONS_DOCTOR" ON "ADMISSIONS" ("DOCTOR_ID")
;

CREATE UNIQUE INDEX "SYS_C0014082" ON "DOCTORS" ("DOCTOR_ID")
;

CREATE INDEX "IX_MEDICINES_CATEGORY" ON "MEDICINES" ("CATEGORY_ID")
;

CREATE UNIQUE INDEX "UQ_PATIENTS_CIVIL_ID" ON "PATIENTS" ("CIVIL_ID")
;

CREATE UNIQUE INDEX "SYS_C0014118" ON "PATIENT_VISITS" ("VISIT_ID")
;

CREATE INDEX "IX_ADMISSIONS_ROOM" ON "ADMISSIONS" ("ROOM_ID")
;

CREATE INDEX "IX_ITEMS_PRESCRIPTION" ON "PRESCRIPTION_ITEMS" ("PRESCRIPTION_ID")
;

CREATE UNIQUE INDEX "SYS_C0014052" ON "DEPARTMENTS" ("DEPARTMENT_ID")
;

CREATE UNIQUE INDEX "SYS_C0014062" ON "MEDICINE_CATEGORIES" ("CATEGORY_ID")
;

CREATE INDEX "IX_ITEMS_MEDICINE" ON "PRESCRIPTION_ITEMS" ("MEDICINE_ID")
;

CREATE INDEX "IX_VISITS_PATIENT" ON "PATIENT_VISITS" ("PATIENT_ID")
;

CREATE UNIQUE INDEX "SYS_C0014057" ON "DOCTOR_SPECIALTIES" ("SPECIALTY_ID")
;

CREATE UNIQUE INDEX "SYS_C0014074" ON "PATIENTS" ("PATIENT_ID")
;

CREATE INDEX "IX_DOCTORS_DEPARTMENT" ON "DOCTORS" ("DEPARTMENT_ID")
;

CREATE UNIQUE INDEX "SYS_C0014065" ON "APPOINTMENT_STATUSES" ("STATUS_ID")
;

CREATE UNIQUE INDEX "SYS_C0014093" ON "MEDICINES" ("MEDICINE_ID")
;

CREATE UNIQUE INDEX "UQ_APPT_STATUS_NAME" ON "APPOINTMENT_STATUSES" ("STATUS_NAME")
;

CREATE INDEX "IX_DOCTORS_SPECIALTY" ON "DOCTORS" ("SPECIALTY_ID")
;

CREATE UNIQUE INDEX "UQ_ROOMS_ROOM_NO" ON "ROOMS" ("ROOM_NO")
;





















































































































































































create or replace TRIGGER trg_admissions_room_status
AFTER INSERT OR UPDATE OF STATUS ON ADMISSIONS
    FOR EACH ROW
BEGIN
  IF :NEW.STATUS = 'Admitted' THEN
UPDATE ROOMS SET STATUS = 'Occupied' WHERE ROOM_ID = :NEW.ROOM_ID;
ELSIF :NEW.STATUS = 'Discharged' THEN
UPDATE ROOMS SET STATUS = 'Available' WHERE ROOM_ID = :NEW.ROOM_ID;
END IF;
END;
/

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_ADMISSIONS_ROOM_STATUS"
AFTER INSERT OR UPDATE OF STATUS ON ADMISSIONS
    FOR EACH ROW
BEGIN
  IF :NEW.STATUS = 'Admitted' THEN
UPDATE ROOMS SET STATUS = 'Occupied' WHERE ROOM_ID = :NEW.ROOM_ID;
ELSIF :NEW.STATUS = 'Discharged' THEN
UPDATE ROOMS SET STATUS = 'Available' WHERE ROOM_ID = :NEW.ROOM_ID;
END IF;
END;
/
ALTER TRIGGER "TRG_ADMISSIONS_ROOM_STATUS" ENABLE;






























































CREATE UNIQUE INDEX "SYS_C0014145" ON "ADMISSIONS" ("ADMISSION_ID")
;
CREATE INDEX "IX_ADMISSIONS_PATIENT" ON "ADMISSIONS" ("PATIENT_ID")
;
CREATE INDEX "IX_ADMISSIONS_DOCTOR" ON "ADMISSIONS" ("DOCTOR_ID")
;
CREATE INDEX "IX_ADMISSIONS_ROOM" ON "ADMISSIONS" ("ROOM_ID")
;

CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_ADMISSIONS_ROOM_STATUS"
AFTER INSERT OR UPDATE OF STATUS ON ADMISSIONS
    FOR EACH ROW
BEGIN
  IF :NEW.STATUS = 'Admitted' THEN
UPDATE ROOMS SET STATUS = 'Occupied' WHERE ROOM_ID = :NEW.ROOM_ID;
ELSIF :NEW.STATUS = 'Discharged' THEN
UPDATE ROOMS SET STATUS = 'Available' WHERE ROOM_ID = :NEW.ROOM_ID;
END IF;
END;
/
ALTER TRIGGER "TRG_ADMISSIONS_ROOM_STATUS" ENABLE;

CREATE UNIQUE INDEX "SYS_C0014109" ON "APPOINTMENTS" ("APPOINTMENT_ID")
;
CREATE INDEX "IX_APPT_PATIENT" ON "APPOINTMENTS" ("PATIENT_ID")
;
CREATE INDEX "IX_APPT_DOCTOR" ON "APPOINTMENTS" ("DOCTOR_ID")
;
CREATE INDEX "IX_APPT_STATUS" ON "APPOINTMENTS" ("STATUS_ID")
;

CREATE UNIQUE INDEX "SYS_C0014065" ON "APPOINTMENT_STATUSES" ("STATUS_ID")
;
CREATE UNIQUE INDEX "UQ_APPT_STATUS_NAME" ON "APPOINTMENT_STATUSES" ("STATUS_NAME")
;

CREATE UNIQUE INDEX "SYS_C0014052" ON "DEPARTMENTS" ("DEPARTMENT_ID")
;

CREATE UNIQUE INDEX "SYS_C0014082" ON "DOCTORS" ("DOCTOR_ID")
;
CREATE INDEX "IX_DOCTORS_DEPARTMENT" ON "DOCTORS" ("DEPARTMENT_ID")
;
CREATE INDEX "IX_DOCTORS_SPECIALTY" ON "DOCTORS" ("SPECIALTY_ID")
;

CREATE UNIQUE INDEX "SYS_C0014057" ON "DOCTOR_SPECIALTIES" ("SPECIALTY_ID")
;

CREATE UNIQUE INDEX "SYS_C0014093" ON "MEDICINES" ("MEDICINE_ID")
;
CREATE INDEX "IX_MEDICINES_CATEGORY" ON "MEDICINES" ("CATEGORY_ID")
;

CREATE UNIQUE INDEX "SYS_C0014062" ON "MEDICINE_CATEGORIES" ("CATEGORY_ID")
;

CREATE UNIQUE INDEX "SYS_C0014074" ON "PATIENTS" ("PATIENT_ID")
;
CREATE UNIQUE INDEX "UQ_PATIENTS_CIVIL_ID" ON "PATIENTS" ("CIVIL_ID")
;

CREATE UNIQUE INDEX "SYS_C0014118" ON "PATIENT_VISITS" ("VISIT_ID")
;
CREATE INDEX "IX_VISITS_APPOINTMENT" ON "PATIENT_VISITS" ("APPOINTMENT_ID")
;
CREATE INDEX "IX_VISITS_PATIENT" ON "PATIENT_VISITS" ("PATIENT_ID")
;
CREATE INDEX "IX_VISITS_DOCTOR" ON "PATIENT_VISITS" ("DOCTOR_ID")
;

CREATE UNIQUE INDEX "SYS_C0014127" ON "PRESCRIPTIONS" ("PRESCRIPTION_ID")
;
CREATE INDEX "IX_PRESC_VISIT" ON "PRESCRIPTIONS" ("VISIT_ID")
;
CREATE INDEX "IX_PRESC_PATIENT" ON "PRESCRIPTIONS" ("PATIENT_ID")
;
CREATE INDEX "IX_PRESC_DOCTOR" ON "PRESCRIPTIONS" ("DOCTOR_ID")
;

CREATE UNIQUE INDEX "SYS_C0014134" ON "PRESCRIPTION_ITEMS" ("PRESCRIPTION_ITEM_ID")
;
CREATE INDEX "IX_ITEMS_PRESCRIPTION" ON "PRESCRIPTION_ITEMS" ("PRESCRIPTION_ID")
;
CREATE INDEX "IX_ITEMS_MEDICINE" ON "PRESCRIPTION_ITEMS" ("MEDICINE_ID")
;

CREATE UNIQUE INDEX "SYS_C0014101" ON "ROOMS" ("ROOM_ID")
;
CREATE UNIQUE INDEX "UQ_ROOMS_ROOM_NO" ON "ROOMS" ("ROOM_NO")
;























































































































