CREATE TABLE traffic_signals (
                                 signal_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 signal_name     VARCHAR2(100) NOT NULL,
                                 state           VARCHAR2(10) DEFAULT 'RED' NOT NULL
                  CONSTRAINT ck_signal_state CHECK (state IN ('RED','YELLOW','GREEN')),
                                 last_changed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
/

CREATE OR REPLACE PROCEDURE advance_traffic_signal(p_signal_id IN NUMBER) IS
  PRAGMA AUTONOMOUS_TRANSACTION;

  v_state         VARCHAR2(10);
  v_last_changed  TIMESTAMP;
  v_elapsed_secs  NUMBER;
  v_required_secs NUMBER;
  v_next_state    VARCHAR2(10);
BEGIN
SELECT state, last_changed_at
INTO v_state, v_last_changed
FROM traffic_signals
WHERE signal_id = p_signal_id
    FOR UPDATE;

v_elapsed_secs :=
      EXTRACT(DAY    FROM (SYSTIMESTAMP - v_last_changed)) * 86400
    + EXTRACT(HOUR   FROM (SYSTIMESTAMP - v_last_changed)) * 3600
    + EXTRACT(MINUTE FROM (SYSTIMESTAMP - v_last_changed)) * 60
    + EXTRACT(SECOND FROM (SYSTIMESTAMP - v_last_changed));

  v_required_secs := CASE v_state
                        WHEN 'RED'    THEN 10
                        WHEN 'YELLOW' THEN 5
                        WHEN 'GREEN'  THEN 10
END;

  IF v_elapsed_secs >= v_required_secs THEN
    v_next_state := CASE v_state
                       WHEN 'RED'    THEN 'YELLOW'
                       WHEN 'YELLOW' THEN 'GREEN'
                       WHEN 'GREEN'  THEN 'RED'
END;

UPDATE traffic_signals
SET state           = v_next_state,
    last_changed_at = SYSTIMESTAMP
WHERE signal_id = p_signal_id;
END IF;

COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END advance_traffic_signal;
/

CREATE OR REPLACE PROCEDURE start_signal_cycle(p_signal_id IN NUMBER) IS
  PRAGMA AUTONOMOUS_TRANSACTION;
  v_job_name VARCHAR2(128) := 'SIG_CYCLE_' || p_signal_id;
BEGIN
  DBMS_SCHEDULER.CREATE_JOB(
    job_name            => v_job_name,
    job_type            => 'STORED_PROCEDURE',
    job_action          => 'ADVANCE_TRAFFIC_SIGNAL',
    number_of_arguments => 1,
    start_date          => SYSTIMESTAMP,
    repeat_interval     => 'FREQ=SECONDLY;INTERVAL=1',
    enabled             => FALSE,
    comments            => 'Auto-cycle job for traffic_signals.signal_id = ' || p_signal_id
  );

  DBMS_SCHEDULER.SET_JOB_ARGUMENT_VALUE(
    job_name          => v_job_name,
    argument_position => 1,
    argument_value    => p_signal_id
  );

  DBMS_SCHEDULER.ENABLE(v_job_name);

COMMIT;
END start_signal_cycle;
/

CREATE OR REPLACE TRIGGER trg_signal_start_cycle
AFTER INSERT ON traffic_signals
FOR EACH ROW
BEGIN
  start_signal_cycle(:NEW.signal_id);
END trg_signal_start_cycle;
/

CREATE OR REPLACE PROCEDURE stop_traffic_signal(p_signal_id IN NUMBER) IS
  v_job_name VARCHAR2(128) := 'SIG_CYCLE_' || p_signal_id;
BEGIN
BEGIN
    DBMS_SCHEDULER.STOP_JOB(v_job_name);
EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE NOT IN (-27366, -27475) THEN
        RAISE;
END IF;
END;

BEGIN
    DBMS_SCHEDULER.DROP_JOB(v_job_name);
EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -27475 THEN
        RAISE;
END IF;
END;
END stop_traffic_signal;
/

INSERT INTO traffic_signals (signal_name) VALUES ('Main and 1st');
COMMIT;

INSERT INTO traffic_signals (signal_name) VALUES ('Main and 2nd');
COMMIT;

SELECT signal_id, signal_name, state, last_changed_at,
       EXTRACT(DAY    FROM (SYSTIMESTAMP - last_changed_at)) * 86400
           + EXTRACT(HOUR   FROM (SYSTIMESTAMP - last_changed_at)) * 3600
           + EXTRACT(MINUTE FROM (SYSTIMESTAMP - last_changed_at)) * 60
           + EXTRACT(SECOND FROM (SYSTIMESTAMP - last_changed_at)) AS secs_in_state
FROM traffic_signals
ORDER BY signal_id;

EXEC stop_traffic_signal(1);

SELECT signal_id, signal_name, state, last_changed_at
FROM traffic_signals;

SELECT job_name, state, next_run_date
FROM user_scheduler_jobs
WHERE job_name LIKE 'SIG_CYCLE_%';