services:
  api:
    build: ./healthcheck
    container_name: upload-app
    ports:
      - "8080:8080"
    volumes:
      # Windows: C:/shared_upload_files:/app/uploaded_files
      - ./shared_upload_files:/app/uploaded_files
