create table traffic_signals (
    signal_id number GENERATED by default as identity PRIMARY KEY,
    signal_name varchar2(50) not null,
    signal_state VARCHAR2(10) default 'RED' not null,
    last_changed_at timestamp default systimestamp not null
);

create or replace procedure start_signal_watch ( p_signal_id in number ) as
    PRAGMA autonomous_transaction;
begin
    dbms_output.put_line('To Do');
    dbms_scheduler.create_job(job_name => 'sig_watch' || p_signal_id, job_type => 'PLSQL_BLOCK',job_action => 'begin check_and_update_signal_status(' || p_signal_id || '); END;',
    repeat_interval => 'FREQ=SECONDLY; INTERVAL=5',
    start_date => systimestamp,
    enabled => true
    );
    COMMIT;
end start_signal_watch;

create or replace procedure check_and_update_signal_status (p_signal_id in number)
as 
    v_state varchar2;
    v_last_changed_at timestamp;
    v_next_state varchar2;
    v_required_seconds number;
begin
    dbms_output.put_line('Checking and Updating signal status for signal with ID: ' || p_signal_id);
    select signal_state, last_changed_at into v_state, v_last_changed_at from traffic_signals where signal_id = p_signal_id;
    if v_state = 'RED' then
       v_next_state := 'YELLOW'; v_required_seconds := 10;
    elsif v_state = 'YELLOW' then
        v_next_state := 'GREEN'; v_required_seconds := 5;
    else
        v_next_state := 'RED'; v_required_seconds := 5;
    end if;
    
    IF SYSTIMESTAMP >= v_last_changed_at + NUMTODSINTERVAL(v_required_seconds, 'SECOND') THEN
        UPDATE traffic_signals SET signal_state = v_next_state, last_changed_at = SYSTIMESTAMP WHERE signal_id = p_signal_id;
        COMMIT;
    END IF;
    dbms_output.put_line('v_state is ' || v_state || 'v_last_changed_at is ' || v_last_changed_at);
end;
/

begin
    check_and_update_signal_status(1);
end;

create or replace trigger handle_traffic_signal_insert_event
after insert on traffic_signals
for each row 
begin
    start_signal_watch(:NEW.signal_id);
end handle_traffic_signal_insert_event;
/

insert into traffic_signals (signal_name) values ('Ghala signal');