
-- =========================================================
-- DEPARTMENTS
-- =========================================================
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, FLOOR_NO, STATUS)
VALUES (1, 'Cardiology', 2, 'Active');
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, FLOOR_NO, STATUS)
VALUES (2, 'Pediatrics', 3, 'Active');
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, FLOOR_NO, STATUS)
VALUES (3, 'Emergency', 1, 'Active');
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, FLOOR_NO, STATUS)
VALUES (4, 'Orthopedics', 4, 'Active');
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, FLOOR_NO, STATUS)
VALUES (5, 'Neurology', 5, 'Active');

-- =========================================================
-- DOCTOR_SPECIALTIES
-- =========================================================
INSERT INTO DOCTOR_SPECIALTIES (SPECIALTY_ID, SPECIALTY_NAME, STATUS)
VALUES (1, 'Cardiologist', 'Active');
INSERT INTO DOCTOR_SPECIALTIES (SPECIALTY_ID, SPECIALTY_NAME, STATUS)
VALUES (2, 'Pediatrician', 'Active');
INSERT INTO DOCTOR_SPECIALTIES (SPECIALTY_ID, SPECIALTY_NAME, STATUS)
VALUES (3, 'Surgeon', 'Active');
INSERT INTO DOCTOR_SPECIALTIES (SPECIALTY_ID, SPECIALTY_NAME, STATUS)
VALUES (4, 'Neurologist', 'Active');
INSERT INTO DOCTOR_SPECIALTIES (SPECIALTY_ID, SPECIALTY_NAME, STATUS)
VALUES (5, 'Orthopedic Specialist', 'Active');
INSERT INTO DOCTOR_SPECIALTIES (SPECIALTY_ID, SPECIALTY_NAME, STATUS)
VALUES (6, 'Dermatologist', 'Active');
INSERT INTO DOCTOR_SPECIALTIES (SPECIALTY_ID, SPECIALTY_NAME, STATUS)
VALUES (7, 'General Physician', 'Active');

-- =========================================================
-- MEDICINE_CATEGORIES
-- =========================================================
INSERT INTO MEDICINE_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, STATUS)
VALUES (1, 'Antibiotic', 'Active');
INSERT INTO MEDICINE_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, STATUS)
VALUES (2, 'Painkiller', 'Active');
INSERT INTO MEDICINE_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, STATUS)
VALUES (3, 'Diabetes', 'Active');
INSERT INTO MEDICINE_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, STATUS)
VALUES (4, 'Vitamin', 'Active');
INSERT INTO MEDICINE_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, STATUS)
VALUES (5, 'Antihistamine', 'Active');

-- =========================================================
-- APPOINTMENT_STATUSES
-- =========================================================
INSERT INTO APPOINTMENT_STATUSES (STATUS_ID, STATUS_NAME)
VALUES (3, 'Cancelled');
INSERT INTO APPOINTMENT_STATUSES (STATUS_ID, STATUS_NAME)
VALUES (2, 'Completed');
INSERT INTO APPOINTMENT_STATUSES (STATUS_ID, STATUS_NAME)
VALUES (4, 'No Show');
INSERT INTO APPOINTMENT_STATUSES (STATUS_ID, STATUS_NAME)
VALUES (1, 'Scheduled');

-- =========================================================
-- PATIENTS
-- =========================================================
INSERT INTO PATIENTS (PATIENT_ID, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT)
VALUES (1, '11111111', 'Ahmed Ali', 'Male', DATE '1990-05-10', '91234567', 'ahmed@example.com', 'O+', 'Muscat', 'Ali Ahmed', '99880011', TO_DATE('2026-07-15 05:51:19','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PATIENTS (PATIENT_ID, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT)
VALUES (2, '11111112', 'Fatima Hassan', 'Female', DATE '1995-02-18', '92345678', 'fatima@example.com', 'A+', 'Seeb', 'Hassan Ali', '99880012', TO_DATE('2026-07-15 05:51:19','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PATIENTS (PATIENT_ID, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT)
VALUES (3, '11111113', 'Mohammed Salim', 'Male', DATE '1988-09-22', '93456789', 'mohammed@example.com', 'B+', 'Barka', 'Salim Mohammed', '99880013', TO_DATE('2026-07-15 05:51:19','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PATIENTS (PATIENT_ID, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT)
VALUES (4, '11111114', 'Aisha Said', 'Female', DATE '1999-11-12', '94567890', 'aisha@example.com', 'AB+', 'Sohar', 'Said Ahmed', '99880014', TO_DATE('2026-07-15 05:51:19','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PATIENTS (PATIENT_ID, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT)
VALUES (5, '11111115', 'Khalid Nasser', 'Male', DATE '1992-01-05', '95678901', 'khalid@example.com', 'O-', 'Nizwa', 'Nasser Khalid', '99880015', TO_DATE('2026-07-15 05:51:19','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PATIENTS (PATIENT_ID, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT)
VALUES (6, '11111116', 'Mariam Rashid', 'Female', DATE '1996-07-14', '96789012', 'mariam@example.com', 'A-', 'Sur', 'Rashid Ali', '99880016', TO_DATE('2026-07-15 05:51:19','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PATIENTS (PATIENT_ID, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT)
VALUES (7, '11111117', 'Yousef Hamad', 'Male', DATE '1985-03-30', '97890123', 'yousef@example.com', 'B-', 'Ibri', 'Hamad Yousef', '99880017', TO_DATE('2026-07-15 05:51:19','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PATIENTS (PATIENT_ID, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT)
VALUES (8, '11111118', 'Noor Abdullah', 'Female', DATE '2000-08-09', '98901234', 'noor@example.com', 'O+', 'Rustaq', 'Abdullah Noor', '99880018', TO_DATE('2026-07-15 05:51:19','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PATIENTS (PATIENT_ID, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT)
VALUES (9, '11111119', 'Sultan Omar', 'Male', DATE '1991-12-20', '99012345', 'sultan@example.com', 'A+', 'Muscat', 'Omar Sultan', '99880019', TO_DATE('2026-07-15 05:51:19','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PATIENTS (PATIENT_ID, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT)
VALUES (10, '11111120', 'Sara Ibrahim', 'Female', DATE '1998-06-01', '90123456', 'sara@example.com', 'AB-', 'Salalah', 'Ibrahim Sara', '99880020', TO_DATE('2026-07-15 05:51:19','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PATIENTS (PATIENT_ID, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT)
VALUES (11, '11111121', 'Huda Al Balushi', 'Female', DATE '1993-04-17', '91110021', 'huda.patient@example.com', 'O+', 'Muscat', 'Salim Al Balushi', '92110021', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PATIENTS (PATIENT_ID, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT)
VALUES (12, '11111122', 'Omar Al Harthy', 'Male', DATE '1987-10-08', '91110022', 'omar.patient@example.com', 'A+', 'Seeb', 'Mariam Al Harthy', '92110022', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PATIENTS (PATIENT_ID, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT)
VALUES (13, '11111123', 'Layla Al Kindi', 'Female', DATE '2001-03-25', '91110023', 'layla.patient@example.com', 'B+', 'Barka', 'Nasser Al Kindi', '92110023', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PATIENTS (PATIENT_ID, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT)
VALUES (14, '11111124', 'Majid Al Hinai', 'Male', DATE '1979-12-14', '91110024', 'majid.patient@example.com', 'AB+', 'Nizwa', 'Aisha Al Hinai', '92110024', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PATIENTS (PATIENT_ID, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT)
VALUES (15, '11111125', 'Rania Al Rashdi', 'Female', DATE '1996-09-02', '91110025', 'rania.patient@example.com', 'A-', 'Sohar', 'Ahmed Al Rashdi', '92110025', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PATIENTS (PATIENT_ID, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT)
VALUES (16, '11111126', 'Nasser Al Habsi', 'Male', DATE '1983-06-19', '91110026', 'nasser.patient@example.com', 'O-', 'Rustaq', 'Fatma Al Habsi', '92110026', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PATIENTS (PATIENT_ID, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT)
VALUES (17, '11111127', 'Amal Al Maamari', 'Female', DATE '1989-01-30', '91110027', 'amal.patient@example.com', 'B-', 'Ibri', 'Khalid Al Maamari', '92110027', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PATIENTS (PATIENT_ID, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT)
VALUES (18, '11111128', 'Saeed Al Busaidi', 'Male', DATE '1994-08-11', '91110028', 'saeed.patient@example.com', 'AB-', 'Sur', 'Noor Al Busaidi', '92110028', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PATIENTS (PATIENT_ID, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT)
VALUES (19, '11111129', 'Maha Al Lawati', 'Female', DATE '2002-05-06', '91110029', 'maha.patient@example.com', 'O+', 'Muscat', 'Yousuf Al Lawati', '92110029', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PATIENTS (PATIENT_ID, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT)
VALUES (20, '11111130', 'Hamad Al Sinani', 'Male', DATE '1975-11-23', '91110030', 'hamad.patient@example.com', 'A+', 'Nakhal', 'Sara Al Sinani', '92110030', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PATIENTS (PATIENT_ID, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT)
VALUES (22, '87654329', 'Salim Nasser Al Rawahi', 'Male', DATE '2001-07-09', '95551239', 'salim.rawahi@example.com', 'O+', 'Muscat, Oman', 'Nasser Al Rawahi', '96662349', DATE '2026-07-26');
INSERT INTO PATIENTS (PATIENT_ID, CIVIL_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, MOBILE_NO, EMAIL, BLOOD_GROUP, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_NO, CREATED_AT)
VALUES (21, '12345678', 'salwa ariyami', 'Female', DATE '2000-07-18', '91323556', 'safa.alsibani@gmail.com', 'O+', 'Muscat', 'fadhil', '92314556', NULL);

-- =========================================================
-- ROOMS
-- =========================================================
INSERT INTO ROOMS (ROOM_ID, ROOM_NO, ROOM_TYPE, DAILY_RATE, STATUS)
VALUES (1, '101', 'General', 50, 'Available');
INSERT INTO ROOMS (ROOM_ID, ROOM_NO, ROOM_TYPE, DAILY_RATE, STATUS)
VALUES (2, '102', 'General', 50, 'Available');
INSERT INTO ROOMS (ROOM_ID, ROOM_NO, ROOM_TYPE, DAILY_RATE, STATUS)
VALUES (3, '201', 'Private', 100, 'Occupied');
INSERT INTO ROOMS (ROOM_ID, ROOM_NO, ROOM_TYPE, DAILY_RATE, STATUS)
VALUES (4, '202', 'Private', 100, 'Available');
INSERT INTO ROOMS (ROOM_ID, ROOM_NO, ROOM_TYPE, DAILY_RATE, STATUS)
VALUES (5, '301', 'ICU', 300, 'Occupied');

-- =========================================================
-- DOCTORS
-- =========================================================
INSERT INTO DOCTORS (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS)
VALUES (1, 'Dr. Ahmed Al-Harthy', 1, 1, '91111111', 'ahmed@hospital.com', 30, 'Active');
INSERT INTO DOCTORS (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS)
VALUES (2, 'Dr. Fatma Al-Rashdi', 2, 2, '92222222', 'fatma@hospital.com', 25, 'Active');
INSERT INTO DOCTORS (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS)
VALUES (3, 'Dr. Mohammed Al-Balushi', 3, 3, '93333333', 'mohammed@hospital.com', 40, 'Active');
INSERT INTO DOCTORS (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS)
VALUES (4, 'Dr. Salim Al-Hinai', 4, 5, '94444444', 'salim@hospital.com', 35, 'Active');
INSERT INTO DOCTORS (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS)
VALUES (5, 'Dr. Aisha Al-Lawati', 5, 4, '95555555', 'aisha@hospital.com', 45, 'Active');
INSERT INTO DOCTORS (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS)
VALUES (6, 'Dr. Khalid Al-Kindi', 1, 1, '96666666', 'khalid@hospital.com', 30, 'Active');
INSERT INTO DOCTORS (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS)
VALUES (7, 'Dr. Noor Al-Maamari', 2, 2, '97777777', 'noor@hospital.com', 25, 'Active');
INSERT INTO DOCTORS (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS)
VALUES (8, 'Dr. Yousuf Al-Habsi', 3, 7, '98888888', 'yousuf@hospital.com', 20, 'Active');
INSERT INTO DOCTORS (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS)
VALUES (9, 'Dr. Sara Al-Busaidi', 4, 6, '99999999', 'sara@hospital.com', 28, 'Active');
INSERT INTO DOCTORS (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS)
VALUES (10, 'Dr. Hamad Al-Sinani', 5, 4, '90000000', 'hamad@hospital.com', 50, 'Active');

-- =========================================================
-- MEDICINES
-- =========================================================
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
VALUES (1, 'Amoxicillin', 1, 'Capsule', 100, 20, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
VALUES (2, 'Paracetamol', 2, 'Tablet', 250, 50, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
VALUES (3, 'Metformin', 3, 'Tablet', 120, 30, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
VALUES (4, 'Vitamin C', 4, 'Tablet', 200, 40, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
VALUES (5, 'Cetirizine', 5, 'Tablet', 80, 20, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
VALUES (6, 'Ibuprofen', 2, 'Tablet', 150, 30, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
VALUES (7, 'Azithromycin', 1, 'Tablet', 90, 20, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
VALUES (8, 'Insulin', 3, 'Injection', 60, 15, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
VALUES (9, 'Vitamin D', 4, 'Tablet', 110, 25, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
VALUES (10, 'Loratadine', 5, 'Tablet', 95, 20, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
VALUES (11, 'Cefuroxime', 1, 'Tablet', 12, 20, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
VALUES (12, 'Diclofenac', 2, 'Tablet', 18, 25, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
VALUES (13, 'Gliclazide', 3, 'Tablet', 75, 20, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
VALUES (14, 'Multivitamin Syrup', 4, 'Syrup', 8, 15, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
VALUES (15, 'Fexofenadine', 5, 'Tablet', 65, 20, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
VALUES (16, 'Clarithromycin', 1, 'Tablet', 45, 15, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
VALUES (17, 'Naproxen', 2, 'Tablet', 9, 15, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
VALUES (18, 'Glimepiride', 3, 'Tablet', 55, 20, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
VALUES (19, 'Vitamin B Complex', 4, 'Tablet', 100, 25, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS)
VALUES (20, 'Chlorpheniramine', 5, 'Syrup', 10, 18, 'Active');

-- =========================================================
-- APPOINTMENTS
-- =========================================================
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (1, 1, 1, DATE '2026-07-05', '09:00', 2, 'Chest pain and shortness of breath', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (2, 2, 2, DATE '2026-07-06', '09:30', 2, 'Child fever and cough', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (3, 3, 3, DATE '2026-07-07', '10:00', 2, 'Abdominal pain', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (4, 4, 4, DATE '2026-07-08', '10:30', 2, 'Knee pain after exercise', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (5, 5, 5, DATE '2026-07-09', '11:00', 2, 'Recurring headache', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (6, 6, 6, DATE '2026-07-10', '11:30', 2, 'High blood pressure review', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (7, 7, 7, DATE '2026-07-11', '12:00', 2, 'Child stomach pain', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (8, 8, 8, DATE '2026-07-12', '12:30', 2, 'General weakness', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (9, 9, 9, DATE '2026-07-13', '13:00', 2, 'Skin rash', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (10, 10, 10, DATE '2026-07-14', '13:30', 2, 'Migraine follow-up', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (11, 11, 1, DATE '2026-07-15', '08:30', 1, 'Routine cardiac checkup', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (12, 12, 2, DATE '2026-07-15', '09:00', 1, 'Pediatric vaccination review', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (13, 13, 3, DATE '2026-07-15', '09:30', 1, 'Minor injury assessment', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (14, 14, 4, DATE '2026-07-15', '10:00', 1, 'Back pain', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (15, 15, 5, DATE '2026-07-15', '10:30', 1, 'Dizziness', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (16, 16, 6, DATE '2026-07-15', '11:00', 3, 'Cardiology follow-up', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (17, 17, 7, DATE '2026-07-15', '11:30', 1, 'Child allergy', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (18, 18, 8, DATE '2026-07-15', '12:00', 4, 'General medical consultation', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (19, 19, 9, DATE '2026-07-15', '12:30', 1, 'Persistent skin irritation', TO_DATE('2026-07-15 05:51:20','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (20, 20, 10, DATE '2026-07-15', '13:00', 1, 'Neurology assessment', TO_DATE('2026-07-15 05:51:21','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (21, 1, 6, DATE '2026-07-16', '08:30', 1, 'Heart rate review', TO_DATE('2026-07-15 05:51:21','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (22, 2, 7, DATE '2026-07-17', '09:00', 1, 'Child growth check', TO_DATE('2026-07-15 05:51:21','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (23, 3, 3, DATE '2026-07-18', '09:30', 1, 'Emergency follow-up', TO_DATE('2026-07-15 05:51:21','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (24, 4, 4, DATE '2026-07-19', '10:00', 1, 'Orthopedic review', TO_DATE('2026-07-15 05:51:21','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (25, 5, 5, DATE '2026-07-20', '10:30', 1, 'Headache follow-up', TO_DATE('2026-07-15 05:51:21','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (26, 6, 1, DATE '2026-07-21', '11:00', 1, 'Blood pressure monitoring', TO_DATE('2026-07-15 05:51:21','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (27, 7, 2, DATE '2026-07-22', '11:30', 1, 'Pediatric follow-up', TO_DATE('2026-07-15 05:51:21','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (28, 8, 8, DATE '2026-07-23', '12:00', 1, 'General checkup', TO_DATE('2026-07-15 05:51:21','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (29, 9, 9, DATE '2026-07-24', '12:30', 1, 'Dermatology follow-up', TO_DATE('2026-07-15 05:51:21','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (30, 10, 10, DATE '2026-07-25', '13:00', 1, 'Neurology follow-up', TO_DATE('2026-07-15 05:51:21','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, REASON_FOR_VISIT, CREATED_AT)
VALUES (221, 22, 1, DATE '2026-07-27', '10:00', 2, 'Fever and sore throat', DATE '2026-07-26');

-- =========================================================
-- ADMISSIONS
-- =========================================================
INSERT INTO ADMISSIONS (ADMISSION_ID, PATIENT_ID, DOCTOR_ID, ROOM_ID, ADMISSION_DATE, DISCHARGE_DATE, ADMISSION_REASON, STATUS)
VALUES (1, 1, 1, 1, DATE '2026-07-12', DATE '2026-07-22', 'Cardiac observation', 'Discharged');
INSERT INTO ADMISSIONS (ADMISSION_ID, PATIENT_ID, DOCTOR_ID, ROOM_ID, ADMISSION_DATE, DISCHARGE_DATE, ADMISSION_REASON, STATUS)
VALUES (2, 3, 3, 3, DATE '2026-07-13', NULL, 'Post-operative monitoring', 'Admitted');
INSERT INTO ADMISSIONS (ADMISSION_ID, PATIENT_ID, DOCTOR_ID, ROOM_ID, ADMISSION_DATE, DISCHARGE_DATE, ADMISSION_REASON, STATUS)
VALUES (3, 5, 5, 5, DATE '2026-07-14', NULL, 'Neurological observation', 'Admitted');
INSERT INTO ADMISSIONS (ADMISSION_ID, PATIENT_ID, DOCTOR_ID, ROOM_ID, ADMISSION_DATE, DISCHARGE_DATE, ADMISSION_REASON, STATUS)
VALUES (4, 2, 2, 2, DATE '2026-07-07', DATE '2026-07-10', 'Severe respiratory infection', 'Discharged');
INSERT INTO ADMISSIONS (ADMISSION_ID, PATIENT_ID, DOCTOR_ID, ROOM_ID, ADMISSION_DATE, DISCHARGE_DATE, ADMISSION_REASON, STATUS)
VALUES (5, 4, 4, 4, DATE '2026-07-03', DATE '2026-07-06', 'Orthopedic observation', 'Discharged');
INSERT INTO ADMISSIONS (ADMISSION_ID, PATIENT_ID, DOCTOR_ID, ROOM_ID, ADMISSION_DATE, DISCHARGE_DATE, ADMISSION_REASON, STATUS)
VALUES (45, 22, 1, 5, DATE '2026-07-26', NULL, 'Observation due to persistent fever', 'Admitted');

-- =========================================================
-- PATIENT_VISITS
-- =========================================================
INSERT INTO PATIENT_VISITS (VISIT_ID, APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, VISIT_DATE, SYMPTOMS, DIAGNOSIS, NOTES, FOLLOW_UP_DATE)
VALUES (1, 1, 1, 1, DATE '2026-07-05', 'Chest pain, fatigue, shortness of breath', 'Mild hypertension', 'Reduce salt intake and monitor blood pressure', DATE '2026-08-04');
INSERT INTO PATIENT_VISITS (VISIT_ID, APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, VISIT_DATE, SYMPTOMS, DIAGNOSIS, NOTES, FOLLOW_UP_DATE)
VALUES (2, 2, 2, 2, DATE '2026-07-06', 'Fever and cough', 'Upper respiratory infection', 'Rest and maintain hydration', DATE '2026-07-29');
INSERT INTO PATIENT_VISITS (VISIT_ID, APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, VISIT_DATE, SYMPTOMS, DIAGNOSIS, NOTES, FOLLOW_UP_DATE)
VALUES (3, 3, 3, 3, DATE '2026-07-07', 'Abdominal pain and nausea', 'Gastritis', 'Avoid spicy food and drink sufficient water', DATE '2026-07-25');
INSERT INTO PATIENT_VISITS (VISIT_ID, APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, VISIT_DATE, SYMPTOMS, DIAGNOSIS, NOTES, FOLLOW_UP_DATE)
VALUES (4, 4, 4, 4, DATE '2026-07-08', 'Knee pain and swelling', 'Muscle strain', 'Rest the knee and avoid strenuous activity', DATE '2026-07-30');
INSERT INTO PATIENT_VISITS (VISIT_ID, APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, VISIT_DATE, SYMPTOMS, DIAGNOSIS, NOTES, FOLLOW_UP_DATE)
VALUES (5, 5, 5, 5, DATE '2026-07-09', 'Recurring headache and sensitivity to light', 'Migraine', 'Maintain regular sleep and avoid known triggers', DATE '2026-08-05');
INSERT INTO PATIENT_VISITS (VISIT_ID, APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, VISIT_DATE, SYMPTOMS, DIAGNOSIS, NOTES, FOLLOW_UP_DATE)
VALUES (6, 6, 6, 6, DATE '2026-07-10', 'High blood pressure reading', 'Hypertension follow-up', 'Continue prescribed medication and record daily readings', DATE '2026-08-14');
INSERT INTO PATIENT_VISITS (VISIT_ID, APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, VISIT_DATE, SYMPTOMS, DIAGNOSIS, NOTES, FOLLOW_UP_DATE)
VALUES (7, 7, 7, 7, DATE '2026-07-11', 'Stomach pain and reduced appetite', 'Mild stomach infection', 'Take medication after meals', DATE '2026-07-27');
INSERT INTO PATIENT_VISITS (VISIT_ID, APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, VISIT_DATE, SYMPTOMS, DIAGNOSIS, NOTES, FOLLOW_UP_DATE)
VALUES (8, 8, 8, 8, DATE '2026-07-12', 'Weakness and tiredness', 'Vitamin deficiency', 'Improve diet and take vitamins daily', DATE '2026-08-09');
INSERT INTO PATIENT_VISITS (VISIT_ID, APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, VISIT_DATE, SYMPTOMS, DIAGNOSIS, NOTES, FOLLOW_UP_DATE)
VALUES (9, 9, 9, 9, DATE '2026-07-13', 'Skin rash and itching', 'Allergic dermatitis', 'Avoid suspected allergen and use prescribed medicine', DATE '2026-07-29');
INSERT INTO PATIENT_VISITS (VISIT_ID, APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, VISIT_DATE, SYMPTOMS, DIAGNOSIS, NOTES, FOLLOW_UP_DATE)
VALUES (10, 10, 10, 10, DATE '2026-07-14', 'Severe headache and nausea', 'Migraine episode', 'Rest in a dark room and take prescribed medicine', DATE '2026-08-02');
INSERT INTO PATIENT_VISITS (VISIT_ID, APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, VISIT_DATE, SYMPTOMS, DIAGNOSIS, NOTES, FOLLOW_UP_DATE)
VALUES (21, 221, 22, 1, DATE '2026-07-26', 'Fever and sore throat', 'Seasonal flu', 'Patient needs rest and fluids', DATE '2026-07-31');

-- =========================================================
-- PRESCRIPTIONS
-- =========================================================
INSERT INTO PRESCRIPTIONS (PRESCRIPTION_ID, VISIT_ID, PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES)
VALUES (1, 1, 1, 1, DATE '2026-07-05', 'Take medicines according to the instructions.');
INSERT INTO PRESCRIPTIONS (PRESCRIPTION_ID, VISIT_ID, PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES)
VALUES (2, 2, 2, 2, DATE '2026-07-06', 'Take medicines according to the instructions.');
INSERT INTO PRESCRIPTIONS (PRESCRIPTION_ID, VISIT_ID, PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES)
VALUES (3, 3, 3, 3, DATE '2026-07-07', 'Take medicines according to the instructions.');
INSERT INTO PRESCRIPTIONS (PRESCRIPTION_ID, VISIT_ID, PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES)
VALUES (4, 4, 4, 4, DATE '2026-07-08', 'Take medicines according to the instructions.');
INSERT INTO PRESCRIPTIONS (PRESCRIPTION_ID, VISIT_ID, PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES)
VALUES (5, 5, 5, 5, DATE '2026-07-09', 'Take medicines according to the instructions.');
INSERT INTO PRESCRIPTIONS (PRESCRIPTION_ID, VISIT_ID, PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES)
VALUES (6, 6, 6, 6, DATE '2026-07-10', 'Take medicines according to the instructions.');
INSERT INTO PRESCRIPTIONS (PRESCRIPTION_ID, VISIT_ID, PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES)
VALUES (7, 7, 7, 7, DATE '2026-07-11', 'Take medicines according to the instructions.');
INSERT INTO PRESCRIPTIONS (PRESCRIPTION_ID, VISIT_ID, PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES)
VALUES (8, 8, 8, 8, DATE '2026-07-12', 'Take medicines according to the instructions.');
INSERT INTO PRESCRIPTIONS (PRESCRIPTION_ID, VISIT_ID, PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES)
VALUES (9, 9, 9, 9, DATE '2026-07-13', 'Take medicines according to the instructions.');
INSERT INTO PRESCRIPTIONS (PRESCRIPTION_ID, VISIT_ID, PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES)
VALUES (10, 10, 10, 10, DATE '2026-07-14', 'Take medicines according to the instructions.');
INSERT INTO PRESCRIPTIONS (PRESCRIPTION_ID, VISIT_ID, PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES)
VALUES (21, 21, 22, 1, DATE '2026-07-26', 'Take medicines after meals');

-- =========================================================
-- PRESCRIPTION_ITEMS
-- =========================================================
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
VALUES (1, 1, 1, '500mg', 'Twice daily', 7, 'After food');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
VALUES (2, 1, 2, '500mg', 'When needed', 5, 'After food');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
VALUES (3, 2, 7, '250mg', 'Twice daily', 5, 'After food');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
VALUES (4, 2, 20, '5ml', 'Twice daily', 5, 'Shake well before use');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
VALUES (5, 3, 16, '500mg', 'Twice daily', 5, 'After food');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
VALUES (6, 3, 2, '500mg', 'When needed', 3, 'After food');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
VALUES (7, 4, 17, '250mg', 'Twice daily', 7, 'After food');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
VALUES (8, 4, 2, '500mg', 'When needed', 5, 'After food');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
VALUES (9, 5, 6, '400mg', 'When needed', 5, 'After food');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
VALUES (10, 5, 19, '1 tablet', 'Once daily', 30, 'After breakfast');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
VALUES (11, 6, 3, '500mg', 'Twice daily', 30, 'With meals');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
VALUES (12, 6, 9, '1 tablet', 'Once daily', 30, 'After breakfast');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
VALUES (13, 7, 11, '250mg', 'Twice daily', 5, 'After food');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
VALUES (14, 7, 14, '5ml', 'Once daily', 14, 'After food');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
VALUES (15, 8, 4, '1 tablet', 'Once daily', 30, 'After breakfast');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
VALUES (16, 8, 19, '1 tablet', 'Once daily', 30, 'After breakfast');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
VALUES (17, 9, 5, '10mg', 'Once daily', 10, 'At night');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
VALUES (18, 9, 15, '120mg', 'Once daily', 10, 'Before food');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
VALUES (19, 10, 2, '500mg', 'When needed', 5, 'After food');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
VALUES (20, 10, 6, '400mg', 'When needed', 5, 'After food');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS)
VALUES (21, 21, 2, '500 mg', '3 times daily', 5, 'Take one tablet after meals');

-- Synchronize identity generators after explicit IDs were loaded.
-- This prevents future APEX inserts from attempting to reuse ID 1.
ALTER TABLE DEPARTMENTS MODIFY DEPARTMENT_ID GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE DOCTOR_SPECIALTIES MODIFY SPECIALTY_ID GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE MEDICINE_CATEGORIES MODIFY CATEGORY_ID GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE APPOINTMENT_STATUSES MODIFY STATUS_ID GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE PATIENTS MODIFY PATIENT_ID GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE ROOMS MODIFY ROOM_ID GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE DOCTORS MODIFY DOCTOR_ID GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE MEDICINES MODIFY MEDICINE_ID GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE APPOINTMENTS MODIFY APPOINTMENT_ID GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE ADMISSIONS MODIFY ADMISSION_ID GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE PATIENT_VISITS MODIFY VISIT_ID GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE PRESCRIPTIONS MODIFY PRESCRIPTION_ID GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE PRESCRIPTION_ITEMS MODIFY PRESCRIPTION_ITEM_ID GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);

COMMIT;

