services:
  api:
    build: .
    image: ibrahimrahbi/healthcheck:latest
    container_name: "healthcheckapp"
    ports:
      - "8000:8080"
    restart: always
    volumes:
      - ./shared_upload_files:/app/uploaded_files
    restart: always
