--  ****** Create TABLE traffic_signals ********
CREATE TABLE traffic_signals (
  signal_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  signal_name     VARCHAR2(100) NOT NULL,
  state           VARCHAR2(10) DEFAULT 'RED' NOT NULL
                  CONSTRAINT ck_signal_state CHECK (state IN ('RED','YELLOW','GREEN')),
  last_changed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

select * from traffic_signals;


-- ****** Create Procedure check_and_update_signal_status *******

create or replace procedure check_and_update_signal_status (p_signal_id in number)
as
  v_state varchar2(10);
  v_last_changed_at timestamp;
  v_next_state varchar2(10);
  v_required_seconds number;
begin
  select state, last_changed_at into v_state, v_last_changed_at
  from traffic_signals
  where signal_id = p_signal_id;

  if v_state = 'RED' then
    v_next_state := 'YELLOW';
    v_required_seconds := 10;
  elsif v_state = 'YELLOW' then
    v_next_state := 'GREEN';
    v_required_seconds := 5;
  else
    v_next_state := 'RED';
    v_required_seconds := 10;
  end if;

  dbms_output.put_line('checking signal ' || p_signal_id || ' state=' || v_state);

  if systimestamp >= v_last_changed_at + numtodsinterval(v_required_seconds, 'SECOND') then
    update traffic_signals
    set state = v_next_state, last_changed_at = systimestamp
    where signal_id = p_signal_id;
    commit;
  end if;
end check_and_update_signal_status;
/

-- ***** Procedure START_SIGNAL_WATCH ********

create or replace procedure start_signal_watch (p_signal_id in number)
as
  pragma autonomous_transaction;
begin
  dbms_scheduler.create_job(
    job_name        => 'SIG_WATCH_' || p_signal_id,
    job_type        => 'PLSQL_BLOCK',
    job_action      => 'BEGIN check_and_update_signal_status(' || p_signal_id || '); END;',
    repeat_interval => 'FREQ=SECONDLY; INTERVAL=5',
    start_date      => systimestamp,
    enabled         => true
  );
  commit;
end start_signal_watch;
/ 

-- ****** create trigger *******

create or replace trigger handle_traffic_signal
after insert on traffic_signals
for each row
begin
  start_signal_watch(:new.signal_id);
end handle_traffic_signal;
/

-- ******** Insert Traffic Light *********
insert into traffic_signals (signal_name) values ('Seeb Signal');
insert into traffic_signals (signal_name) values ('Al Khuwair Signal');
insert into traffic_signals (signal_name) values ('SUHAR Signal');
commit;


-- connect with an account that has SYSTEM privileges
GRANT CREATE JOB TO SYSTEM;

-- ******** Check Traffic Light Status
select signal_id, signal_name, state, last_changed_at
from traffic_signals;


