name: opencode-review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      
      - name: Configure Git Identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "MentorMind Code Review Agent"

      - name: Review Pull Request with OpenCode
        uses: anomalyco/opencode/github@latest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          model: 'openai/gpt-4o-mini'
          use_github_token: true
          prompt: |
            Rules for reviewing this pull request before posting a comment:
            - Check for indentation consistency. It can be either 4 spaces or 2 spaces, but not a mix of both.
            - Make sure there are no consecutive blank lines in the entire code.
            - Keeping in mind that the code is for practice purposes, check for any obvious logical errors or potential improvements in the code.
            - The title of the pull request is: ${{ github.event.pull_request.title }}. It should start with a clickup id (e.g., "86ex6r17g") followed by a : (e.g., "86ex6r17g: ") and then the title of clickup ticket (e.g., "86ex6r17g: Implement user authentication").
            - The description of the pull request is: ${{ github.event.pull_request.body }}. It should be meaningful and should include a description of the changes made in the pull request, the reason for the changes, and any relevant information that would help reviewers understand the context of the changes.
            Rules for posting a comment on this pull request:
            - Make sure to use a one-liner for each identified issue or each suggested improvement found in the code.
            - Comment should be in proper .md formatting.
            